README.md, blogging.md
Link to the blogging guide more forcefully from the README, and add some high level bullets to the blogging guide about metadata and workflow.
=> Bring blogging points to the front

_posts/2014-12-22-protosketch.md
Thanks @OriHoffer for catching this.
=> Fast formatting fix for protosketing post (1/7)

_config.yml, _posts/2015-01-08-an-open-source-tool-for-easier-database-testing.md
Post is live on staging, this PR is for any pre-publishing edits like capitalization. It also adds `future: false` to the `_config.yml` to hide any posts with publish dates that are in the future.
=> Final edits before publishing

_posts/2015-01-08-an-open-source-tool-for-easier-database-testing.md, _posts/2015-01-08-creating-a-federal-marketplace-for-agile-delivery-services.md, blogging.md
@catherinedevlin thank you very much for this blog post! @OriHoffer @elainekamlley hit the green button to make this live?
=> Final publish rdbms-subsetter post

_data/team.yml
=> Update team list

pages/developer.md
=> adding the Hub api to 18f's /developer page

_posts/2015-01-16-open-source-for-good-government.md
This centers the tweet proposed in the post in #465.
=> Center the tweet

.travis.yml
Uses Docker and is way faster:
http://docs.travis-ci.com/user/workers/container-based-infrastructure/
=> Try out Travis' new container infrastructure

_posts/2015-02-09-the-first-gov-domains-hardcoded-into-your-browser-as-all-https.md
=> Typo in HSTS post

.gitignore, README.md, _config.yml, _posts/README.md, script/post
Greatly simplified blogging instructions per the new workflow we introduced a couple weeks ago. @18F/rearchitects your feedback is welcomed.
Also closes #511
=> Blog instructions

Gemfile.lock, _data/import-public.rb, _data/projects.yml, _data/team.yml, go
Corresponds to 18F/dashboard#190.
cc: @gboone @elainekamlley
=> Switch to split-file data-private format

_posts/2015-02-25-We-Are-Hiring.md
Slightly modified design job description + modified wording of diversity paragraph
=> brief edits to design description and last paragraph

_plugins/author.rb, _posts/2015-03-02-cos-post.md
- the author plugin needed updating to search for PIFs
- Ty Grandison is a PIF and we should pull his data out with the plugin
=> Uses {% author %} for cos post and updates plugin

_posts/2015-02-24-how-to-use-github-and-the-terminal-a-guide.md
This is for you, @melodykramer  and @gboone.
You'll notice that some changes are just cleaning up trailing whitespace. That's because my Sublime Text is configured to automatically delete them when I save a file, using the [TrailingSpaces](https://github.com/SublimeText/TrailingSpaces) plugin, which I highly recommend.
I also wanted to ask about this statement: `If you follow these instructions for any project you're working on in GitHub, they will work the same way`. Did you mean that the reader should expect pull requests to fail for other projects, or to work for other GitHub projects?
If the latter, that would not be entirely accurate because only people who have write access to a repo can submit pull requests after cloning a repo. No one can submit a PR to any repo they don't have …
=> Fix typos and clarify a few things.

_posts/2015-02-24-how-to-use-github-and-the-terminal-a-guide.md
Thank goodness for crowdsourcing! We caught this missing bit after [a conversation on Twitter.](https://twitter.com/heatherfro/status/572899679505133571)
=> Gah! We missed a step!

_posts/2015-02-24-how-to-use-github-and-the-terminal-a-guide.md
Found some more typos, and some of the table of content links were broken. I fixed them and made the capitalization consistent, using the AP Style Guide for titles. Not sure if we're using any particular style guides.
If this looks good, I can fix the merge conflicts and push again.
=> More minor fixes.

_posts/2015-03-06-ux-lessons-learned-from-a-procurement-project.md
=> UX Lessons Learned From A Procurement Project

_posts/2015-03-05-Labor-Category-Descriptions-for-Agile-Procurements, _posts/2015-03-05-Labor-Category-Descriptions-for-Agile-Procurements.md
@cscairns Let us know if you think of a good image for this post, otherwise we're good to roll with this later this afternoon, cc: @18F/blog
=> Agile descriptions post

_posts/2015-03-11-onet-today-and-beyond.md
The O*NET blog post's images are broken, and have incorrect formatting. This fixes all of those. Did this get eyeballed on staging before deploy?
=> Fix O*NET images and formatting

_posts/2015-03-13-how-to-protosketch.md
Slated for publication EOD today. cc: @RobertLRead @adelevie @18F/blog
=> First pass at How to Protosketch

_posts/2015-03-18-sunshine-week-extractive-industries-transparency-initiative-event.md
me and my trusting `pandoc` too much
=> sloppy markdown conversion

_posts/2015-03-19-18f-by-the-numbers.md
Here's the 18F by the numbers post!
=> 18f by the numbers post

_posts/2015-03-19-18f-by-the-numbers.md
=> updated image info

_posts/2015-03-19-18f-by-the-numbers.md
Adding a byline for @ericadeahl
=> erica's byline

_posts/2015-03-17-does-18f-pass-the-bechdel-test-for-tech.md, _posts/2015-03-17-for-public-comment-the-https-only-standard.md, _posts/2015-03-19-18f-by-the-numbers.md, _posts/2015-03-19-how-we-built-analytics-usa-gov.md, _posts/2015-03-20-one-year-in-and-looking-forward.md
cc: @18F/blog Merge if we're happy :smile_cat:
=> Deploy One Year in and Looking Forward

_posts/2015-03-24-making-twitter-images-more-accessible.md
Adds link to accessibility post
=> Added link suggested by Daniel Morgan at DOT

_posts/2015-03-30-new-rfp-ghostwriting-service-to-improve-contract-success.md
@kategarklavs this adds the open graph image (derp, #gregboonefail)
=> adds image to frontmatter

assets/_sass/_custom.scss, pages/index.html
=> Fixes remaining two accessibility warnings

pages/index.html
Must remember to revert this tomorrow morning...
=> April Fools!

README.md, pages/index.html
Turns out sometimes it takes a little more than turning it off and on again.
=> Revert April Fools 2015

_includes/head.html
This method asynchronously loads fonts as soon as possible, while not
blocking render, then stores the result in localStorage for future
visits.
This has been documented here:
http://www.filamentgroup.com/lab/font-loading.html
TODO, there could be improvements made to this later down the line:
- Separate each type of font file (ttf, woff) into a separate file
with font data base64 encoded. Program if statement for different types
- Use font loading events to apply font class after font loaded.
=> Improving font performance.

_includes/head.html
It got broken when converted to JS, it's supposed to include a `.min` in the file name.
=> Fix font loading

deploy/18f-site.conf
https://18f.gov -> https://18f.gsa.gov
=> Handle 18f.gov redirect

_layouts/post.html
Now post pages have zero automatically-detected 508 issues.
=> Fixed 508 issue with logo in post template.

_posts/2015-04-21-hackathons-not-just-for-folks-who-code.md
A few cosmetic changes on the hackathon post
=> Renamed, reheadlined, unbolded/italic links

_posts/2015-04-20-act-iac-event-on-devops-in-the-government.md
=> Update ACT IAC post in production

_posts/2015-04-23-coming-soon-the-agile-delivery-services-soliciatation.md
@cscairns @NoahKunin @vzvenyach cc: @18F/blog 
Sorry for the delay getting this out.
=> Rfq announcer

_posts/2015-04-23-coming-soon-the-agile-delivery-services-soliciatation.md
Apparently @NoahKunin snuck some edits in between my downloading the post and the PR earlier. This is a quick fix.
=> A few edits from Kunin

_posts/2015-04-23-the-dat-team-talks-data-streams.md
The byline needs to be explicit.
=> Fix byline for Max post

_posts/2015-04-29-18f-how-we-write.md
Addresses @quepol's question at c3b7586
=> hub.18f.us/hub isn't public, 18f.gsa.gov/hub is

_posts/2015-05-01-pair-programming-why-two-heads-are-better-than-one.md
=> fixed date 

_team/noah.md
Noah M is in twice (here and at his last name), put in my bio at `noah.md`.
Mild suggest to the team that we switch to a file format of First Initial + Last Name [ex: nkunin.md] to resolve disambiguation as we scale.
=> Too Many Noahs

deploy/fabfile.py, go
@elainekamlley  has full license to send me a SMH on Slack.
The `production_build` command had the wrong name in the list of commands. So it doesn't work in production. :/
=> Sloppy sloppy sloppy, @gboone

_team/majma.md
Wanted to do a quick edit of the project blurb. Forgive me if I messed up the PR.
=> quick fixes

_team/eric.md
Gave it a once-over. Thanks for getting it started!
=> Rewrote my bio a bit

_team/leah.md
Dupe of #832 but applied to the `staging` branch
=> adjusting for accuracy... :)

_team/yuda.md
Dupe of #798 but to the `staging` branch.
=> Update John's Bio

pages/consulting.md
Updating our content on the /consulting page.
=> Updating 18F Consulting copy

_posts/2015-05-12-announcing-the-calc-tool.md
and edited More Details on the Data
=> added digital tool paragraph

_data/services.yaml, assets/_sass/_custom.scss, pages/index.html
Several advantages to making services a data file, including having them show up in our data api. (Will be here: https://18f.gsa.gov/api/data/services.json), but also makes the homepage template cleaner by having something to iterate through. We can easily bring these data into their respective pages and/or use them in other parts of the site eventually. We could connect them to team members, blog posts, etc.
=> One more line height fix and makes services data files

_data/services.yaml
=> pages instead of sites

_posts/2015-05-29-moveforward-analytics-video.md
=> moveForward Analytics video post

_team/ericronne.md
=> Changed "most recently" to "recently"

_posts/2015-06-03-giving-back-to-open-source.md
=> Fix "Giving back to open source" off-by-one error

_posts/2015-04-01-govtechhack-hacking-for-civic-improvement.md, _posts/2015-04-03-how-to-welcome-new-coders-to-a-civic-hackathon.md
to 2 old blogs posts so I can tweet the tags/hackathon link and have it be awesome.
=> add hackathon tags

pages/consulting.md
@elainekamlley @gboone Made some minor style/finesse/grammar edits here. Take a look for me?
=> Style edits for 18F Consulting

assets/_sass/_custom.scss
List styles, spacing, and margins should be standardized across blog posts _and_ the `bare` template now.
=> List type fix

Gemfile.lock, _data/services.yaml, pages/delivery.md
18F Delivery page content. @elainekamlley: bullet points are still being obstinate.
=> 18F Delivery Content

_includes/scripts.html
As per requirements in https://www.digitalgov.gov/files/2015/02/GSA-DAP-UA-Code-Quick-Guide-15-01-30-v1-02_mvf.pdf
=> Adds DAP agency abbreviation as required

_posts/2015-06-11-18f-at-national-civic-hacking-day.md
h/t to my grandmother, who caught it.
=> Correcting typo in excerpt

pages/thank-you.md
Updated headline and text to be more explanatory. Extended timeout from 20 to 30 seconds.
=> text changes

_data/services.yaml, pages/index.html
Adding updated front page content for more consistency. Thanks to @awfrancisco, great work!
=> updated front page content

_posts/2015-06-02-taking-the-pulse-of-the-federal-governments-web-presence.md
Apparently jtindel was not listed in the frontmatter, this fixes that
=> Adds jtindel as an author

feed.xml
=> Adds new filtered authors to the feed

_team/jacobharris.md
Added my github and twitter accounts. Also tightened up the text a little. Thank you.
=> Edits to the bio for Jacob Harris

_team/jeremy.md
- typo: "leared" -> "learned" (though i do like the idea of leering at how government works)
- cleaned up some phrasing in the quote 
- role  "UX Researcher" (was only one here, not how I self ID) -> "User Experience Designer" (others here have this title, is one of the things ppl call me)
=> fixed some typos/language issues, changed role to be consistent with others at 18F

_team/eric.md
I removed the third-person paragraph, removed my affiliation with the (now nonexistent) Policy Guild, and reworded things slightly.
=> Further rewrote my bio a bit

_team/vdavez.md
=> Avoid potential confusion that I'm 18F's lawyer

_posts/2014-08-12-the-contributors-guide-to-18f-code-for-the-common.html, _posts/2014-08-21-creating-an-open-fec.html, _posts/2014-09-04-a-new-look-at-the-freedom-of-information-act.html, _posts/2014-09-08-the-encasement-strategy-on-legacy-systems-and-the.html, _posts/2014-09-15-say-hello-to-the-new-presidential-innovation-fellows.html, _posts/2014-09-18-getting-to-work-for-the-american-people.html, _posts/2014-09-25-design-studio-onrr.md, _posts/2014-10-01-open-source-hack-series-midas.md, _posts/2014-10-21-how-to-run-your-own-3-sprint-agile-workshop.md, _posts/2014-11-13-why-we-use-https-in-every-gov-website-we-make.md, _posts/2014-11-17-taking-control-of-our-website-with-jekyll-and-webhooks.md, _posts/2014-11-26-how-to-use-more-open-source.md, _posts/2014-12-10-great-community-turnout-for-open-source-hack-night.md, _posts/2014-12-11-large-scale-development-culture-change.md, _posts/2014-12-12-going-to-gov-college.md, _posts/2014-12-17-snippets.md, _posts/2014-12-18-a-complete-list-of-gov-domains.md, _posts/2014-12-22-protosketch.md, _posts/2014-12-23-hub.md
Headlines, sub-heads, and some other tricky words fixed (lists, government, federal, agile, and so on)!
=> Capitalization standardization through end of 2014

_team/joshcarp.md
=> Minor edits

_includes/logo.html, _layouts/profile.html, assets/_sass/_custom.scss
Deceptive branch name. This closes #992 by moving the "Back to all people" link beneath the logo.
=> Moves the "back to profiles" link beneath the logo

_team/egoodman.md, _team/emileigh.md
one more commit to remove USCIS from my projects (since I'm not working on it).
=> small error in Emileigh bio

_posts/2015-07-15-openfec-api-update.md
added indentation to make it easier to read and found a stray () that i removed.
Thanks!
=> formatting json

_posts/2015-07-16-introduction-to-https-webinar.md
I made some formatting fixes, and removed the manually added anchors -- our blog system generates anchors automatically for every subheader.
=> Formatting changes to HTTPS webinar post

_team/jacobharris.md
I was just browsing and found some stuff.
=> Fixed a couple of typoes and redundancies

Gemfile, Gemfile.lock
@konklone will this ensure we don't accidentally upgrade recarpet again?
=> Freezes redcarpet at v 3.2.3

_team/egoodman.md, _team/jeremiak.md
Updates Liz, Victor V., Cristina, and Jeremia's front matter
=> Updates a few team profiles with expected frontmatter

_posts/2015-05-18-myusa.md
Adds the myusa tag to the post from May 18th. cc: @jackiekazil
=> Add myusa tag

_team/christinabrydges.md, _team/victorvalvidiezo.md
Augments #1055 with a commit I forgot to push.
=> Adds frontmatter to Victor V and Cristina B's profiles

_press/18F-open-source-projects.md
Specifically, rephrases as a declarative instead of a question.
=> Styles the title more consistently with the style guide

_press/18F-open-source-projects.md
Added press page that describes how others use our projects.
=> added new press page

_config-deploy.yml, _press/18F-accomplishments.md, _press/18F-consulting.md, _press/18F-relationship-with-united-states-digital-service.md, _press/history-of-18F.md, _press/how-does-18F-work.md, _press/how-is-18F-funded.md
Edited all sections for style and format. 
Added additional accomplishments 
Removed reference to unfinished blog post.
=> Updates and edits to the press page

_posts/2015-08-06-communicart-tool-will-streamline-purchase-card-process.md
Deploys #1080 to production fixing a typo caught by @bsweger. (Thanks, @bsweger!)
Also, does a 1080.
=> Does a 1080

_posts/2015-08-06-communicart-tool-will-streamline-purchase-card-process.md
=> A correction for C2.

_team/julia.md
Small pull request with a few bits of update information.
=> Updating Julia Elman bio with city, twitter and github handles.

_team/stephanierivera.md, _team/will.md
This PR adds "18F Intake" as a project for @StephanieRivera and myself.
=> Adding intake project

_data/authors.yml
=> Removes a duplicate entry for Garren

_includes/nav.html, assets/_sass/_custom.scss, pages/index.html
Also changes language next to the sign up form. And changes "contact" to "newsletter" in the nav. Includes changes from #952 and #1045 without having to deal with merge conflicts. 
@gboone @melodykramer @andrewmaier can you review and merge?
=> Update contact section to newsletter

_team/holly.md
=> Small edits

_team/anna.md
Thanks for getting this posted @elainekamlley! Making a few small edits to grammar and word order on my bio to practice making a pull request.
=> Small content and grammar changes to Anna's bio

_team/victorvaldiviezo.md
We've been spelling Victor's last name wrong all this time! I'll go hide in embarrassment now. Sorry, Victor!
=> Spell check: Team member's last name edition

assets/_sass/base/_typography.scss, assets/_sass/base/extends/_button.scss
Only apply antialiasing to high-resolution displays.
=> Update _typography.scss and _button.scss

_posts/2015-09-17-new-citizenship-resources-demystify-the-naturalization-process.md
=> Dedupe links, fix bullet formatting

_press/18F-accomplishments.md
Also reordered list to bring some larger projects towards the top and put our policies at the bottom.
=> Add Every Kid in a Park, College Scorecard, and Federalist. 

feed.xml
=> Fixes the feed error caused by funky chars in titles

.about.yml
=> Adds an about.yml file!

_posts/2015-09-21-cfpb-design-speaker-series.md
=> Refine the CFPB mission statement line

_data/authors.yml, _posts/2015-09-22-usa-gov-launches-vote-usa-gov-to-help-citizens-register-and-connect-with-states.md
=> Deploy typo fix

_data/authors.yml, _posts/2015-09-25-web-design-standards.md
Figured I'd save you some work, and have ported all the edits I just made to the Google Doc over here. Made the URL changes separate commits in case I missed a memo about the playbook URL changing. Otherwise, the link to the Standards was incorrect each time.
/cc @awfrancisco @gboone
=> Final edits

_posts/2015-09-28-web-design-standards.md
=> Spelling fixes

_team/khandelwal.md
I've now moved over to consulting. My 18F website profile should reflect that.
=> Update profile to reflect new position

_posts/2015-10-09-cloud-gov-launch.md, _posts/2015-10-14-whats-in-a-name-understanding-and-using-gov-acronyms.md
This deploys the first post written partially with the Federalist platform! @dhcole @18F/blog
=> Publishes: What's in a name: Understanding and using government acronyms

_posts/2014-11-26-how-to-use-more-open-source.md
Thanks to @rtwell for noticing this table was not accessible.
=> Makes more accessible the HTML table in the post

_posts/2014-11-26-how-to-use-more-open-source.md, _posts/2015-09-09-how-a-two-day-spring-moved-an-agency-twenty-years-forward.md, _posts/2015-10-13-open-source-micropurchasing.md, _posts/2015-10-14-whats-in-a-name-understanding-and-using-gov-acronyms.md
Sends #1219 and #1244 to production
=> Deploy tag and a11y fixes to production

_posts/2015-10-15-best-practices-for-distributed-teams.md
=> Fixes the responsiveness of the vine embed

_posts/2015-10-15-best-practices-for-distributed-teams.md
A couple small style things I noticed just now. 
cc @awfrancisco @melodykramer
=> quick stylings

_posts/2015-10-15-best-practices-for-distributed-teams.md, assets/_sass/components/_components.scss, assets/_sass/components/_embeds.scss
OK, first attempt didn't quite work out. Here's another attempt at responsive embedding.
=> Fixes responsive embeds

_posts/2015-09-28-web-design-standards.md
=> Fix a Typo

.about.yml
=> egoodman => esgoodman

_posts/2015-10-09-cloud-gov-launch.md
Also tags the only (so far) cloud.gov post with it.
=> Adds a cloud-gov specific tag

_team/jfinch.md
Also adds cloud.gov to the press page.
=> Published the micro-purchase announcement 

_data/authors.yml
=> Adds instructions for editing the authors.yml file

_posts/2015-11-06-micro-purchase-lessons.md
- Small edits for smoother readability (imo)
- Also added the link to the googles apps script source code
=> Minor edits to micropurchase

pages/delivery.md
Closes #1274
Thanks for the suggestion, @jtag
=> Removes the MyUSA post from the delivery page.

_posts/2015-11-09-conversation-with-cfpb-natalie-kurz.md, _posts/2015-11-17-choose-design-over-architecture.md, _team/jj-moy.md, go
Links to the correct image in today's post. Adds an alt attributue to an
old post and patches to go script to make it run all the tests.
=> A11y fix, image fix for today's post, team name, go updates

go
MY BAD, everyone. I had this commented out while I was testing the
script and it looks like I forgot to uncomment before pushing it up.
This will fix the errors in building production.
=> Un-comments the git commands

_posts/2015-11-30-complex-data-in-useiti.md
Deploys a copyright attribution fix
=> Corrects attribution on the pumpjack icon.

_posts/2015-05-21-TockingTime.md
Fixes the permalink and adds a redirect just in case the camelcase URL is out there somewhere.
=> Tocks time correctly

_posts/2015-11-30-complex-data-in-useiti.md
The pumpjack icon was CC-BY. So, I updated the attribution, but didn't pull down to preview. Review, plz! Thank you!
=> Adds more specific attribution to pumpjack icon.

_includes/head.html
cc: @gbinal @18F/blog this will open up the Google Search Console (long overdue).
=> Adds the google search console code

_posts/2015-12-07-what-exactly-do-we-even-do-all-day.md
We should put a question mark at the end of that headline. I think.
=> What would you say you *do* here?

_team/kara.md
=> Update Kara's profile

_posts/2014-11-26-how-to-use-more-open-source.md
=> Fix typo in 2014-11-26-how-to-use-more-open-source.md

_posts/2015-12-11-how-we-test-18f-gsa-gov.md
=> Updates opengraph image for how we test post

_posts/2015-12-17-plain-language-betafec-new-content-design.md, _posts/2015-12-17-the-agile-bpa-is-ready-to-launch.md
attn: @18F/blog @awfrancisco @vzvenyach
=> The latest on the agile bpa

_team/amanda-robinson.md
This is a bio for @ertzeid for the 18F website.
attn: @18F/blog @18F/content
=> Adds a bio for Amanda R.

_team/mossadeq-zia.md
=> Adds a bio for Mossadeq Z

_posts/2015-12-22-uk-digital-service-visits-us-to-begin-series-of-exchanges.md
If we're going to U.S. we should also U.K.
=> Standardizes punctuation

_posts/2015-12-23-looking-back-2015-our-own-words.md, _posts/2015-22-23-looking-back-2015-our-own-words.md
@melodykramer @18F/blog @quepol This posts the 2015 year in review blog post to staging.
=> 2015 in review

_team/randy-hart.md
cc: @randyhart @18F/blog @18F/content
=> Adds Randy's bio

_team/britta-gustafson.md
cc: @18F/content @18F/comms and @brittag
=> Adds a bio for Britta G.!

_press/18F-open-source-projects.md
Moved from [this spreadsheet](https://docs.google.com/spreadsheets/d/1LyUHCacNsQtzyJnOEWW4sn2IhMlITqXCW5PiqSE-JhY/edit#gid=647424526).
/cc @melodykramer
=> link to the DC fork of the Guides Template on the Press page

_data/authors.yml, _posts/2015-12-29-is-your-project-using-agilefall.md
Adds Christopher Goranson, Alan Brouilette, and Alan Atlas as authors
=> Agilefall post, adds 3 authors

_team/adrian-webb.md
@adrianwebb cc: @18F/blog @18F/content @awfrancisco
=> Adds a bio for Adrian

_plugins/embeds.rb, _posts/2014-12-11-large-scale-development-culture-change.md, _posts/2014-12-12-going-to-gov-college.md, _posts/2015-05-29-moveforward-analytics-video.md, _posts/2015-06-11-18f-at-national-civic-hacking-day.md, _posts/2015-06-11-moveforward-map-give-video.md, _posts/2015-06-25-improving-healthcare-gov-experience.md, _posts/2015-07-16-introduction-to-https-webinar.md, _posts/2015-08-06-communicart-tool-will-streamline-purchase-card-process.md, _posts/2015-10-02-building-a-better-government-design-team.md, _posts/2015-11-13-answering-common-questions-about-cloud-gov.md, _posts/2015-12-30-turning-learning-up-to-11.md, assets/_sass/components/_embeds.scss
This will make it easier for editing in federalist's editor eventually. In the meantime it will make sure all youtube embeds are properly scaled at smaller screen sizes. cc: @18F/blog
=> Adds a filter for youtube embeds

_posts/2015-08-07-technical-debt-1.md, _posts/2015-09-04-what-is-technical-debt.md, _posts/2015-10-05-managing-technical-debt.md
Added links to next post in series in last line of each post.
=> Add links to last line of technical debt blog posts

_team/brandon.md
@brandocalrissian's bio for 18f.gsa.gov, cc: @18F/blog @18F/content
=> Brandon Kirby's bio!

_posts/2016-01-04-turning-learning-up-to-11-transparency.md, _posts/2016-01-05-turning-learning-up-to-11-knowledge-sharing.md
=> Turning learning up to 11 post 3

_press/18F-open-source-projects.md
=> link to the other uses of analytics.usa.gov

_posts/2015-05-12-announcing-the-calc-tool.md, _posts/2015-12-01-how-we-dramatically-improved-18fs-onboarding-process-in-3-months.md, _posts/2016-01-05-turning-learning-up-to-11-knowledge-sharing.md, _posts/2016-01-07-tips-for-adapting-analytics-usa-gov.md
=> Publishes the analytics adaptation post

_posts/2016-01-06-tips-for-adapting-analytics-usa-gov.md
This should redirect any requests for the post with the old date to the correct place.
=> Adds a redirect from the old date to the correct url

_data/authors.yml, _posts/2016-01-07-announcing-the-18f-micro-purchase-platform.md
=> Deploy redirect for analytics post

_team/kaitlin.md
Have a great detail, @kaitlin!
=> Update Kaitlin's profile

_posts/2016-01-21-what-we-can-learn-from-the-interiors-social-feeds.md
=> added missing period

_data/authors.yml, _posts/2016-01-25-how-user-story-estimation-helps-my-team-deliver-value.md
=> User story estimation post

_data/authors.yml, _posts/2016-01-22-18f-writing-lab.md, _posts/2016-01-25-how-user-story-estimation-helps-my-team-deliver-value.md
=> Publishes the User story estimation post

_posts/2016-01-25-how-user-story-estimation-helps-my-team-deliver-value.md
(everything adheres to the style guide)
=> fixing typos and punctuation issues

_team/michael-cata.md
Just editing my profile and dusting off my github knowledge
=> Bio Edit, mcata

_config-deploy.yml, _config-staging.yml, go
Should fix staging and production. I guess I thought these servers were aware of their own hostnames
=> Baseurl fix

_config-deploy.yml, _config-staging.yml
=> Final config fixes

_data/authors.yml, _posts/2016-02-02-new-us-digital-registry-authenticates-official-public-service-accounts.md
Also adds Justin Herman as an author.
=> Digital registry xpost

_team/cm.md
A friend pointed out some typos and I realized this was rather out of date.
=> Typos/Updates to CM Bio

_config-deploy.yml, _config-staging.yml, go
Verify this closes #1497 once it's on staging.
=> Should fix the feed issue on 18f.gsa.gov.

_posts/2016-02-12-happy-valentines-day-from-18F.md
=> Fixes the roses-violets tweet link

_posts/2016-03-02-strategies-people-use-when-interacting-with-the-federal-government.md
https://github.com/18F/blog-drafts/issues/412
=> add post 3

_includes/flag.html
=> Fixes gov capitalization

_posts/2016-03-08-too-many-options-make-complicated-decisions-harder.md, _posts/2016-03-09-trust-as-a-two-way-street.md
https://github.com/18F/blog-drafts/issues/417
=> FFD Post #8: Trust as a two-way street #417

_posts/2016-03-11-designing-services-that-are-accessible-transparent-and-easy-to-use.md
https://github.com/18F/blog-drafts/issues/419
=> FFD Post #10 - Designing services that are accessible, transparent, and easy for all to use. #419

_posts/2016-03-10-announcing-the-launch-of-the-digital-acquisitions-pilot.md
It looks like there was a plan to add another citation, but that wasn't followed through on. I removed the link that's attached to no text, leaving only the ones already showing up (presumably the ones that passed editing muster).
=> Fix double period at end of sentence

_team/jessie-posilkin.md
updating the city - I live in DC, not SF
=> Updating my city

_posts/2016-03-22-what-was-your-path-to-18f.md, _posts/2016-03-23-what-have-you-loved-working-on.md
=> Anniv part 3

_posts/2016-03-23-how-to-integrate-the-draft-us-web-design-standards-into-existing-projects.md
Publish date doesn't have a time. Might have to add to coordinate with the anniversary post.
=> Standards design strategy

_posts/2016-03-23-how-to-integrate-the-draft-us-web-design-standards-into-existing-projects.md, _posts/2016-03-23-what-have-you-loved-working-on.md
Final fixes for anniversary part 3
=> Part 3 touchups

_posts/2016-04-07-making-more-consistent-decisions-with-design-principles-a-new-18f-guide.md
Closes #1628 and replicates the change
=> remove photo

_posts/2016-04-06-take-our-code-18f-projects-you-can-reuse.md
Turns out it wasn't as reusable as we thought. @brittag can you verify I got the right one removed?
=> Removes the feedback widget

_posts/2015-12-07-what-exactly-do-we-even-do-all-day.md
I totally get the idea here, and I do talk about the helpful benefits of our staff feeling vaguely watched as they do their work. As a government team, I think it'd be best to avoid references to CCTV cameras and surveillance as explicit analogies for this effect, though.
=> Avoid framing the benefits of openness as one of "surveillance"

_data/authors.yml, _posts/2016-04-22-what-is-an-api.md
=> What is an API post

assets/_sass/components/_bare.scss, pages/index.html
I don't know about y'all, but for breakfast tomorrow, I'm having starfish and coffee, maple syrup and jam. Butterscotch clouds and tangerine, and a side order of ham.
=> Reverts the logo back to the classic #1188ff

_plugins/author.rb
Reverts 18F/18f.gsa.gov#1638 and hopefully fixes all the build failures. I have no idea when I merged that PR, but I have no memory of doing so.
=> Revert "Author archives"

_includes/nav.html
Missed a couple of the new pages in the global nav when I was doing the content work earlier.
=> Adds join and hire to the global nav

_layouts/bare.html, assets/_sass/components/_globalnav.scss
This PR fixes a few UI bugs re: the current navigation.
I think we should consider further clean-up & refactoring of this component, but in the short-term wanted to address these small things.
Before:
After:
=> navbar short-term fixes

_includes/footer.html
=> add trailing slash to footer links

_config.yml, pages/feed.md
Closes #1715 Thanks to @jeremiak for a big assist on this. One of those one-word-in-the-pull-request-makes-all-the-difference-and-took-forever-to-figure-out situations.
=> Xml feed fix

_includes/head.html
one more fix caught by @jeremiak
=> Updates the feed location in the <head>

_posts/2016-05-13-how-18f-handles-information-security-and-third-party-applications.md
Clarifies how the integration worked and adds an editors note.
=> Google - Slack integration clarification

_layouts/project.html
this should fix the current project page rendering / redirect issue
=> fix project page layout

_includes/dashboard-contact.html, _includes/projectlist.html, pages/dashboard/stages.html
=> Fixes and restores the stages page to the dashboard

_team/shawnique.md
updated profile while doing a github refresh
=> Updated Profile

_team/eric.md
=> Simpler bio for @eric

_press/18F-open-source-projects.md
=> link to City of Santa Monica analytics

_posts/2016-05-31-taking-an-agile-approach-to-content.md
=> fix "sections sections" typo

_posts/2015-06-08-data-act-data-act-explainer.md
Adds the data act tag so it's grouped with other posts about the project.
=> Add the data act tag

_posts/2016-06-17-exciting-additions-to-analytics-usa-gov.md
We left Markdown in the OpenGraph tags for the DAP post.
=> Fix OpenGraph metadata on DAP update post

_posts/2016-06-24-5-lessons-in-object-oriented-design-from-sandi-metz.md
=> Fix small typo

pages/what-we-deliver.md
Approved by CPS and @StephanieRivera 
cc @gboone
=> New CPS blurb

_posts/2015-09-15-federalist-platform-launch.md
sets the URL for the content guide to the federalist-docs site
=> update content guide link

_posts/2016-07-07-when-a-micropurchase-doesnt-work-out-we-try-to-learn-from-it.md
Indeed we do. Here's the post for publication tomorrow, pending final layout review by @mtorres253 and/or @vzvenyach
=> When a micro-purchase doesn’t work out, we try to learn from it

_posts/2016-06-30-6-ways-a-writing-lab-will-help-your-organization.md
To keep consistent with other posts on the topic of content design. Thanks for flagging @nicoleslaw
=> Change content to content design

_posts/2016-07-11-conversation-about-static-dynamic-websites.md
May be holding this a few days while we sort out editorial plans. It's here when we need it.
=> Static vs. dynamic websites

_posts/2016-07-13-3-ways-for-digital-acqusition-teams-to-work-better.md
When the authors are OK with the preview, we can publish.
=> Adds the Digital Acquisition teams post

_posts/2016-07-13-technology-transformation-services-looking-for-new-commissioner.md
Publish after 3PM Eastern. cc: @18F/blog @awfrancisco
=> TTS Commissioner annoucement

_posts/2016-07-14-elaine-kamlley-a-developer-commited-diversity.md
@18F/blog @elainekamlley when we're happy with the preview, we can merge at any time
=> Elaine Kamlley: A developer committed to diversity

_posts/2015-03-06-ux-lessons-learned-from-a-procurement-project.md
Tiny little typo in the question.
=> Line 122 - "Ddiscovery" changed to "Discovery"

_posts/2016-06-20-build-empathy-with-stakeholder-interviews-part-1-preparation.md
It was missing the "discover" folder in the URL.
=> Corrected link to Stakeholder Interviews Method Cards

_posts/2016-08-16-what-happens-when-the-whole-team-joins-user-interviews.md
=> Hyperlink "CALC" to post announcing CALC

_posts/2016-08-11-holly-allen-helping-engineer-a-better-18F.md
We should make a note for the redesign to adjust these caption styles so we don't have to `<br>` so much.
=> Adjusts holly's caption and text spacing

_posts/2015-12-17-the-agile-bpa-is-ready-to-launch.md
=> Change link text

_posts/2015-09-09-how-a-two-day-spring-moved-an-agency-twenty-years-forward.md
=> Remove links to scripts

Gemfile, Gemfile.lock, _config.yml
=> Modifies some search engine and share settings

_posts/2016-08-31-kanban-for-government.md
Fixing "dramatica" to "dramatic" in the post preview text.
=> Fixing a typo in the kanban for government post

_includes/footer/desktop.html, _includes/footer/mobile.html
Now points to correct repo + the specific page! You may just want to point to the right repo.
=> change footer links

pages/stages.html
=> Replace stages page

_posts/2016-09-12-james-scott-automating-engineering-better-government.md
=> James Scott's profile

_posts/2015-10-29-welcome-to-betafec.md
=> Remove animated hero image

_data/authors.yml, _posts/2016-09-27-pro-tips-for-data-friendly-regulations-proposals.md
attn: @18F/blog @tadhg-ohiggins @jehlers @Journerdism 
I will post the preview link in Slack.
=> Adds: Pro tips for data-friendly regulations and proposals

_posts/2016-09-19-vendors-government-strengthen-partnership-technology-industry-day.md
Just two quick typo fixes for the TTS industry day post.
=> Minor typo fixes on 2016-09-19 post

_posts/2016-10-04-what-is-static-source-analysis.md
=> Publishes: What is Static Source Analysis

_posts/2016-09-20-mississippi-agile-modular-techniques-child-welfare-system.md
"mississippi" to "state and local practice"
=> Change tag

_posts/2016-07-29-live-streamed-demos-for-exponential-transparency-and-information-sharing.md
=> update hard returns and add playlist link

_posts/2016-05-13-how-18f-handles-information-security-and-third-party-applications.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-2.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-2)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/awfrancisco-patch-2/)
- Removes hero image that doesn't work well
/cc @gboone @elainekamlley
=> Removes hero

_posts/2014-03-19-hello-world-we-are-18f.md, _posts/2016-10-24-embracing-opportunities-to-improve-and-innovate.md
- Publish IG response
- Remove empty hero from old post
/cc @gboone @vzvenyach @smils @quepol
=> IG post and remove hero

_posts/2014-05-10-make-gov-apis-better-with-user-experience.md, _posts/2014-05-19-packaging-up-api-usability-testing-for-agency-re-use.md, _posts/2015-09-09-how-a-two-day-spring-moved-an-agency-twenty-years-forward.md, _posts/2016-02-09-tips-for-capturing-the-best-data-from-user-interviews.md, _posts/2016-04-04-national-earthquake-information-centers-open-source-team.md, _posts/2016-07-29-live-streamed-demos-for-exponential-transparency-and-information-sharing.md, _posts/2016-08-16-what-happens-when-the-whole-team-joins-user-interviews.md, _posts/2016-08-31-kanban-for-government.md, _posts/2016-09-27-pro-tips-for-data-friendly-regulations-proposals.md, _posts/2016-10-04-what-is-static-source-analysis.md, pages/tags/usability testing.md
Consolidates `usability testing` to `usability`
Add periods to `u.s. geological survey`
Add `tools you can use` to more posts
Change `tools we use` to `tools you can use`
=> Tag updates

_data/authors.yml, _posts/2016-10-28-california-takes-new-approach-procurement.md
=> Publishes: Recap of the California industry day session

pages/vulnerability-disclosure-policy.md
- Updates vulnerability reporting email address.
- Reversion of smart quotes [as described here](https://github.com/18F/18f.gsa.gov/pull/1996#issuecomment-257370355).
=> Update vuln reporting email

_authors/christine-cawthorne.md, _authors/gwynnekostin.md, _authors/jeffwoodworth.md, _authors/jtindel.md, _authors/kris-rowley.md, _authors/lisagelobter.md, _authors/marinafox.md, _authors/mattchessen.md, _authors/memiwhitehead.md, _authors/robin-thottungal.md, _layouts/default-profile.html
Fixes issue(s) #2021  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/guest-authors.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/guest-authors)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/guest-authors/)
- add guest authors note into relevant `.md` files
- change `default_profile.html` to add guest authors if statement
-
/cc @gemfarmer @awfrancisco @coreycaitlin
=> Guest Authors

_posts/2016-11-14-agile-procurement-state-local-government.md, _posts/2016-11-14-modular-procurement-state-local-government.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/agile-procurement.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/agile-procurement)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/agile-procurement/)
/cc @18F/blog @awfrancisco @mheadd @robincarnahan
=> Publishes: Agile procurement resources for state and local government

_authors/mike-wilkening.md, _authors/stuart-drown.md, _posts/2016-11-17-leadership-innovation-california-child-welfare-services.md, tests/schema/_authors.yml
😎 [Preview](https://federalist.18f.gov/preview/18F/18f.gsa.gov/ca-harvard/2016/11/17/leadership-innovation-california-child-welfare-services/)
/cc @18F/blog
=> Publishes: Leadership and innovation at California's Child Welfare Services

_sass/_core/typography.scss
Fixes issue(s) #1981 .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/anti-aliasing.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/anti-aliasing)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/anti-aliasing/)
- adds font smoothing 
/cc @coreycaitlin @ericronne
=> added anti-aliasing

_posts/2016-11-22-a-vulnerability-disclosure-policy-for-the-technology-transformation-service.md
- Notes explicitly that we'll be updating the scope to include all TTS-operated systems.
/cc @noahkunin @kimberbat
=> Makes explicit that we're planning to expand scope to all TTS systems

_posts/2016-11-22-a-vulnerability-disclosure-policy-for-the-technology-transformation-service.md
=> Fix broken link, no trailing slash

_posts/2016-11-25-what-18f-is-thankful-for-this-thanksgiving.md
- Makes quotes consistently set with long dashes.
- Attributes truncated quote to "Anonymous" 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/turkey-fixes.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/turkey-fixes)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/turkey-fixes/2016/11/25/what-18f-is-thankful-for-this-thanksgiving/)
/cc @smils
=> Hyphen, anonymous quote hotfix

_posts/2016-11-25-what-18f-is-thankful-for-this-thanksgiving.md
- Small style and grammar edits
/cc @gboone
=> Style edits

_posts/2016-11-14-modular-procurement-state-local-government.md
@zacharycohn is this everything? I think I got it all.
=> Update Modular procurement for state local government post

pages/vulnerability-disclosure-policy.md
- Syncs up policy with latest changes. (Clarity on reporting methods.)
/cc relevant people
=> Vulnerability disclosure policy sync

_posts/2015-03-30-new-rfp-ghostwriting-service-to-improve-contract-success.md
=> Correct tag

research/outreach-research/pps-event-findings.md
Fixes issue(s) # 2098.
- Added findings from outreach tabling event to research folder
-
-
=> adding outreach findings from tabling event

_posts/2015-03-20-one-year-in-and-looking-forward.md, pages/developer.md
Fixes issue(s) #2096 and 2097 .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/some-bug-fixes.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/some-bug-fixes)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/some-bug-fixes/)
- Updated `/developer` page. Deleted outdated information
- Fixed link in blog post
-
=> Updated developer page and fixed link in one year in review blog post

_posts/2016-12-12-connecting-culture-change-at-18F-and-PBS.md
😎 [Preview](https://federalist.18f.gov/preview/18F/18f.gsa.gov/workplace-design/2016/12/12/connecting-culture-change-at-18F-and-PBS/)
cc: @18F/blog
=> Workplace design post

_authors/dahianna.md, _posts/2016-12-15-tts-projects-forward-open-government-partnership-principles.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/open-gov/)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/open-gov/)
/cc @awfrancisco @Dahianna
=> Open Gov Partnerships post

_authors/alex-bisker.md, _authors/dahianna.md, _authors/kimberdowsett.md, _authors/mheadd.md, _authors/mike-wilkening.md, _authors/stuart-drown.md, _authors/theresa.md, _includes/header.html, _plugins/author_data.rb, _posts/2016-10-28-california-takes-new-approach-procurement.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/accessibility-fixes.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/accessibility-fixes)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/accessibility-fixes/)
- Add logo text for accessibility
- Fix Ruby bug
- Add title attribute to an iframe in a blog post
/cc @gemfarmer
=> Ruby and accessibility fixes

pages/home.html
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/homepage-update-copy.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/homepage-update-copy)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/homepage-update-copy/)
- adds the new homepage design
/cc @austinhernandez
=> New homepage layout 

Gemfile.lock
This reverts commit aaf279ec515f7d45c63645b46ee7681246dc4edc.
/cc @ericronne
=> Revert ./serve push

CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md
Fixes issue(s) #2012 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/contributing.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/contributing)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/contributing/)
- updates the [CONTRIBUTING.md](CONTRIBUTING.md) file to include more descriptive text about how to fill out a PR template
=> Template contributing text

_layouts/default-image.html, _layouts/project-tag-results.html, _sass/_components/layout.scss
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/spacing-fixes.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/spacing-fixes)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/spacing-fixes/)
/cc @gemfarmer
=> fix spacing issues on image-hero and project pages

_posts/2017-01-04-tracking-the-us-governments-progress-on-moving-https.md
- Removes duplicate hero image.
/cc @gboone
=> Remove duplicate hero image from HTTPS progress post

_posts/2015-10-09-cloud-gov-launch.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/wslack-cloud-fix.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/wslack-cloud-fix)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/wslack-cloud-fix)
=> make headlines work in cloud announcement post

_authors/rebecca-refoy-sidibe.md
Adds some missing metadata in an author's file. Should cause build to pass again.
=> Adds missing metadata

_plugins/team.rb, spec/_plugins/team_spec.rb
Issue reported by @wslack [**here**](https://gsa-tts.slack.com/archives/beta-18f-site/p1483746421000889)
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/hotfix-photos-2.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/hotfix-photos-2)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/hotfix-photos-2/)
- [path to 18f](https://federalist.18f.gov/preview/18F/18f.gsa.gov/hotfix-photos-2/2016/03/22/what-was-your-path-to-18f/)
- [why did you join 18f?](https://federalist.18f.gov/preview/2016/03/21/we-asked-100-of-our-coworkers-why-did-you-join-18f/)
- [what have you loved working on?](https://federalist.18f.gov/preview/18F/18f.gsa.gov/hotfix-photos-2/2016/03/23/what-have-you-loved-working-on/)
=> Hotfix for team_photo bug

_posts/2017-01-10-mark-hopson-negotiating-on-americas-behalf.md
Publishes, Mark's profile "Negotiating on America's Behalf"
Preview: https://federalist.18f.gov/preview/18F/18f.gsa.gov/hopson-profile/2017/01/10/mark-hopson-negotiating-on-americas-behalf/
cc/ @awfrancisco @jeanninehunter @MCHopson
=> Mark Hopson profile

_posts/2017-01-17-life-changing-magic-writing-release-notes.md
=> Publishes: The life-changing magic of release notes

_posts/2016-11-14-modular-procurement-state-local-government.md
For now, until the Federalist issue is fixed
cc @gboone @quepol
=> Removes broken link

_posts/2017-01-19-the-dark-standup.md
Publishes "The Dark Standup"
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/through-a-standup-darkly.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/through-a-standup-darkly)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/through-a-standup-darkly/)
Notes:
- @gboone will trigger a build in the morning to generate the post
/cc: @abrouilette @18F/blog
=> Through A Standup, Darkly

_hire/index.md, pages/hire.md
Fixes issue(s) #2212 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/banner-swap.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/banner-swap)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/banner-swap/)
/cc @austinhernandez
=> Remove hero image from hire page

pages/how-we-work.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/caret-fix.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/caret-fix)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/caret-fix/how-we-work/)
- Adds missing > carets to the How we work page
/cc @coreycaitlin @austinhernandez
=> Adds missing carets

blog/index.html
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/caretzz.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/caretzz)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/caretzz/blog/)
- added missing arrow carets to `/blog/` 
=> Add missing carets

_sass/_core/utility.scss
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/center-fix.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/center-fix)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/center-fix/)
/cc @gemfarmer
=> refine how allow-layout-classes works

Gemfile, Gemfile.lock, _includes/javascript.html, _layouts/default-image.html, _plugins/jekyll_asset_pipeline.rb, _sass/_components/sticky.scss, assets/js/sticky.js
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/applied-sticky.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/applied-sticky)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/applied-sticky/)
=> Apply sticky to about page

_projects/dhs-myuscis.md, _projects/eregs.md, _projects/treasury-data-act.md, tests/schema/_projects.yml
Fixes issue(s) #2200 and #2189 and #2106 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/more-project-pages.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/more-project-pages)
[:sunglasses: eRegs](https://federalist.18f.gov/preview/18F/18f.gsa.gov/more-project-pages/project/eregulations/)
[:us: myUSCIS](https://federalist.18f.gov/preview/18F/18f.gsa.gov/more-project-pages/project/dhs-myuscis/)
[:moneybag: DATA Act](https://federalist.18f.gov/preview/18F/18f.gsa.gov/more-project-pages/project/treasury-data-act/)
Still needs final review in-context from subject matter experts on each project.
/cc @kategarklavs 🎉  @awfrancisco 🌮
=> [WIP] More project-page intros

_posts/2017-02-02-cloud-gov-is-now-fedramp-authorized.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/cloudgov-question-mark.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/cloudgov-question-mark)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/cloudgov-question-mark/)
- Adds a question mark to the “What is cloud.gov” sub-header.
/cc @brittag
=> Add question mark to “what is cloud.gov” sub-header.

_posts/2017-02-02-cloud-gov-is-now-fedramp-authorized.md
Alternate URL is https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/482/2015/03/FedRAMP-Package-Request-Form_V4_06192014.pdf
However, per the slack discussion the Sites team is migrating right now so a more generic URL is best.
Reference: https://gsa-tts.slack.com/archives/fedramp/p1486148812000022
-
-
-
=> Cloud.gov Post; Fix 404 for FedRAMP Package Access Request

_projects/dhs-myuscis.md
Per this morning's conversation with Jen, I made a few updates to the USCIS summary content. Corey, please feel free to edit as you see fit(!)
Fixes issue(s) # .NA
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/kategarklavs-patch-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/kategarklavs-patch-1)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/kategarklavs-patch-1/project/dhs-myuscis/)
-Added a bullet mentioning the N-400
-Moved up the paragraph describing how our work benefitted USCIS employees
-Restructured the bulleted list a bit so that the bolded items are integrated w/the descriptions
/cc @coreycaitlin and @jehlers
=> Updates to USCIS project summary

pages/vulnerability-disclosure-policy.md
- Updates vulnerability disclosure policy with latest updates (third party service clarification, addition of cloud.gov to scope).
/cc @kimberbat @brittag
=> Sync vuln disclosure policy updates to 18f.gsa.gov

_posts/2017-02-02-cloud-gov-is-now-fedramp-authorized.md, assets/blog/cloud-gov/cloud-gov-chart.svg
- changed text from 320 to 325
- replaced corresponding image (same filename)
=> cgov number update

_projects/navy-reserve.md
Fixes issue(s) #2248.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/ready-to-serve-intro.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/ready-to-serve-intro)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/ready-to-serve-intro/project/navy-ready-2-serve/)
=> Ready to serve intro

_projects/agile-bpa.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/acolter-patch-2.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/acolter-patch-2)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/acolter-patch-2/)
- Edits from Zac and Alla
=> Updates based on edits from Zac and Alla

_projects/navy-reserve.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/acolter-patch-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/acolter-patch-1)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/acolter-patch-1/)
/cc @coreycaitlin @austinhernandez
=> Change subhead from ## to ###

_projects/calc.md, _projects/federalist.md
Fixes issue(s) #2201 and #2204 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/add-project-pages.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/add-project-pages)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/add-project-pages/)
/cc @awfrancisco @kategarklavs
=> Add project pages for CALC and Federalist

_data/navigation.yml, _join/index.md, _join/open-positions/position-title.md, pages/join.md
This PR restores the current join page design and content so we can launch other changes ASAP. It's accessible from the footer.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/join-revisions.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/join-revisions)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/join-revisions/)
/cc @gemfarmer
=> Revert join page for this release

_about/index.md, _sass/_components/icon-list.scss, _sass/_components/nav-accordion.scss, _sass/_components/sticky.scss
See issue(s) #2274 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/about-tweaks.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/about-tweaks/about/)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/about-tweaks/about/)
- add a big more spacing between nav + content
- slightly reduce padding on left side of nav items
- tighten up and refine vertical spacing in icon section
- change list styling for press images
/cc @gemfarmer @austinhernandez
=> About page style tweaks

_config-blog.yml, _includes/banner-cta.html, _projects/agile-bpa.md, _projects/c2.md, _projects/calc.md, _projects/dhs-myuscis.md, _projects/ed-college-scorecard.md, _projects/fec-gov.md, _projects/federalist.md, _projects/navy-reserve.md, _projects/treasury-data-act.md, _sass/_components/section-info.scss, examples/project-template.md, pages/press.html
Fixes issue(s) #2275 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-page-refinement.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-page-refinement)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/project-page-refinement/)
- thickened border above right rail, and made it lighter blue
- various added links and metadata tweaks
- change CTA text
/cc @gemfarmer
=> Project page refinement

_projects/navy-reserve.md
Fixes issue(s) #2283.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/acolter-patch-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/acolter-patch-1)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/acolter-patch-1/)
- Incorporated edits from Tom Black
=> Incorporated edits from Tom Black

_about/index.md, _includes/navigation/footer-desktop.html, _includes/navigation/footer-mobile.html, examples/project-template.md, pages/what-we-deliver.md
Fixes issue(s) #2276 and others
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/fix-links.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/fix-links)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/fix-links/)
- Correct the press link in the footer
- Correct project-page urls
- Add links to new project pages from What we deliver
- Update the example project template to reflect more detail
/cc @gemfarmer @elainekamlley
=> Fix project and press links, correct template file

_layouts/default-intro.html, _sass/_components/icon-list.scss
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/visual-errors.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/visual-errors)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/visual-errors/)
- Add title/banner back to simple pages (developer, code of conduct, etc.)
- Fix tiny spacing issue on About page
/cc @gemfarmer
=> Visual changes and fixes

_join/index.md
Did a little bit of voice/tone work + general cleanup here (nothing too intense). Would be happy to take another pass at this if you'd like me to make additional updates!
- General copy edits
- Made the tone a bit friendlier, the voice a bit more 18F
- Changed a few bits o' formatting
- That's about all
=> Edits to Join us materials

_projects/calc.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/add-calc-quote.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/add-calc-quote)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/add-calc-quote/what-we-deliver/calc/)
Adds quote from CALC product owner, slightly edited for length — get approval from Alan and Andre before merging!
_will get @awfrancisco's eyes after merge_
=> Add edited calc quote

pages/april-fools/index.md
Fixes issue(s) #2316.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/april-fools-page.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/april-fools-page)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/april-fools-page/)
-fix typo
-standardize on phrase "April Fools Day"
=> April Fools Day page fixes

_posts/2016-05-13-how-18f-handles-information-security-and-third-party-applications.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/editors-note)
[PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/editors-note/)
- Add editor's note with link and quote from 2/21/2017 IG report
- Updates time and date of last time the post was updated
/cc @vzvenyach
=> Adds new Editors' note

_data/navigation.yml, _join/index.md, _join/open-positions/position-title.md
Fixes issue(s) #1908 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/joining-again.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/joining-again)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/joining-again/join/)
Here is the pertinent file: https://github.com/18F/18f.gsa.gov/blob/joining-again/_join/index.md
/cc @kategarklavs
=> [WIP] Restoring Join content work

_posts/2016-12-14-how-to-run-an-efficient-meeting.md
Fixes issue(s) #2130 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/meetings-note)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/meetings-note/2016/12/14/how-to-run-an-efficient-meeting/)
/cc @wslack @awfrancisco
=> add note about asking an observer to attend

PULL_REQUEST_TEMPLATE.md, README.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/docker-docs.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/docker-docs)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/docker-docs/)
- Updates the README to help clarify some of the pain points in the docker setup.
- updates template to include link to README
=> supportive docker documentation

_posts/2015-12-17-the-agile-bpa-is-ready-to-launch.md
- Fixes incorrect inquiries email
/cc @gboone
=> Correct inquiries email

_includes/card.html, assets/js/index.js
Fixes issue(s) #2362 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/card-link.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/card-link)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/card-link/what-we-deliver)
- adds click handler to `.card-link` that allows navigating to other windows.
=> Card click handler

_posts/2015-12-07-what-exactly-do-we-even-do-all-day.md
=> Heading format fix

_posts/2017-03-21-nasa-journey-with-us-web-design-standards.md, tests/schema/tags.yml
cc @18F/blog @juliaelman 
[Preview](https://federalist.18f.gov/preview/18F/18f.gsa.gov/nasa-wds/)
=> Publishes: NASA’s journey with the U.S. Web Design Standards

pages/vulnerability-disclosure-policy.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/ah-login-vuln-update.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/ah-login-vuln-update)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/ah-login-vuln-update/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/ah-login-vuln-update/README.md)
- Sync with latest vulnerability disclosure policy (login.gov updates)
/cc @konklone
=> Sync vulnerability policy / add login.gov

_styleguide/subpages/typography.md
- Adds commas to separate rem & px in type instructions
- Removes stray parenthesis
/cc @gemfarmer
=> Making format consistent

_includes/breadcrumb.html, _includes/button-listing.html, _includes/open-positions.html, _join/apply/product-manager.md, _join/job-listings/product-manager.md, _join/open-positions/position-title.md, _join/open-positions/product-manager.md, _join/product-manager/official-posting.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/join-listings.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/join-listings)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/join-listings/join/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/join-listings/README.md)
- First of many new job listings added to page!
- [Product manager performance profile](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/join-listings/join/product-manager/)
- [Product manager job listing](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/join-listings/join/product-manager/job-listings/)
- [Product manager application page](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/joi …
=> Product manager job listing

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/join-fixer)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/join-fixer/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/join-fixer/README.md)
- Adjusts the eligibility text for all 18F jobs.
/cc @gemfarmer @elainekamlley @hestherchang
=> Adjusts eligibility text

_posts/2015-07-17-the-new-10.md, tests/schema/tags.yml
So we can display this blog post on the project page
@gboone
=> Add new ten tag

_join/index.md
made updates to various sections to reflect current processes
Fixes issue(s) # ..n/a. the information was outdated and I updated it
-
-
-
=> Update various sections

_posts/2016-01-07-announcing-the-18f-micro-purchase-platform.md
=> Removes hero, fixes header formatting

pages/foia-reading-room.md
None to publish just yet but this will be the place for them when we have them.
=> Creates a shell for future FOIA requests.

_posts/2016-03-18-how-user-archetypes-informed-the-draft-us-web-design-standards.md
Fixes images in a broken blog post.
[Preview](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/img-fix/2016/03/18/how-user-archetypes-informed-the-draft-us-web-design-standards/)
/cc @gemfarmer
=> fix images in WDS user archetype post

_includes/button-listing.html, _includes/open-positions.html, _join/apply/product-manager.md, _join/job-listings/gs-14.md, _join/job-listings/gs-15.md, _join/open-positions/backend-software-engineer.md
cc: @hestherchang Whenever we're ready to publish you can push the big green button.
=> Engineering job post

_projects/agile-bpa.md
- Changes project URL to new ads.18f.gov URL
/cc @gboone
=> Update project URL

_join/eng-interviews.md, _join/index.md
This is still a rough draft -- I haven't previewed -- but I wanted to validate the approach before I proceed.
@hestherchang @gboone is this an OK approach for adding this content? I added a link on the main join page, and a separate doc for the eng-specific stuff.
=> Adds details about the engineering round of interviews.

_join/open-positions/backend-software-engineer.md
It's closed! cc @hestherchang @jacobian
=> Remove engineering position

_posts/2017-04-27-remembering-larry-matthias-early-partner-excellent-civil-servant.md
=> Puts the correct Nick on the byline

_posts/2015-05-12-announcing-the-calc-tool.md
=> Correct link for Discovery

_join/job-listings/acq-gs-13.md, _join/job-listings/acq-gs-14.md, _join/job-listings/acq-gs-15.md, _join/open-positions/acquisition-technical-lead.md, _projects/cloud-gov.md, _projects/dod-military-onesource.md, _projects/dol-wage-and-hour.md, _projects/micro-purchase-marketplace.md, _projects/treasury-new-ten.md, _projects/us-web-design-standards.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/layout-fix.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/layout-fix)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/layout-fix/)
Fixes layouts for some project pages and job descriptions
=> updated layout calls

_join/open-positions/acquisition-technical-lead.md
=> Remove italics from link

_join/open-positions/acquisition-technical-lead.md
This adds the YAML to create a description metatag for the tech lead job posting (I hope).
=> add description tag for acq tech lead posting

Gemfile, Gemfile.lock, _join/eng-interviews.md, _join/job-listings/engr-gs-14.md, _join/job-listings/engr-gs-15.md, _join/open-positions/backend-software-engineer.md, _join/open-positions/product-manager.md
Fixes issue(s) #2377
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/gem-up.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/gem-up)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/gem-up/)
- updated html proofer
- corrected the layout call for some join pages
/cc @gemfarmer
=> Gem update and correct layouts

_join/job-listings/acq-gs-13.md
cc @elainekamlley @hestherchang
=> Clarify how to submit application

_join/job-listings/acq-gs-14.md
=> Clarify how to submit - 14

_join/job-listings/acq-gs-15.md
=> Clarify how to submit - 15

_projects/treasury-new-ten.md
Fixes issue(s) #2203 .
Thanks for the typo catch @coreycaitlin!
=> Fixing typo

_join/open-positions/acquisition-technical-lead.md
Position is closed, so let's stop advertising it.
cc: @hestherchang @awfrancisco
=> Take down job listing

_posts/2017-06-01-federalist-is-out-of-beta-and-open-for-business.md
edit per https://github.com/18F/18f.gsa.gov/issues/2444
Fixes issue(s) #2444 .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/wslack-edit-federalist.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/wslack-edit-federalist)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/wslack-edit-federalist/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/wslack-edit-federalist/README.md)
- edit Federalist blog post language
Checklist:
/cc @gboone
=> clarify that Federalist is built on cloud.gov

_posts/2017-06-06-fractal-and-federalist-join-the-us-web-design-standards.md
To match length of other blog posts
Checklist:
/cc @gboone
=> Add more info to description

_authors/aaronburk.md, _posts/2017-06-22-why-discovery-research-matters-for-modular-procurement.md, tests/schema/tags.yml
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/mod-procurement.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/mod-procurement)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/mod-procurement/)
- Publishes Forest Service blog post
- Add Aaron Burk to authors
- Add `Forest Service` tag
/cc @awfrancisco @rrefoy
=> Publishes Forest Service: why discovery research matters for modular procurement

_posts/2017-06-22-why-discovery-research-matters-for-modular-procurement.md
Fixes issue(s) # NO ISSUE.
- There was a previous post that had Aaron Burk as an author and the slug used there was "aaron-burk". I changed the tag here to align the two posts in a single index.
Checklist:
=> Changed the author slug for Aaron Burk

_posts/2017-06-22-why-discovery-research-matters-for-modular-procurement.md
=> Adds "permitting"

_posts/2017-06-22-why-discovery-research-matters-for-modular-procurement.md
Adds description of guest author
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-1)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/awfrancisco-patch-1E/README.md)
=> Add description of authors

_authors/aaronburk.md, _includes/header.html, _includes/navigation/footer-desktop.html
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/logo-change.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/logo-change)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/logo-change/)
- Change 18F logo in the header and footer
=> Change back to original 18F logo

tests/schema/tags.yml
Adding to group our DOJ projects together under one tag.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/doj-tag.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/doj-tag)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/doj-tag/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/doj-tag/README.md)
- Adds `department of justice` tag
=> Add DOJ tag

_includes/gform-button-listing.html, _includes/open-positions.html, _join/index.md, _join/open-positions/onrr-front-end-engineer.md
Fixes issue(s) #2463  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/doi-job.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/doi-job)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/doi-job/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/doi-job/README.md)
- Adds information about DOI's Office of Natural Resources Revenue to join page
- Adds information about ONRR Front End Engineer position and how to apply
- Created google form button 
- updated `open-positions.html` to hide 18F specific text 
/cc @rooneywp @gboone
=> Publishes ONRR job listing

_join/index.md, _join/open-positions/front-end-design-intern.md, _join/open-positions/onrr-front-end-engineer.md, _join/open-positions/service-visual-design-intern.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/internships.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/internships/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/BRANCH_NAME/internships.md)
- Posts two internship positions: Front end and service/visual design
- Updated join home page content 
- Copy edits to DOI job posting
/cc @awfrancisco @esgoodman
=> Posting 18F internship opportunities

pages/thank-you.md
Fixes issue(s) #2478  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/thank-you.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/thank-you)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/thank-you/)
- Adds thank you page for new newsletter subscribers after confirming their email address
=> Creates thank you page for newsletter subscribers

_join/open-positions/front-end-design-intern.md, _join/open-positions/onrr-front-end-engineer.md, _join/open-positions/product-manager.md, _join/open-positions/service-visual-design-intern.md, _join/open-positions/talent-acquisition-specialist.md, _join/open-positions/talent-engagement-lead.md, _join/open-positions/talent-engagement-specialist.md, _posts/2016-07-19-strategies-for-starting-your-own-writing-lab.md
**TO BE MERGED MON 731** 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-postings.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-postings)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/job-postings/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/job-postings/README.md)
- Posting three talent positions 
- Posting product manager position
- Edit other open positions
/cc @rooneywp @awfrancisco
=> Posting open talent and product manager positions

_join/open-positions/talent-acquisition-specialist.md, _join/open-positions/talent-engagement-lead.md, _join/open-positions/talent-engagement-specialist.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/talent-aq.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/talent-aq/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/talent-aq/README.md)
- Posting Talent Acquisition Specialist position
- Changing closing time for three positions 
/cc @awfrancisco @rooneywp
=> Posting talent acquisition position and change closing time

_includes/navigation/footer-desktop.html, _includes/navigation/footer-mobile.html, pages/code-of-conduct.md
Take it down while we work out some issues with the existing code of conduct.
=> Unpublish code of conduct (for now)

_join/open-positions/talent-acquisition-specialist.md, _join/open-positions/talent-engagement-lead.md, _join/open-positions/talent-engagement-specialist.md
- Update closing time in `How to apply` section
- Added consistent job announcement number
=> Corrections to job postings

_join/open-positions/product-manager.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/pm-position.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/pm-position/)
- This publishes Product Manager position
**Will need to take down on 8/11 @ 11PM ET**
=> Posting Product Manager position

_join/open-positions/product-manager.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/elainekamlley-patch-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/elainekamlley-patch-1)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/elainekamlley-patch-1/)
- Removed Phoenix AZ as a possible work location
/cc @awfrancisco @hestherchang
=> Take out a location from PM role

_layouts/project-page.html
Fixes issue(s) #2491 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/sidebar-bug.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/sidebar-bug)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/sidebar-bug/what-we-deliver/us-web-design-standards)
- Changes conditional logic that was checking for incorrect attribute names
=> Fix sidebar bug

_join/open-positions/product-manager.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/pm-edit.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/pm-edit/)
- Talent was getting a few emails from applicants unsure of the difference of Innovation specialist and PM role. Note above indicates both.
=> Added note indicating innovation specialist as official title

_join/open-positions/onrr-front-end-engineer.md
**Issue:** The locations from this position were missing from the posting.
- Added the locations of the role to the posting
=> Add locations to job posting

_join/open-positions/product-manager.md, _join/position-no-longer-available.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/pm-takedown.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/pm-takedown)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/pm-takedown/)
- PM role is now closed. Taking down job posting
=> Removing PM position

_join/open-positions/consulting-software-engineer-gs13.md, _join/open-positions/consulting-software-engineer-gs14.md, _join/open-positions/consulting-software-engineer-gs15.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/consult-eng.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/consult-eng)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/consult-eng/join/)
- Posting GS-13, GS-14, and GS-15 Consulting Software Engineering positions
/cc @awfrancisco @hestherchang
=> Posting Consulting Software Engineer

_join/open-positions/consulting-software-engineer-gs13.md, _join/open-positions/consulting-software-engineer-gs14.md, _join/open-positions/consulting-software-engineer-gs15.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/jpost-edits.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/jpost-edits)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/jpost-edits/)
- small copy edits
=> Copy edits to job postings

_projects/login-gov.md
Bunch o' text edits
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/smils-patch-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/smils-patch-1)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/smils-patch-1/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/smils-patch-1/README.md)
-
-
-
Checklist:
=> Bunch o' text edits

_projects/login-gov.md, tests/schema/tags.yml
Fixes issue(s) ##2394 .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/login-project.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/login-project)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/login-project/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/login-project/README.md)
- Publishes login.gov project page
- Adding `login.gov` tag
/cc @jeanninehunter @awfrancisco
=> HOLD UNTIL LAUNCH: Publishes Login.gov project page

_posts/2017-08-23-government-launches-login-gov.md
/cc @elainekamlley hold on merging until I get a 👍 from all the people
=> Update launch date

_posts/2015-03-18-sunshine-week-extractive-industries-transparency-initiative-event.md
=> Minor typo fix, remove excess "."

_join/open-positions/content-designer-gs14.md, _join/open-positions/content-designer-gs15.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/jobs-switch.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/jobs-switch)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/jobs-switch/join/)
- Posting GS-14 and GS-15 Content Designer positions
/cc @awfrancisco @nicoleslaw @hestherchang
=> Posts content designer positions

_join/open-positions/content-designer-gs14.md, _join/open-positions/content-designer-gs15.md
cc @awfrancisco Missed it before you merged. I think the GS-14 one also has an error under Qualifications. It says GS-13 there?
=> Minor copyedits / typo fixes

_join/index.md
- Change link from 2016 to 2017
=> Update pay calculator link to 2017

_authors/laura-gerhardt.md, _posts/2017-08-30-what-makes-a-great-vendor-team.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/acq-team.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/acq-team)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/acq-team//2017/08/30/what-makes-a-great-vendor-team/)
- Publishes blog post
/cc @awfrancisco @lauraGgit
=> Publishes: What makes a great vendor team blog post

_posts/2017-09-05-ficam-partners-with-federalist.md
=> Add link to original post

_posts/2017-09-07-forrest-service-six-month-check.md, _posts/2017-09-08-forrest-service-six-month-check.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/fs-check.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/fs-check)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/fs-check/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/BRANCH_NAME/fs-check.md)
- Added content for Forrest Services six month assumption check update
/cc @rrefoy @awfrancisco
=> Publishes Forrest Services post

_posts/2017-09-08-forest-service-six-month-check.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/elainekamlley-patch-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/elainekamlley-patch-1)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/elainekamlley-patch-1/)
- Fix URL 
- Redirect added 
=> typo fix in URL

_join/index.md, _join/open-positions/acquisition-technical-lead-gs14.md, _join/open-positions/acquisition-technical-lead-gs15.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/acq-tech-lead.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/acq-tech-lead)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/acq-tech-lead/join/)
- Adding open acq tech lead positions
- Fixed line breaks in gov resume sample
/cc @awfrancisco @hestherchang
=> Publishing Acquisition Technical Lead positions

_join/open-positions/acquisition-technical-lead-gs14.md, _join/open-positions/acquisition-technical-lead-gs15.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-fix.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-fix)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/job-fix/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/job-fix/README.md)
- Change Office of 18F to Office of Acquisition
- Change Technology Transformation Service to Services
/cc @hestherchang @elainekamlley
=> Update position location

_authors/jon-geselle.md, _authors/randy-hart.md, _posts/2017-09-12-how-alaska-is-using-transparency.md
Publishes Alaska transparency post. 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/alaska-transparency.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/alaska-transparency)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/alaska-transparency/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/alaska-transparency/README.md)
- publish post
- add jon geselle as author
/cc @randyhart
=> Alaska transparency post

_join/index.md
Fixes issue from #2543 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-2.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-2)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/awfrancisco-patch-2/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/awfrancisco-patch-2/README.md)
/cc @gboone
=> Remove double quote

_join/open-positions/onrr-front-end-engineer.md, _join/position-no-longer-available.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/doi-job-down.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/doi-job-down)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/doi-job-down/)
- Removes DOI ONRR Front end position 
/cc @gboone
=> Takes down DOI front end position

_posts/2017-09-18-a-day-in-the-life-of-an-18f-product-owner.md
should be "Rebecca works" not "Rebecca work"
-
-
-
Checklist:
=> Fix subject-verb agreement

_authors/adam-kendall.md, _posts/2017-09-26-automated-scanning-for-sensitive-information.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/git-seekret.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/git-seekret)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/git-seekret/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/git-seekret/README.md)
- Publishes git seekret blog post
=> Publishes Automated scanning for sensitive info in the dev cycle

_join/open-positions/acquisition-design-lead.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/acq-design.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/acq-design)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/acq-design/join)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/acq-design/README.md)
- Publishes Acq design positon
Checklist:
/cc @awfrancisco @hestherchang @wongperson
=> Publishes Acq Design Lead position

_posts/2017-10-03-building-a-large-scale-design-system.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/wds-fix.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/wds-fix)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/wds-fix/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/wds-fix/README.md)
- Remove duplicate image
=> Removing a duplicate image from WDS post

pages/contact.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/dev-edit.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/dev-edit)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/dev-edit/)
- updated link
=> Updating partnership principles link

_join/open-positions/acquisition-design-lead.md
=> Removed resume video link

_authors/aaron-sauers.md, _posts/2017-10-04-18f-and-federal-laboratories-work-together-to-bring-better-data-to-businesses.md, _posts/2017-10-05-18f-and-federal-laboratories-work-together-to-bring-better-data-to-businesses.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/flc-biz.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/flc-biz)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/flc-biz/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/flc-biz/README.md)
- Publishes FLC blog post
- Adds Aaron Sauers to authors list
=> Publishes "18F and federal laboratories work together to bring better data to businesses"

_principles/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-3.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-3)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/awfrancisco-patch-3/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/awfrancisco-patch-3/README.md)
- Fix list formatting
Checklist:
/cc @gboone
=> Formatting fix

_join/open-positions/acquisition-design-lead.md, _join/position-no-longer-available.md
To be merged 10/13
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/remove-job.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/remove-job)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/remove-job/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/remove-job/README.md)
- removes the Acq Design Lead position 
=> DO NOT MERGE TILL 10/13 - removes acq design lead positon

_includes/navigation/footer-desktop.html, _includes/navigation/footer-mobile.html, pages/code-of-conduct.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/coc-update.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/coc-update)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/coc-update/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/coc-update/README.md)
- Replaces the Code of Conduct with a statement and links
- Change Code of Conduct page to published
- Adds CoC link to footer
/cc @annalee @gboone
=> Add CoC statement, footer link

_join/open-positions/opp-feedback-analytics-engineer.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/analytics-engineer.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/analytics-engineer)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/analytics-engineer/join/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/analytics-engineer/README.md)
- Posting new job description
/cc @hestherchang @gboone
=> Posting feedback analytics engineer position

_about/index.md, _join/index.md, _join/open-positions/opp-feedback-analytics-engineer.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/mission.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/mission)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/mission/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/mission/README.md)
- Added mission and vision to `About 18F`
- Added disclaimer to 18F `/join`
/cc @gboone
=> Added 18F mission statement and disclaimer on open positions

_join/index.md
- Added acronyms to office and agency 
/cc @gboone
=> Add Acronyms to join page

_join/open-positions/opp-feedback-analytics-engineer.md
Plus additional wording and punctuation tweaks.
-
-
-
Checklist:
=> Update to clarify this is not an 18F position

_join/open-positions/opp-feedback-analytics-engineer.md
=> Typo fixes to job description

_posts/2017-10-11-pulling-back-the-curtain-on-it-procurement.md
Removed mentions of illusion from blog post
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/elainekamlley-patch-2svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/elainekamlley-patch-2)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/elainekamlley-patch-2/]
- Removed mentions of illusion from blog post
/cc @gboone
=> Slight changes to the language

_posts/2016-06-20-build-empathy-with-stakeholder-interviews-part-1-preparation.md
=> Fix broken link

_projects/agile-bpa.md, _projects/c2.md, _projects/calc.md, _projects/cloud-gov.md, _projects/dhs-myuscis.md, _projects/dod-military-onesource.md, _projects/doi-every-kid-in-a-park.md, _projects/dol-wage-and-hour.md, _projects/ed-college-scorecard.md, _projects/eregs.md, _projects/fec-gov.md, _projects/federalist.md, _projects/hhs-states.md, _projects/navy-reserve.md, _projects/treasury-data-act.md, _projects/treasury-new-ten.md, _projects/us-web-design-standards.md
Addresses part of issue #2466.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-summaries.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-summaries)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/project-summaries/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/project-summaries/README.md)
- Updates the summaries of most project pages. Summaries appear on the home page and what we deliver
/cc 
@elainekamlley for other tasks in this issue and review management
@smils for content review. You can preview the changes [here](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/project-summaries/what-we-deliver/)
=> Update project summaries

_join/open-positions/pif-director-of-communications-and-marketing-gs15.md
- PIF comms is only GS-15 step 1, edit to reflect that
=> Take out salary range

_join/open-positions/pif-director-of-communications-and-marketing-gs15.md
- GSA needs to make changes. Taking down post
/cc @awfrancisco @amandaschonfeld
=> Taking down post as per GSA HR request

_join/position-no-longer-available.md
=> Added redirect to PIF comms director

_join/open-positions/pif-director-of-communications-and-marketing-gs15.md, _join/position-no-longer-available.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/pif-comms.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/pif-comms)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/pif-comms/join/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/pif-comms/README.md)
- PIF comms director updated content as per GSA HR request
=> Publishing updated PIF comms director position description

_join/open-positions/pif-director-of-communications-and-marketing-gs15.md
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/elainekamlley-patch-2/join/)
- The title is Director of Communications
=> Remove deputy from title

_join/index.md, _join/open-positions/acquisition-product-manager-gs15.md, _join/open-positions/strategist-gs15.md
Fixes issue(s) # [joining-tts](https://github.com/18F/joining-18f/issues/355)
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/email-update.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/email-update)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/email-update/)
- Changed email to jointts@gsa.gov
/cc @awfrancisco @JennMoran
=> updated email to jointts@gsa.gov

_config-accesslint.yml, _config-blog.yml, _posts/2017-12-14-getting-stakeholder-buy-in-for-agile-development.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/stakeholder-agile.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/stakeholder-agile)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/stakeholder-agile/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/stakeholder-agile/README.md)
cc @gboone
=> Publishes stakeholder buy in for agile post

_join/open-positions/strategist-gs15.md, _join/position-no-longer-available.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/remove-strategist.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/remove-strategist)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/remove-strategist/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/remove-strategist/README.md)
- Removes 18F Strategist position
/cc @gboone
=> Remove strategist position

_join/open-positions/acquisition-product-manager-gs15.md, _join/position-no-longer-available.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/remove-j.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/remove-j)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/remove-j/)
- Removed acq product position 
=> Remove product position

_plugins/team.rb
Speed up build by not including team images on local dev, which significantly slows down the build.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/ms-speed_up_build.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/ms-speed_up_build)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/ms-speed_up_build/)
=> Try and speeding up local dev build

_join/index.md
updated salary cap to reflect 2018 salary
-
-
-
Checklist:
=> update to government pay grades section

pages/contact.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/subject-line.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/subject-line)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/subject-line/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/subject-line/README.md)
- Changes subject line from "18F Website Inquiry" to "Partnering with 18F"
=> Change subject line in mailto link

_projects/agile-bpa.md, _projects/fbi-crime-data-explorer.md
Fixes issue #2524  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/fbi-cde.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/fbi-cde)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/fbi-cde/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/fbi-cde/README.md)
- Add Crime Data Explorer project page
- Fixes typo on Agile BPA description
Note: FBI project page still needs an image before publishing
=> Adds FBI Crime Data Explorer project page

_principles/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/path-analysis.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/path-analysis)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/path-analysis/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/path-analysis/README.md)
- Change Foundation Engagement to Path Analysis on the principles page (This is the only instance that needs to be update on the site)
=> FE to Path Analysis

_projects/fbi-crime-data-explorer.md, _projects/nsf-seedfund.md, tests/schema/tags.yml
Fixes issue(s) #2525  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/nsf-seedfund.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/nsf-seedfund)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/nsf-seedfund/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/nsf-seedfund/README.md)
- Adds NSF project page
- Fixes heading on FBI project page
NSF project page still needs image
=> Adds NSF Seed Fund project page

_projects/forest-service.md
Fixes issue(s) #2440  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/forest-service-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/forest-service-1)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/forest-service-1/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/forest-service-1/README.md)
- Adds Forest Service project page
Needs image before publishing
=> Forest Service project page

_about/index.md, _includes/side-cta.html, _layouts/project-page.html, _principles/index.md, _sass/_components/post-feature.scss, _sass/_core/utility.scss, _sass/_core/variables.scss, pages/how-we-work.md
Fixes issue(s) #2622  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/contact-move.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/contact-move)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/contact-move/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/contact-move/README.md)
- added contact to side bar in project pages
- added contact options to side nav in `about` and `partnership principles`
- added border between related blogs and footer in project pages
=> Made contact options more prominent in project pages, about, and partnership princ

_posts/2016-02-12-happy-valentines-day-from-18F.md, tests/schema/tags.yml
Fixes issue(s) #2644.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/valentines-system.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/valentines-system)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/valentines-system/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/valentines-system/README.md)
- Fixes last blog post with standards tag
- Removes standards tag
=> Change standards tag

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-post.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-post)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/job-post/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/job-post/README.md)
- Link to TTS page for 18F product position
=> Posting link to product manager position

_posts/2018-02-22-new-home-for-the-federal-plain-language-community.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/change-date.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/change-date)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/change-date/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/change-date/README.md)
@elainekamlley
=> Change date

_posts/2014-05-14-hacking-bureaucracy-improving-hiring-and-software.md, _posts/2014-09-15-say-hello-to-the-new-presidential-innovation-fellows.md, _posts/2015-01-21-join-us.md, _posts/2015-02-25-We-Are-Hiring.md, _posts/2016-02-10-bringing-iterative-development-to-our-talent-team.md, _posts/2016-02-24-two-new-open-positions-to-guide-our-business-and-our-people.md, _posts/2016-07-13-technology-transformation-services-looking-for-new-commissioner.md, _posts/2016-12-02-presidential-innovation-fellows-now-accepting-applications-spring-2017.md
Fixes issue(s) #2677 .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/join-us-tag.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/join-us-tag)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/join-us-tag/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/join-us-tag/README.md)
- Changes hiring to join us 
=> Change hiring tag to join us

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/remove-button.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/remove-button)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/remove-button/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/remove-button/README.md)
- Removes PM position link
=> Removes button to PM job opening

_posts/2018-02-22-ask-18f-data-collection.md, tests/schema/tags.yml
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/advice-data.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/advice-data)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/advice-data/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/advice-data/README.md)
- Converted content to markdown
/cc @awfrancisco @LindsayYoung @anthonygarvan
=> Publishes Advice Column 

_posts/2018-02-28-ask-18f-data-collection.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/a-fix.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/a-fix)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/a-fix/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/a-fix/README.md)
- typo fix
- date on markdown file updated
=> Typo fix and date update on blog post

_layouts/hww-primary.html, _sass/_components/blockquotes.scss, _sass/_components/layout.scss, pages/how-we-work.md, spec/_plugins/utlity_spec.rb
Fixes issue(s) #2661 .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/hww-update.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/hww-update)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/hww-update/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/hww-update/README.md)
- Adds Path Analysis and Experiment and iterate language
- Adds project cards to the bottom of content
- Created a new how we work layout
=> Update language and layout of How we work page

_products_projects/agile-bpa.md, _products_projects/cloud-gov.md, _products_projects/eregs.md, _products_projects/federalist.md, _products_projects/login-gov.md, _services_projects/c2.md, _services_projects/calc.md, _services_projects/dhs-myuscis.md, _services_projects/dol-wage-and-hour.md, _services_projects/ed-college-scorecard.md, _services_projects/fbi-crime-data-explorer.md, _services_projects/fec-gov.md, _services_projects/forest-service.md, _services_projects/hhs-states.md, _services_projects/nsf-seedfund.md, _services_projects/treasury-data-act.md, _services_projects/us-web-design-standards.md
Fixes issue(s) #2673 .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-cards.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-cards)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/project-cards/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/project-cards/README.md)
- Change the titles on project cards to descriptions from project names
- Change background headers on project cards to not repeat new descriptions
- Add product names to agency section of front matter
- Shorten description of FBI CDE project
- Change project URLs to full URLs rather than names
=> Update project titles and backgrounds

Gemfile.lock, _posts/2018-03-13-win-big-by-going-small.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/win-big.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/win-big)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/win-big/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/win-big/README.md)
- Markdown conversion of blog post
/cc @awfrancisco @mheadd
=> Publishes Win big by going small blog post

_posts/2016-03-15-treasury-and-the-data-act-full-of-sunshine.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/header-fix.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/header-fix)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/header-fix/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/header-fix/README.md)
- Fixes format on headers
=> Header format fix

pages/vulnerability-disclosure-policy.md
Syncs VDP, adds api.data.gov to scope.
/cc @GUI @gbinal
=> Update VDP with api.data.gov

_authors/amin-mehr.md, _authors/lauren-anderson.md, _posts/2018-03-27-four-benefits-to-using-the-full-TTS-tech-stack.md, tests/schema/tags.yml
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/four-benefits.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/four-benefits)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/four-benefits/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/four-benefits/README.md)
- Converted text for blog post 
- gsa tag
- new guest authors
=> Publishes four benefits to using TTS tech stack blog post

_products_projects/cloud-gov.md, _products_projects/eregs.md, _products_projects/federalist.md, _products_projects/login-gov.md, _services_projects/c2.md, _services_projects/calc.md, _services_projects/dol-wage-and-hour.md, _services_projects/ed-college-scorecard.md, _services_projects/fbi-crime-data-explorer.md, _services_projects/fec-gov.md, _services_projects/forest-service.md, _services_projects/nsf-seedfund.md, _services_projects/treasury-data-act.md, _services_projects/us-web-design-standards.md
Fixes issue(s) #2607 and #2699 .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-repos.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-repos)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/project-repos/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/project-repos/README.md)
- Adds descriptive names to repo links
- Adds new repo links
- Adds new resources
=> Update project page sidebars

pages/contact.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/newsletter-c.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/newsletter-c)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/newsletter-c/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/newsletter-c/README.md)
- Adds google form to collect newsletter subscriptions 
=> Adding google form to subscribe to newsletter

_products_projects/cloud-gov.md, _sass/_components/blockquotes.scss, _services_projects/calc.md, _services_projects/dhs-myuscis.md, _services_projects/ed-college-scorecard.md, _services_projects/fec-gov.md, _services_projects/hhs-states.md, _services_projects/treasury-data-act.md, pages/how-we-work.md
Fixes issue(s) #2704  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-test.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-test)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/project-test/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/project-test/README.md)
- Added testimonials to Data Act, FEC, CALC, HHS, collect scorecard, MyUSCIS, and cloud
- Added styling for fun fact block quotes
=> Testimonials to project pages

_authors/hannah-kane
=> adds hannah-kane as author

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/remove-acq-job.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/remove-acq-job)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/remove-acq-job/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/remove-acq-job/README.md)
- remove acq job link
=> Remove Acq User Design job post

_sass/_components/blockquotes.scss, _sass/_core/utility.scss, pages/home.html
Fixes issue(s) #2704 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/home-testimonial.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/home-testimonial)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/home-testimonial/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/home-testimonial/README.md)
- Adds additional section and styling to the home page for testimonials
/cc @awfrancisco 
Big thanks to @ericronne and the [design lab](https://github.com/18F/design-lab/issues/5)! @ericronne please let me know if you have any comments or suggestions.
=> Adds home page testimonial

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/vis-job.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/vis-job)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/vis-job/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/vis-job/README.md)
- Removes close positions
- Adds visual design role
/cc @awfrancisco @Dahianna
=> Remove 3 jobs and add vis design position

_code_of_conduct/index.md, _config.yml, pages/code-of-conduct.md
Replaced text with approved revised CoC
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/jeanninehunter-patch-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/jeanninehunter-patch-1)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/jeanninehunter-patch-1/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/jeanninehunter-patch-1/README.md)
=> Replaced text with approved revised CoC

pages/contact.md
- Change Dan to Kwab in contact us sidebar
=> Change Dan to Kwab on contact

pages/how-we-work.md
Fixes issue(s) #2735 .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/hww-v3.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/hww-v3)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/hww-v3/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/hww-v3/README.md)
- Move testimonial to top
- Update all text
@elainekamlley over to you to see if we can move the contact us blurb to a box or the sidebar
=>  How we work content

pages/developer.md
=> Updating a broken URL

_join/index.md
- Add PIF job
/cc @Dahianna @eddietejeda
=> Add link to PIF job

_posts/2018-05-21-using-agile-methods-to-improve-the-rfp-process.md, _posts/2018-05-22-using-agile-methods-to-improve-the-rfp-process.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/agile-rfp.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/agile-rfp)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/agile-rfp/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/agile-rfp/README.md)
/cc @Dahianna
=> Agile RFP blog post

_posts/2018-05-24-what-agencies-have-to-say-about-working-in-the-open.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/agency-open.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/agency-open)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/agency-open/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/agency-open/README.md)
- Published post on agencies working in the open
/cc @Dahianna
=> Working in the open post

_join/index.md
- Add content designer link
/cc @Dahianna
=> Add content designer opening

_join/index.md
- Remove 2 job links
/cc @Dahianna
=> Remove closed jobs

_posts/2018-05-24-what-agencies-have-to-say-about-working-in-the-open.md
=> Content edit

_join/index.md
- Remove content designer job link
@Dahianna
=> Remove content designer position

_authors/jeannine-hunter.md, _posts/2018-06-06-pif-extend-deadline-fall-2018.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/pif-2018.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/pif-2018)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/pif-2018/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/pif-2018/README.md)
- Adds Jeannine as author
- Published pif 2018 blog post
/cc @Dahianna
=> PIF 2018 cohort blog post

_posts/2018-06-06-pif-extend-deadline-fall-2018.md
=> Fixes to PIF post

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/pm-job.svg?style=svg)(https://circleci.com/gh/18F/18f.gsa.gov/tree/pm-job)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/pm-job/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/pm-job/README.md)
/cc @dahianna
=> Remove PM job

_authors/kara-reinsel.md, _posts/2018-06-14-ask-18f-how-to-shift-the-cultural-mindset-of-my-organization.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/ask-post-3.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/ask-post-3)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/ask-post-3/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/ask-post-3/README.md)
/cc @Dahianna
=> Ask 18F blog post #3

pages/how-we-work.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/pa-update.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/pa-update)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/pa-update/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/pa-update/README.md)
- Update typical cost of a Path Analysis
/cc @Dahianna
=> Update price of path analysis

_posts/2016-08-29-data-act-prototype-simplicty-is-key.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/data-act-fixup.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/data-act-fixup)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/data-act-fixup/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/data-act-fixup/README.md)
- Fix table header in DATA Act article
=> Fix table header in DATA Act article

assets/js/jekyll-pages-api-search.js
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/hide_loading_bar.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/hide_loading_bar)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/hide_loading_bar/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/hide_loading_bar/README.md)
-hide loading bar
Checklist:
=> Merge dev to master

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/closejobs.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/closejobs)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/closejobs/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/closejobs/README.md)
- Removes Viz Design & Strategist apply links
Checklist:
=> [MERGE AFTER 8:00pm EST 6/29] Removes Viz & Strat Jobs

_join/index.md
Fixes issue(s) #  N/A
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/postengrole.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/postengrole)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/postengrole/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/postengrole/README.md)
- Add open consulting software engineer
=> [MERGE ON 7/2] Add eng open position

_authors/gil-alterovitz.md, _authors/justin-koufopoulos.md, _posts/2018-07-03-presidential-innovation-fellows-bringing-new-approaches-to-nations-biggest-challenges.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/pif-day.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/pif-day)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/pif-day/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/pif-day/README.md)
- Publish PIF post
- Added gil-alterovitz as author
- Added justin-koufopoulos as author
/cc @eddietejeda
=> PIF day in the life blog post

_authors/cordelia-yu.md, _posts/2018-07-06-ask-18f-plain-language-government-terms.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/ask18f-plain.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/ask18f-plain)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/ask18f-plain/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/ask18f-plain/README.md)
- Add Cordelia as an author
- Publish 18F advice column about plain language
=> Ask 18F Plain language in government terms blog post

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-6.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-6)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/awfrancisco-patch-6/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/awfrancisco-patch-6/README.md)
/cc @Dahianna
=> Remove consulting engineer position

_posts/2018-07-10-introducing-accessibility-for-teams.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/accessibility-guide-3.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/accessibility-guide-3)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/accessibility-guide-3)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/accessibility-guide-3/README.md)
- Fix images
Checklist:
=> Accessibility guide post

_join/index.md
=> added content designer role to open positions

_authors/mark-headd.md, _posts/2018-07-17-five-contracting-tweaks-that-have-yielded-18f-better-procurements.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/contracting-hacks.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/contracting-hacks)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/contracting-hacks/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/contracting-hacks/README.md)
- Publish contracting tweaks post
=> Five contracting tweaks post

_join/index.md
Fixes issue(s) #2760  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/join-update.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/join-update)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/join-update/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/join-update/README.md)
- Shorten join.18f.gov content
- Sync content with sections from join.tts.gsa.gov
/cc @eddietejeda @Dahianna
=> Join content updates

_join/index.md
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/JennMoran-patch-3/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/JennMoran-patch-3/README.md)
-
-
-
Checklist:
=> removed content designer/added ux designer

_posts/2018-07-26-what-we-learned-from-building-a-pool-of-agile-vendors.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/bpa-image.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/bpa-image)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/bpa-image/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/bpa-image/README.md)
- Remove hero image
@Dahianna
=> Remove image

pages/contact.md
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/awfrancisco-patch-1/)
- Change Kwab to Lindsay on contact page
cc @Dahianna
=> Change Kwab to Lindsay

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/RemoveUXJob-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/RemoveUXJob-1)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/RemoveUXJob-1/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/RemoveUXJob-1/README.md)
- Removes link to UX job posting
Checklist:
/cc @awfrancisco @JennMoran
=> [MERGE AFTER 8:00PM PST 8/3] Remove UX Job Link

_join/index.md
- Fixes minor typo in 'How to Apply' section
Checklist:
/cc @fureigh
=> fixes typo in How to Apply section

_authors/jon-prisby.md, _posts/2018-08-07-how-login-used-evidence-based-buying.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/login-buying-post.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/login-buying-post)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/login-buying-post/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/login-buying-post/README.md)
- Publish login.gov evidence buying post
- Add Jon Prisby as an author
=> login evidence buying post

_posts/2015-05-11-moveforward.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisc-patch-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisc-patch-1)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/awfrancisc-patch-1/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/awfrancisc-patch-1/README.md)
- Remove embedded tweet
@Dahianna
=> Remove tweet that is now protected

assets/presentations/presentation-README.md
Adds presentation folder for staff to upload slide decks for public sharing. 
- Add presentations folder in assets
- Add readme
@Dahianna
=> Add presentations folder

_join/index.md
Resolve broken link on Join 18F page.
=> Update development and training link

.circleci/config.yml
Just remove reference to code climate, which we are not using anymore.
=> comment out reference to code climate in circleci

_about/index.md, pages/what-we-deliver.md
Fixes issue(s) #2792  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/fed-text.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/fed-text)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/fed-text/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/fed-text/README.md)
- Adds language to About and What We Deliver to make it clear that 18F staff are federal employees
- Changes estimated staff count from 200 to 120
cc @eddietejeda
=> Add federal employee language

_posts/2018-07-26-what-we-learned-from-building-a-pool-of-agile-vendors.md
=> Fix phrasing

_includes/head.html
Fixes issue(s) #2816 .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/increase_twitter_card_size.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/increase_twitter_card_size)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/increase_twitter_card_size/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/increase_twitter_card_size/README.md)
=> increase twitter card size

_join/index.md
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/awfrancisco-patch-1/)
- Add job
cc @Dahianna
=> Add cloud lead job

_posts/2016-01-12-hacking-inclusion-by-customizing-a-slack-bot.md, blog/index.html
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/guys.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/guys)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/guys/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/guys/README.md)
- Unpublishes guys bot post
- Redirects guys bot post to blog homepage
=> Unpublish guys bot post

_join/index.md
Application closed
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/Dahianna-patch-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/Dahianna-patch-1/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/Dahianna-patch-1/README.md)
- Remove job from Join page
/cc @awfrancisco @eddietejeda
=> Delete consulting technical lead job

pages/contact.md
Update bd contact
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/Dahianna-patch-2.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/Dahianna-patch-2)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/Dahianna-patch-2/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/Dahianna-patch-2/README.md)
- Change Lindsay to Kenny
=> Lindsay to Kenny

_posts/2018-09-27-antipatterns-in-agile-contracting.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/antipatterns-agile-blog.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/antipatterns-agile-blog)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/antipatterns-agile-blog/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/antipatterns-agile-blog/README.md)
- Add post to the blog on 9/27/18
=> Antipatterns in agile contracting blog post

_posts/2018-10-09-implementing-rules-without-rules-engines.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/rules-headline.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/rules-headline)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/rules-headline/)
@Dahianna
=> Change headline

_posts/2017-09-12-how-alaska-is-using-transparency.md, _posts/2018-01-30-getting-prepared-to-prototype.md, _posts/2018-03-13-win-big-by-going-small.md, _posts/2018-05-22-using-agile-methods-to-improve-the-rfp-process.md, _posts/2018-10-25-modular-contracting-and-working-in-the-open.md, tests/schema/tags.yml
Fixes issue(s) #2916  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/tag-alaska.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/tag-alaska)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/tag-alaska/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/tag-alaska/README.md)
- Create `alaska` tag for the DHSS project
- Add tag to relevant blog posts
@Dahianna
=> Create Alaska tag

_services_projects/hhs-states.md
Fixes issue(s) #2918
- Removes testimonial that will be used in Alaska project page
@Dahianna
=> Remove testimonial

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/new-cloud-job.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/new-cloud-job)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/new-cloud-job/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/new-cloud-job/README.md)
- Add cloud job opening to join page
=> Add new cloud engineer opening

_posts/2018-11-13-introduction-to-remote-moderated-usability-testing-part-1.md
Changed 2018-11-13 to 2018-11-14
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/fixed date.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/fixed date)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/fixed date/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/fixed date/README.md)
- Fixed publication date
=> Change date to today

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/close-job.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/close-job)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/close-job/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/close-job/README.md)
@Dahianna
=> Remove closed position

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-5.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-5)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/awfrancisco-patch-5/join/)
- Add 4 open CoE positions
=> Add open positions

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/jobs.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/jobs)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/jobs/join)
- Add 2 COE jobs
- Remove 4 closed jobs
=> Add new CoE jobs

pages/how-we-work.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/add_anchors)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/add_anchors/)
=> add anchors to headings

_authors/eddie-tejeda.md, _posts/2018-12-04-product-management-at-18f-part-1-new-engagements.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/pm-part-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/pm-part-1)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/pm-part-1/)
=> Publish Product Management at 18F post part 1

_posts/2018-12-11-product-management-at-18F-part-2-acquisitions.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/product-management-2.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/product-management-2)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/product-management-2/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/product-management-2/README.md)
- Add post to blog
/cc
=> Product Management at 18F part 2: Acquisitions

_posts/2018-12-11-product-management-at-18F-part-2-acquisitions.md
Add reference to earlier post in blog series as part of the intro. similar to others in series.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/eddietejeda-patch-2.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/eddietejeda-patch-2)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/eddietejeda-patch-2/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/eddietejeda-patch-2/README.md)
=> Add reference to earlier post in blog series

_posts/2018-12-20-product-management-at-18F-part-3.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-management-3.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-management-3)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/project-management-3/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/project-management-3/README.md)
- Add post to blog
/cc @eddietejeda
=> Product management at 18F, part 3 - Products and Platforms

_posts/2018-09-27-antipatterns-in-agile-contracting.md
=> Remove duplicate phrase

_styleguide/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/update_link.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/update_link)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/update_link/)
=> update link to brand.18f.gov

_includes/head.html
Fixes issue(s) https://github.com/18F/18f.gsa.gov/issues/2942
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/add_logo_to_twitter_card.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/add_logo_to_twitter_card)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/add_logo_to_twitter_card/)
=> add logo to twitter card

_about/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-6.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-6)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/awfrancisco-patch-6/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/awfrancisco-patch-6/README.md)
- Updates history section with offices of TTS and TTS move into FAS
=> Update history section

_authors/andrew-burnes.md, _posts/2019-02-05-ask-18F-6-analytics-open-source.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/ask-18f-6.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/ask-18f-6)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/ask-18f-6/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/ask-18f-6/README.md)
- Add Andrew as author
- Publish post
Checklist:
=> Ask 18F - How can I best advocate for the addition of open-source tools?

_posts/2019-02-07-the-cloud-is-not-a-virtue.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/cloud-virtue-post.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/cloud-virtue-post)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/cloud-virtue-post/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/cloud-virtue-post/README.md)
- Publish post
Checklist:
=> The cloud is not a virtue

_join/index.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/new-positions.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/new-positions)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/new-positions/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/new-positions/README.md)
=> Add new positions to site

README.md, _join/index.md
Duplicate of this PR: https://github.com/18F/18f.gsa.gov/pull/2972
Branch name does not include `/` for Federalist
=> Add link to tts join

.gitignore, Gemfile.lock
=> update capybara gem

_sass/_components/blog-index.scss, _sass/_core/utility.scss, pages/contact.md
First pass at #2958. Note that this does not implement the mobile styles.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/2958-contact-page)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/2958-contact-page/contact/)
=> Implement new contact page design

_posts/2019-02-28-prerequisites-for-modular-contracting.md
MERGE on 2/28
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/mcontracting-post.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/mcontracting-post)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/mcontracting-post/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/mcontracting-post/README.md)
- Add post to blog
=> Prerequisites for modular contracting

_layouts/post.html, _sass/_components/blog-post.scss
Fixes issue(s) #2604
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/fix_issue_2604.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/fix_issue_2604)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/fix_issue_2604/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/fix_issue_2604/README.md)
- Makes blog hero image smaller
=> fix issue #2604

_authors/amy-ashida.md, _authors/erin-strenio.md, _posts/2019-04-03-hcd-for-centralization-series-1-why-prioritizing-users-is-important.md
*DO NOT MERGE UNTIL 4/3*
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/hcd-it-centralization-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/hcd-it-centralization-1)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/hcd-it-centralization-1/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/hcd-it-centralization-1/README.md)
- Publish post
- Add authors
=> Human-centered design for IT centralization, part 1

_posts/2019-04-09-why-we-love-modular-contracting.md
Assorted edits and clarifications.
=> Assorted fixes

_posts/2019-04-03-hcd-for-centralization-series-1-why-prioritizing-users-is-important.md, _posts/2019-04-11-hcd-for-centralization-series-2-deciding-whether-or-not-to-centralize.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/add_it_centralization.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/add_it_centralization)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/add_it_centralization/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/add_it_centralization/README.md)
- Add new tag
=> add tag to page

_products_projects/federalist.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/update_federalist_blurb.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/update_federalist_blurb)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/update_federalist_blurb/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/update_federalist_blurb/README.md)
- Update Federalist blurb
See https://github.com/18F/federalist/issues/2158
=> update the federalist blurb

Gemfile, Gemfile.lock
=> jekyll 3.6

_posts/2019-04-03-hcd-for-centralization-series-1-why-prioritizing-users-is-important.md, _posts/2019-04-09-why-we-love-modular-contracting.md, _posts/2019-04-11-hcd-for-centralization-series-2-deciding-whether-or-not-to-centralize.md, _products_projects/federalist.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/various_fixes.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/various_fixes)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/various_fixes/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/various_fixes/README.md)
Here are the commits: https://github.com/18F/18f.gsa.gov/pull/3012
=> reintroducing changes lost in hard push

_posts/2019-05-07-human-centered-design-for-it-centralization-part-3-working-with-vendors.md, _posts/2019-05-09-human-centered-design-for-it-centralization-part-3-what-happens-after-you-centralize.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/it-centralization-2.1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/it-centralization-2.1)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/it-centralization-2.1/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/it-centralization-2.1/README.md)
- Add two blog posts
=> IT Centralization part 3 and 4

_posts/2019-05-16-how-18f-and-pif-work-together-in-agencies.md
changed name in summary text
-
-
-
Checklist:
=> Name change in summary text

_posts/2019-06-18-cross-functional-teams.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/cross-functional-postsvg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/cross-functional-post)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/cross-functional-post/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/cross-functional-post/README.md)
- Publish post to blog
=> Cross-functional teams post

Gemfile.lock, _authors/mark-headd.md, _authors/stephanierivera.md
=> add author files

_posts/2018-10-16-exploring-a-new-way-to-make-eligibility-rules-easier-to-implement.md
The post contains an email address to contact, but we have just switched the address. This update corrects the now-broken link.
- Fixed a broken email address
-
-
Checklist:
=> Adding new contact email

_posts/2019-04-09-why-we-love-modular-contracting.md
Help people learn more about the future blogs about modular contracting.
-
-
-
Checklist:
=> Adding link to taxonomy

_posts/2019-05-21-centralization-gone-right-a-case-study-on-uswds.md
Super small PR to add USDS to the list of agencies, since the USWDS was originally a proposal from @mollieru of USDS (who partnered with 18F to execute).
=> add credit for Mollie R's org

_styleguide/subpages/layout.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/fix-code-block-sidebar.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/fix-code-block-sidebar)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/fix-code-block-sidebar/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/fix-code-block-sidebar/README.md)
=> Fix code block not appearing on site

_styleguide/subpages/layout.md
=> Revert "Fix code block not appearing on site"

_authors/lalitha-jonnalagadda.md, _posts/2019-11-07-barriers-to-governments-adoption-of-user-centered-design-and-how-to-address-them.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/adoption-ux.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/adoption-ux)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/adoption-ux/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/adoption-ux/README.md)
- Add post to blog
=> barriers to ux post

_authors/dahianna.md, _authors/jerome-lee.md, _posts/2019-11-19-building-product-management-capacity-in-government-part-2.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/pm-capacity-2svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/pm-capacity-2)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/pm-capacity-2/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/pm-capacity-2/README.md)
=> PM Capacity part 2

_posts/2019-11-07-barriers-to-governments-adoption-of-user-centered-design-and-how-to-address-them.md
- Fix some evident copy-editing issues (subject verb, "3" vs "three", punctuation
- Make the three questions actually three questions
-
Checklist:
/cc @lalitha-jonnalagadda
=> A few copy-edits for clarity and syntax

_posts/2019-10-29-culture-climate-survey.md
We forget this the first time around, fixing now! :)
-
-
-
Checklist:
=> (WIP) Add preview excerpt for Culture and Climate Survey post

_includes/head.html
=> adjust og:image to linkedin spec

_sass/_templates/how-we-work.scss, pages/how-we-work.md
Fixes issue(s) #3101
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/acquisition-offerings.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/acquisition-offerings)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/acquisition-offerings/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/acquisition-offerings/README.md)
- Add acquisition offerings to "How we work"
=> Add acquisition to how we work

_authors/elisa-chen.md, _authors/qituwra-anderson.md, _authors/shawnique.md, _posts/2020-02-20-areas-for-growth-part-1-cad.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/areas-growth-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/areas-growth-1)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/areas-growth-1/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/areas-growth-1/README.md)
- Add authors
- Add post
=> Areas growth CAD post

_includes/head.html
=> (WIP) updating the og:image to follow what COE has and works

_posts/2020-02-27-areas-for-growth-2-mixed-methods.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/areas-growth-2.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/areas-growth-2)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/areas-growth-2/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/areas-growth-2/README.md)
- Add post
=> Areas of Growth 2 post

_includes/head.html
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/amoose-patch-1/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/amoose-patch-1/README.md)
- Adds the <head> tag because it doesn't exist 👻 
- Fixes the URL to the og:image property
Checklist:
=> Adds the <head> tag

_authors/ashley-owens.md, _authors/michelle-mcnellis.md, _posts/2020-03-18-an-acquisition-retrospective.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/coe-18f-bpa.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/coe-18f-bpa)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/coe-18f-bpa/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/coe-18f-bpa/README.md)
- Add authors
- Add post
=> 18F and CoE BPA post

_posts/2020-03-24-continuous-learning-for-product-managers.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/pm-learning.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/pm-learning)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/pm-learning/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/pm-learning/README.md)
- Publish post
=> PM learning post

_posts/2018-10-16-exploring-a-new-way-to-make-eligibility-rules-easier-to-implement.md
...for folks who copy/paste
-
-
-
Checklist:
=> updating displayed email address

_authors/anne-petersen.md, _authors/carter-baxter.md, _posts/2020-03-31-building-a-collaborative-culture.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/building-culture.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/building-culture)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/building-culture/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/building-culture/README.md)
- Add post
=> building culture post

admin/config.yml, admin/index.html, package-lock.json, package.json
Implement the Netlify CMS GUI to manages posts, authors, and service projects.
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/add-netlify-cms/)
- Add Netlify CMS config to `/admin`
/cc @Dahianna @lsgitter
=> Add Netlify CMS

pages/how-we-work.md
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/crisis-support.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/crisis-support)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/crisis-support/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/crisis-support/README.md)
=> Add crisis acquisition support to site

pages/how-we-work.md
=> Revert "Add crisis acquisition support to site"

_data/agencies.yml
Referenced in https://github.com/18F/18f.gsa.gov/issues/3150
-
-
-
Checklist:
=> Correcting typo in United States Tax Court name

_data/agencies.yml
Just a quick typo fix
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/stvnrlly-patch-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/stvnrlly-patch-1)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/stvnrlly-patch-1/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/stvnrlly-patch-1/README.md)
/cc @Dahianna
=> cfbp → cfpb

package-lock.json, package.json
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/apb-audit-packages)
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/apb-audit-packages/)
- Update NPM package dependencies
=> update package.json deps

_posts/2020-05-28-design-research-in-critical-times.md
- Consistent use of sentence case in headings
- Added missing line breaks
- Added missing space between words
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/research-in-critical-times-fixes/2020/06/02/design-research-in-critical-times/)
=> Fixes to capitalization and spacing

google16a62a069d0c4fa4.html
Google Search Console will allow us to view Google searches that brought users to the 18F site. Integration with Google Search Console also allows us to see impressions, clickthroughs, data by device, and more indexing and performance features.
-
-
-
Checklist:
=> Adding verification file to enable Google Search Console

pages/how-we-work.md
Updates 18F prices.
-
-
-
Checklist:
=> updating prices to reflect new policies

pages/how-we-work.md
Adjusting to reflect current PA pricing
- adjusts PA price to $250K, which is the accurate current price
-
-
Checklist:
=> update PA price

_includes/navigation/footer.html
Fixes issue #3224 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/accessibility-typosvg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/accessibility-typo)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/accessibility-typo/)
- Update typo on footer
=> Fix typo on "View accessibility statement"

_services_projects/doj-crt-portal.md, _services_projects/doj_crt_portal
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/DOJ-project-page.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/DOJ-project-page)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/DOJ-project-page/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/DOJ-project-page/README.md)
- Add project page
=> New DOJ CRT project page

_data/featured_services.yml
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/Dahianna-patch-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/Dahianna-patch-1/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/Dahianna-patch-1/README.md)
- Add project page (DOJ CRT)
-
-
Checklist:
=> add doj project

_posts/2020-09-03-a-federal-guide-to-de-risk-government-technology-projects.md
Reference: https://www.merriam-webster.com/words-at-play/complement-and-compliment-usage-difference
-
- Correct usage
-
Checklist:
/cc @MCHopson
=> Use "complement" instead of "compliment"

_authors/rebecca-refoy-sidibe.md
=> Update legal name

_config.yml, _layouts/styleguide.html, _styleguide/subpages/blog-components.md, _styleguide/subpages/colors.md, _styleguide/subpages/components.md, _styleguide/subpages/for-developers.md, _styleguide/subpages/images.md, _styleguide/subpages/layout.html, _styleguide/subpages/layout.md, _styleguide/subpages/typography.md, pages/guides.md
Closes issue(s) #3196 
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/apb-change-to-main/)
- Change github links to this repository to main branch
=> Update github links to main branch

PULL_REQUEST_TEMPLATE.md
Fixes PR template to include correct Federalist preview URL
- Update PR template Federalist URL
=> Update Federalist URL

admin/config.yml
- Updates all Netlify CMS PR's to point to the main, default branch
=> Update admin UI to create PRs into main branch

_sass/_components/blockquotes.scss
Fixes issue(s) #3181 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/nate-io/bugfix/ie-11-homepage)
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/nate-io/bugfix/ie-11-homepage/)
/cc @nate-io
=> Nate io/bugfix/ie 11 homepage

blog/index.html
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/update-blog-bars.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/update-blog-bars)
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/update-blog-bars/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/update-blog-bars/README.md)
Fix issue #3310
=> Update call out bars in blog homepage

_join/index.md
Add content updates requested by talent
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/BRANCH_NAME/)
-
-
-
Checklist:
=> Join page updates

.circleci/config.yml
caches gems and npm modules to speed circle (doesn't yet fix tests)
=> Ready for review: try gem and npm circle cache

_sass/_components/post-details.scss
Fixes the alignment of the post tags
(Optional) Closes #3404 .
=> convert tags to flex-box

_posts/2014-10-21-how-to-run-your-own-3-sprint-agile-workshop.md, _posts/2015-03-17-for-public-comment-the-https-only-standard.md
Restoring two posts I accidentally deleted from main when troublshooting netlify CMS.
=> revert last two commits - restore files

admin/config.yml
Update netlify cms to generate a sanitized branch name on PR's
=> Update netlify cms config to sanitize branch slug

_data/featured_agencies.yml
Changes `Department of Interior` to `Department of the Interior` in `featured-agencies.yml`.
=> Minor correction to DOI featured agency name

_posts/2021-04-01-building_a_user-centered_data_strategy.md
Fixes more non-breaking spaces in HTML output.
=> Fixes another non-breaking space

_posts/2016-02-29-informing-the-future-of-the-federal-front-door.md
=> fix double quotes for alt text

_posts/2021-06-14-improving_the_way_the_u-s-_tax_court_engages_with_the_public.md
This adds a link to the US Tax Court / Dawson github repo for the blog post on 2021-06-14
=> add link to DAWSON repo

_posts/2021-06-14-improving_the_way_the_u-s-_tax_court_engages_with_the_public.md
This changes the reported number of petitions reported based on observation from a judge at the court.
=> adjust number of petitions based on court's new data

_posts/2021-06-14-improving_the_way_the_u-s-_tax_court_engages_with_the_public.md, _posts/2021-06-16-building_capacities_within_a_government_agency_to_build_and_support_a_new_case_management_system_part_1.md, _posts/2021-06-17-building_capacities_within_a_government_agency_to_build_and_support_a_new_case_management_system_part_2.md, tests/schema/tags.yml
This adds tax court tag to blog posts to allow them to show up in related posts under the project page
=> Add 'tax court' tag to blog posts

_posts/2021-06-14-improving_the_way_the_u-s-_tax_court_engages_with_the_public.md, _posts/2021-06-16-building_capacities_within_a_government_agency_to_build_and_support_a_new_case_management_system_part_1.md, _posts/2021-06-17-building_capacities_within_a_government_agency_to_build_and_support_a_new_case_management_system_part_2.md
This removes notice of the open product specialist position at the court. They have since filled this position. They are still searching for a DevSecOps engineer.
=> Remove notice of one of the positions the tax court is hiring

_posts/2021-09-16-a_day_in_the_life_-_ingeniero_en_18f.md
=> Make small changes from author

_posts/2016-01-12-hacking-inclusion-by-customizing-a-slack-bot.md
This is a follow-on to #3558, since I missed the extra piece of metadata
=> Remove redirect, as well

_posts/2015-09-15-federalist-platform-launch.md
=> Update link to developmentseed.org in blog post

_posts/2022-08-02-senior-executives-pt2.md
Creates a new post for the blog entitled Senior executives part 2: work outside the traditional hierarchy to set up an initiative for success
=> New Blog Post: Senior executives part 2

_posts/2022-08-02-senior-executives-pt2.md
The title from part 1 was copied over and never altered.
=> Updated title to Part 2 Blog Post

_posts/2016-01-12-hacking-inclusion-by-customizing-a-slack-bot.md
=> Use Jina's correct name

_posts/2022-07-20-senior-executives-pt1.md
Hyperlinks at the bottom direct people to all of the articles in the series
=> Updating part 1 with hyperlinks

_posts/2022-07-20-senior-executives-pt1.md
=> Updating links to fix errors

_posts/2022-08-10-18f-tech-sandwich.md
=> switch images

_posts/2014-05-14-hacking-bureaucracy-improving-hiring-and-software.md, _posts/2016-01-21-what-we-can-learn-from-the-interiors-social-feeds.md, admin/index.html, package.json
This PR fixes accessibility errors on 2 older blog posts as well as the private NetlifyCMS page.
closes #3608
=> Fix accessibility issues

_posts/2023-03-23-A-check-up-for-agile-teams.md
Fix some typos and grammar nits
=> Various typo/grammar fixes

pages/vulnerability-disclosure-policy.md
This re-adds the old policy page. The text on the page has just been removed and replaced with a sentence that says to refer to the GSA one.
Closes https://github.com/18F/delivery-assurance/issues/140
(part 2)
=> Re-add vulnerability-disclosure-policy.md

_posts/2023-04-20-hi-from-the-18F-design-chapter.md
This PR publishes a blog post: https://github.com/18F/blog-drafts/issues/822
=> blog: hi from 18F design chapter

_authors/ron-bronson.md
Creates an author file for Ron Bronson so that he can be listed as an author on #3677. 
=> Create author ron-bronson.md

_authors/laura-nash.md
This PR adds Laura Nash as an author so they can be added to this post: #3677 
=> add author laura-nash

_posts/2023-04-20-hi-from-the-18F-design-chapter.md
This resolves the build errors that are showing up about missing author pages that have happened since the 4/20/2023 design chapter post.
=> Fix authors on 4/20/2023 design chapter post

README.md
Just a small update to the README to reflect the version of Ruby used in the Gemfile
=> Update documented ruby version from 2.7.2 to 2.7.4

_includes/banner-cta.html, _sass/_templates/how-we-work.scss, pages/how-we-work.md
https://github.com/18F/TLC-crew/issues/237
=> Tlc 237 how we work accessibility bugs

_posts/2023-06-13-The-four-operating-levels-of-18F-projects.md
=> Minor text changes

_layouts/post.html
Add the full width utility class to the blog container to force consistant width across all posts. 
Closes #3666
=> Force blog container to be full width (Fixes #3666)

README.md, docker-compose.yml
Resolves the outdated Docker Compose file and fixes the command error when running the container.
Closes #3706 
=> Upgrade docker-compose.yml and fix launch command

pages/contact.md
- Added contact form
- Made all team names sentence case
- Updated text around hiring after confirming that we don't add 18F positions to the Join 18F page
[View these changes](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/tlc-contact-form/contact/)
=> Add contact form and update text on contact page

pages/contact.md
Remove the BD contact form and replace it with the inquiries email
[Review the change](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/remove-contact-form/contact/)
=> Removing BD contact form and adding the email back

_authors/qituwra-anderson
Adds Qituwra to the blog author directory.
=> Adding qituwra-anderson to author directory

_authors/jason-nakai.md
this PR adds Jason Nakai to the author database.
=> Create jason-nakai.md author

_posts/2023-09-07-catching-up-with-the-tanf-data-portal-project.md
=> Update inquiries email typo

_posts/2022-11-29-18f-checks-in-with-jerome-lee-and-the-eapd-project.md, _posts/2023-02-24-18f-checks-in-with-emily-read-and-the-usgs-water-resources-mission-area-projects.md, _posts/2023-04-25-18f-checks-in-with-the-dawson-project-at-the-us-tax-court.md, _posts/2023-09-07-catching-up-with-the-tanf-data-portal-project.md
Preview link: https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/ars/add-18f-checks-in-tag/tags/18f-checks-in/
=> Add "18F checks in" tag for posts that check in with 18F partners over time

_sass/_components/blog.scss
This PR adds styling to testimonial pull quotes within blog posts. Closes #3759 .
👓 [Preview](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/ik/blog-blockquotes/2023/09/07/catching-up-with-the-tanf-data-portal-project/)
=> Add styles for blog pull quotes

_principles/index.md
This PR fixes the alignment of the content on the partnership principles page.
Closes #3765 
👓 [Preview](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/ik/partner-page-alignment/partnership-principles/)
=> Fix partnership principles alignment 

README.md
Adds warning to README about the current (broken) status of Docker development.
=> Add warning about status of docker development

pages/AI-services.md, pages/digital-service-transformation.md, pages/home.html, pages/strategy-development.md, pages/vendor-acquisition-support.md, pages/website-modernization.md, pages/work-with-us.md
- The "work with us" button goes to the "work with us" page
- AI offering rescoped 
- New names for offerings 🎉
- A page for each of our standard offerings
- A menu of services with pricing
- Linting whitespace
- Do some usability research on content with perspective partners
- Enhance design for new offerings pages
- Look for some quotes that are not already used on the website 
=> 18F Offerings

README.md
- Update brand guide links in repo
- I only found them in the Github README, not in website content.
=> Update brand guide links in repo

pages/work-with-us.md
removes pricing and adds time as ranges
Timeline update:
-  website transformation 3 months-1 year
-  acq range from 6 months- 1.5 years
link to preview of page https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/remove-pricing/work-with-us/
=> remove pricing

_data/guides.yml
Updates dynamic links for Accessibility, Engineering, and Product guides to their new domain. This achieves milestone #5 of [18f/guides epic 156](https://github.com/18F/guides/issues/156).
=> Update links for accessibility, engineering, and product guides

_authors/boon-sheridan.md, _posts/2024-01-31-gathering-feedback-with-customer-panels.md
Adds Boon Sheridan's author file and a new blog post
=> Add boon sheridan and publish new post

_authors/boon-sheridan.md, _posts/2024-02-01-gathering-feedback-with-customer-panels.md
Publishes the post on Gathering feedback through customer panels and adds Boon Sheridan as an author. This was blog post was published preemptively and then reverted. It will be merged on 2/1/2024.
=> Add boon and publish post

_config.yml, _includes/analytics.html
Updates Google Analytics tag to the [provided tag](https://github.com/18F/TLC-crew/issues/586)
Resolves https://github.com/18F/TLC-crew/issues/586 for 18f.gsa.gov
=> Update google analytics tag

pages/AI-services.md
There's a missing closing bracket for closing `section`.
=> Missing closing bracket for section in AI-services.md

_authors/jon-roberts.md, _authors/neil-martinsen-burrell.md, _posts/2024-04-03-18f-practices-in-action.md
=> Cisa registrar blog post

_posts/2018-07-12-the-case-for-open-source-software.md, _posts/2018-08-07-how-login-used-evidence-based-buying.md, _posts/2019-02-07-the-cloud-is-not-a-virtue.md, _posts/2019-03-07-six-ways-we-improved-tts-design-research-guild.md, _posts/2019-03-19-18F-5-Anniversary-achieve.md, _posts/2019-04-09-why-we-love-modular-contracting.md, _posts/2020-02-06-even-with-a-design-system-you-still-need-a-designer.md, _posts/2020-04-09-18f-help-during-critical-times.md, _posts/2020-06-03-making-critical-government-information-more-resilient.md, _posts/2021-03-31-18f-public-benefits-portfolio-reflects-on-the-last-year.md, _posts/2021-04-27-building_product_management_capacity_in_government_part_3_a_day_in_the_life_of_a_new_product_owner.md, _posts/2021-04-27-we_asked_our_coworkers_why_did_you_join_18f.md, _posts/2021-06-14-improving_the_way_the_u-s-_tax_court_engages_with_the_public.md, _posts/2021-07-27-the_tts_handbook_a_21st-century_approach_to_internal_documentation.md, _posts/2022-01-21-what-have-you-learned-from-other-18F-designers.md, _posts/2023-04-25-18f-checks-in-with-the-dawson-project-at-the-us-tax-court.md, _posts/2023-09-07-catching-up-with-the-tanf-data-portal-project.md, _posts/2024-02-01-gathering-feedback-with-customer-panels.md, _posts/2024-04-03-18f-practices-in-action.md, _products_projects/cloud-gov.md, _services_projects/doi-nrrd.md, examples/project-template.md
Use `blockquote` element for blockquotes.
(Optional) Closes [#(issue_number)](https://github.com/18F/TLC-crew/issues/458)].
=> Replace blockquote div with blockquote element

_includes/layouts/blog-page.html, config/filters.js, content/pages/blog.liquid
This commit creates and implements a blog post paginator that replicates the behavior of the current 18F site (/blog, /blog/page/2).
Closes a checklist item in #3989
=> Add blog post pagination

_posts/2024-06-18-back-to-basics-in-the-age-of-ai.md
Fixed quotation marks and content in bullets per 18F style and some compound words per AP. Revised two hyperlinks for accessibility: they were the same text; made each unique. Fixed (hopefully) markdown for footnote
=> Fix style, typos and a couple links in AI blog post

_posts/2024-07-09-working-with-oracle-databases-in-open-source-projects.md, _posts/2024-07-17-working-with-oracle-databases-in-open-source-projects.md
Adds blog post for https://github.com/18F/blog-drafts/issues/873
> [!IMPORTANT]
> This pull request should only be merged AFTER #3957 is merged. This post will not look good otherwise.
=> Add post for Oracle databases (blog-drafts #873)

_posts/2024-07-17-working-with-oracle-databases-in-open-source-projects.md
Oops! A "todo" made it through multiple rounds of approval, glad I caught it so quickly
=> Update Oracle blog post

.github/workflows/repository_dispatch_create_issue.yml
Still trying to wrap  the body text within the issue.
=> Try another way of escaping body text

content/pages/work-with-us.html
Edit content on "Work with us" page according to [Google Doc draft](https://docs.google.com/document/d/1ANkawZDmoXAA0PWWtwih2xDLTJ_Ef02ZY0vqIuwthr8/edit).
=> Update "Work with Us" page content

content/pages/about.md
Fix broken link to Office of Solutions and update the link to the new TTS site.
=> Fix broken link to Solutions and update link to TTS site

content/posts/2024-11-05-three-ways-to-write-fearless-spreadsheet-formulas.md
Adds spreadsheet formulas blog post
Closes https://github.com/18F/blog-drafts/issues/898
=> Add blog post "Three ways to write fearless spreadsheet formulas"

content/posts/2024-11-05-three-ways-to-write-fearless-spreadsheet-formulas.md
This commit adds copy edits and fixes some of the code examples and a table that wasn't showing the last column.
You can read a thing a million times but sometimes issues are only clear after you press Publish.
=> Update spreadsheet formula blog post

README.md
This MR fixes a small typo in `README.md` file.
=> docs: fix small typo in README.md
