_posts/2015-01-08-an-open-source-tool-for-easier-database-testing.md

I integrated @kategarklavs' edits in https://github.com/18F/18f.gsa.gov/pull/451#issuecomment-69217164, and added a colon before the list of commands.

Integrate Kate's notes on db-subsetter, also add a colon

---

deploy/18f-site.conf

I haven't pushed this config update, but everything's ready on the Hub side (well, technically once 18F/hub#57 goes in, but the `hookshot` task is running on 18f.gsa.gov).
cc: @afeld @gboone @konklone

Add public Hub deployment webhook endpoint

---

script/post

A new script for creating posts quickly and uniformly.
```
Usage: script/post [options]
-t, --title TITLE                Post title
-d, --date DATE                  Date published (default, today)
-i, --image IMAGE                Post image
-a, --author AUTHOR              Post author (comma separated)
-g, --tags TAGS                  Tags for this post (comma separated)
-c, --content CONTENT            The text of the blog post (not the most efficient)
```
Will create a new markdown file in the user's `_posts` directory with all the correct front matter fields ready to go. A command like `script/post -t "New post" -d "January 6, 2015"` will create a markdown file:
```
---
title: New Post
date: '2015-01-06'
layout: post
image: 
tags: 
authors: 
description: 
excerpt: 
--- 
...
``` …

Adds a script for quickly creating a new post

---

pages/index.html

It came to our attention while discussing #399 that the privacy language we have on 18f.gsa.gov is inaccurate and not in keeping with terms we are using on other 18F projects. This commit integrates more accurate terms suggested by @polastre.

Revised privacy language

---

_posts/2015-02-09-the-first-gov-domains-hardcoded-into-your-browser-as-all-https.md

This adds a link to [the FTC's post](http://www.ftc.gov/news-events/blogs/techftc/2015/02/government-agencies-enable-http-strict-transport-security-public) to our HSTS post.

Add link to FTC post

---

deploy/18f-site.conf

This is in reference to both 18F/hub#99 and 18F/hub#145. I also updated `/etc/nginx/nginx.conf` to update `gzip_types` to include `application/json application/javascript`. The changes are already running in production, and confirmed via [Postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en).
cc: @gboone @konklone

Fix the Hub API's content-type for JSON

---

_posts/2015-02-09-the-first-gov-domains-hardcoded-into-your-browser-as-all-https.md

Drops a link to [IE's adoption of HSTS](http://blogs.msdn.com/b/ie/archive/2015/02/16/http-strict-transport-security-comes-to-internet-explorer.aspx). I don't include it in the top sentence with the timeline, because I'm not sure when a stable version of IE will be released with this included. When that happens, we can update this to guarantee "2015" more confidently.

Mention IE's adoption of HSTS and the preload list

---

deploy/18f-site.conf
deploy/cors.rules

For the public paths that have content for people to read (aka not the webhooks).
I'd like to test this out on the staging server manually before merging. I'll indicate when that's done.
Fixed #507.

Adds CORS to the production and staging sites

---

deploy/18f-site.conf

Wasn't strictly necessary, just seemed like useful cleanup.

Updated HTTPS cert name

---

pages/rfpez.md

Just updating the language on our RFP-EZ landing page to refer to OASIS Discovery instead of OASIS Mirage.

Update Mirage references to Discovery

---

_data/import-public.rb
pages/pif/fellows/index.html

@gboone Once 18F/hub#191 is merged into the public Hub, this will import `_data/pif_team.json` and use that to generate the PIF page.

Import pif_team data from the public Hub API

---

_plugins/pif_data.rb

@gboone This causes the PIF pictures to reappear, since the `name` corresponds to the key value of `_data/pif_team.json` that gets stripped out by the `group_by` filter in `pages/pif/fellows/*`.

Plugin to insert the 'name' field into PIF data

---

_plugins/author.rb

Resolves all 60 errors generated by [pa11y](http://pa11y.org)/[HTML CodeSniffer](https://squizlabs.github.io/HTML_CodeSniffer/).
Sample error:
We still have some warnings to take a look at, but now we have zero errors:

Use non-redundant alt text for team photos

---

pages/humans.txt

This pull request adds a simple `humans.txt` file. You can read more about the how and why of adding a `humans.txt` file over at [humanstxt.org](http://humanstxt.org/). TL;DR:
> It's an initiative for knowing the people behind a website. It's a TXT file that contains information about the different people who have contributed to building the website.
As an added bonus, it looks like this would be [the 2nd .gov with a `humans.txt` file](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#qscrl=1&q=site:.gov+inurl:humans.txt) after broadbandmap.gov (shoutout @feomike).
The humans.txt file is generated from `_data/team.json` (although technically it should be contributors to the site, perhaps via the GitHub API, not merely team members).
It looks like this:
```
/* TEAM …
```

Add humans.txt

---

_posts/2015-03-17-does-18f-pass-the-bechdel-test-for-tech.md
_posts/2015-03-17-for-public-comment-the-https-only-standard.md
_posts/2015-03-19-18f-by-the-numbers.md
_posts/2015-03-19-how-we-built-analytics-usa-gov.md
_posts/2015-03-20-one-year-in-and-looking-forward.md

- Adds the one year in and looking forward post
- fixes chronology of posts other from this week
- Bechdel Test, HTTPS standard, By the Numbers and analytics.usa.gov posts were slightly out of order because we didn't provide a date and time in the `date:` field (good to remember for future days with multiple posts).

One Year In and Looking Forward

---

_includes/head.html

Ugh - I hadn't committed the change to the header file, so the `<link>` tag was still pointing to `fonts.googleapis.com`.
@gboone While my local testing was sound on Chrome and Firefox, this means that your tests on Safari and IE were not actually testing the inlined fonts. My apologies. Mind running that test again?

Actually reference the new fonts

---

_config.yml
_layouts/post.html

Inspired by @andrewmaier’s pursuit to find the correct markdown file to
edit in order to fix a typo. I’m considering only showing this on
`staging` but don’t really see a problem putting it on the public site.

Adds an edit link to prose on each post

---

_posts/2015-04-09-flexibility-when-releasing-a-new-product-peace-corps-new-donation-platform.md

The Peace Corps post URL is prefixed with `/design%20and%20code/`:
> https://staging.18f.us/design%20and%20code/2015/04/09/flexibility-when-releasing-a-new-product-peace-corps-new-donation-platform/
It should be: 
> https://staging.18f.us/2015/04/09/flexibility-when-releasing-a-new-product-peace-corps-new-donation-platform/
It's because of the `category` field in the front matter, which this PR removes. I think we need to fix the URL generation before we can start using categories.

Remove category from Peace Corps post

---

assets/_sass/_custom.scss

My fix from yesterday introduced a regression at bigger sizes. Widths between about 980 and 1100px exhibit this:
This tweak moves the `min-height` for the name elements out of the smaller breakpoint so that it's always applied.

Fix name wrapping on bigger screens

---

deploy/18f-site.conf

Little known fact about nginx vhost configs - you have to keep `add_header` directives at the same level. By adding `cors.rules` into specific paths, it prevented the HSTS header from appearing. This is dumb, but this fixes it. The tradeoff is that now the entire site is available over CORS, for `GET`, `OPTIONS`, and `HEAD` requests. Since that seems fine to me, this seems like the simplest fix.

Move CORS rules include to fix HSTS header

---

Gemfile
Gemfile.lock

This should fix 18f.gsa.gov/feed and close #756 by reverting Jekyll to the most stable version.

Fix the RSS Feed

---

_config.yml

Nothing dangerous about generating them, but there's also no reason to so we might as well not.

Adds more files to be excluded from site generation

---

pages/consulting.md

Team member names were displaying in a single line. Updated so they will each appear on their own line. 
Should add links to bios when they are live.

Consulting format

---

.cfignore
Staticfile
cf-deploy.sh
manifest.yml

These are some sample CF manifests and scripts that we can use to deploy the site.
I deployed it to `site.18f.gov` but you all can do what you see fit with this.
There is an org `18f` and a `site` space if you are not invited please ask me.

Add CF deployment scripts and manifest

---

deploy/fabfile.py
go
pages/team.html

Closes #814 by creating a separate configuration file for production that disables generation of the bio pages and modifications to deployment scripts to match. Also leaves the `<a>` tags without an `href` and adds the `disabled` class on production. On staging people should be able to click through to their bios.
Also relocates the `team` page's template to a more reasonable place. See 0a11349 for more detail.

Team template fix

---

CONTRIBUTING.md
LICENSE.md

@ultrasaurus raised the point that teammates may not wish to dedicate their image to the public domain. I am not certain that dedicating a photo to the public domain causes you to lose control over your likeness, but want to be responsive to the concern.
This PR adds a small section to the `LICENSE` and `CONTRIBUTING` files that exempts teammate photos from the public domain dedication. Since the copyright in photos is generally held by the photographer, not the subject, that basically means that the contributor has to know that the copyright holder (the photographer) is okay with hosting their photo here. I'm very comfortable running under the assumption that this is already the case for all the photos here, and will be going forward, but it's relevant to mention.
cc @mwweinberg

Copyright disclaimer on team photos

---

assets/_sass/_custom.scss

The compressed line heights on the [18F Consulting page](https://18f.gsa.gov/consulting/) were annoying me. Also, the new nav was butting up against the top of the content. This gives a few things on the page room to breathe.
Before:
After:

Improved line heights on bare template

---

deploy/18f-site.conf

Also, per 18F/hub#299, I updated `/etc/nginx/nginx.conf` to use `gzip_static on` after rebuilding Nginx at version 1.8.0 with `--with-http_gzip_static_module` enabled, in anticipation of using gzipped files produced by the impending [jekyll_pages_api_search gem](https://github.com/18F/jekyll_pages_api_search/).
BTW, I noticed that a `sudo service nginx restart` isn't enough to ensure the new build is loaded; the error logs show `unknown directive "gzip_static"` when issuing `sudo nginx -s reload` after a restart. You have to manually kill the master process, then run `sudo service nginx start`. After that, the `gzip_static` directive warnings go away.
Manually reissued the last webhook to `/hub/deploy` to ensure that things are working again as intended.
cc: @gboone @konklone

Restore /hub/deploy webhook

---

Gemfile.lock
_config.yml
_includes/nav.html
_layouts/post.html
assets/_sass/_custom.scss
blog/index.html
deploy/test.sh
news/index.html

Changed the following areas from `/news` to `/blog`:
- _config.yml
- global nav button
- took out `back to all posts` button in blog post layout
- renamed news folder to blog folder
closes #356

renamed news to blog

---

Gemfile
Gemfile.lock

Closes #905 and #904 to fix problems in staging.
Starting with #900 the Jekyll build was failing and causing a segmentation fault on the staging server. This was causing the site to not rebuild at all. Any occasionally it would cause the ruby job to hang indefinitely, only killable with `kill -9` :neutral_face: :neutral_face: :neutral_face: :neutral_face: :neutral_face: 
@konklone and I tried a few tactics for troubleshooting including rolling back version of `jekyll` and several plugins, and upgrading ruby itself. When none of those worked I started checking out commit by commit starting with the commit before the merge commit generated in #900 and working our way up until a commit broke the build again and reverted the project to the state it was in. In this case, the build broke after …

Reverts Gemfile to last working version

---

Gemfile
Gemfile.lock
_config.yml
pages/tags/18f consulting.md
pages/tags/18f events.md
pages/tags/API.md
pages/tags/consulting services.md
pages/tags/day in the life.md
pages/tags/demo day.md
pages/tags/department of labor.md
pages/tags/how we work.md
pages/tags/market research.md
pages/tags/open data.md
pages/tags/open government.md
pages/tags/our projects.md
pages/tags/peace corps.md
pages/tags/presidential innovation fellows.md
pages/tags/public service.md
pages/tags/request for quote.md
pages/tags/speaker series.md
pages/tags/success stories.md
pages/tags/sunshine week.md
pages/tags/the hub.md
pages/tags/usability testing.md
pages/tags/user experience.md
pages/tags/user research.md
pages/tags/user-centered design.md
pages/tags/ux design.md
pages/tags/what we learned.md
pages/tags/white house.md

Closes #917 by installing the `jekyll-redirect-from` plugin and creating pages for the old "space separated" tag archives to establish the redirects.
This plugin is pretty cool and makes setting up redirects super simple.

Redirect a bunch of old tags

---

blog/index.html

slugifies links on `/blog/` instead of URL encoding them.

Final touch to resolve #917

---

_posts/2015-02-24-how-to-use-github-and-the-terminal-a-guide.md

Since you can no longer [add new projects to google code](http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html), it doesn't make sense to list it as a GitHub alternative.

remove google code, it's EOL

---

_posts/2015-01-21-join-us.md
_posts/2015-02-25-We-Are-Hiring.md

Occurred to me that these two posts are still coming up in search results, so we should direct people to the up-to-date information. Totally open to other ideas about how to word/format it.

link to hiring site from job-related blog posts

---

feed.xml

Stops the final comma in situations like "Author 1, Author 2, Author 3," cc: @konklone

Excludes the comma from the final list item.

---

pages/index.html

We'll keep the rainbow logo around in case we need it again.
Not proposing we do this now. But we can merge whenever we're ready to bring the old standard back.

Reverts the logo on the homepage.

---

_includes/byline.html
_includes/sidebar.html
_layouts/profile.html

This will only work in places where the team page is enabled – currently not in production. This template logic looks pretty bonkers ATM and we'll want to un-complicate it once we enable the profiles everywhere.

Adds to the byline include links out to the author's team page

---

_data/authors.yml
_posts/2014-04-11-open-source-terms-of-service-a-better-developer.html
_posts/2014-04-12-how-a-pepperoni-pizza-is-inspiring-open-government.html
_posts/2014-05-09-a-few-notes-on-notalone-gov.html
_posts/2014-05-10-make-gov-apis-better-with-user-experience.html
_posts/2014-05-11-18f-shows-what-is-possible-in-government-with-fbopen.html
_posts/2014-05-14-hacking-bureaucracy-improving-hiring-and-software.html
_posts/2014-05-19-packaging-up-api-usability-testing-for-agency-re-use.html
_posts/2014-05-29-announcing-the-developer-program-a-new-hub-for.html
_posts/2014-06-25-intro-to-apis-working-with-urls-json-apis-and-open.html
_posts/2014-07-15-hot-off-the-press-18fs-api-standards.html
_posts/2014-07-16-midas-a-marketplace-for-innovation-in-government.html
_posts/2014-07-23-take-a-gander-at-our-developer-page.html
_posts/2014-07-29-18f-an-open-source-team.html
_posts/2014-07-31-working-in-public-from-day-1.html
_posts/2014-08-12-the-contributors-guide-to-18f-code-for-the-common.html
_posts/2014-08-21-creating-an-open-fec.html
_posts/2014-09-04-a-new-look-at-the-freedom-of-information-act.html
_posts/2014-09-08-the-encasement-strategy-on-legacy-systems-and-the.html
_posts/2014-11-17-taking-control-of-our-website-with-jekyll-and-webhooks.md
_posts/2014-11-26-how-to-use-more-open-source.md

There were a little over 20 remaining duplicate bylines, where `<p class="authors">` bylines had not been removed.
I adjusted the `_authors.yml` file for Matt Chessen, so as to keep his original byline description. In a couple of cases, I moved the "cross-posted from" language to the bottom of the post in a little italicized paragraph.
I also updated our webhooks post that talked about our authors plugin, to mention that we've since changed it and linked to the relevant issue.
Fixes #998.

Fix some duplicate bylines, make author adjustments

---

_layouts/tag_index.html

We already have a link to /blog in the global nav menu. Will update this if I find more that we missed but this might be the last one.

Takes out the back link on /tags archives

---

pages/developers.md

It's a small but simple best practice that you want both `x.gov/developer` and `x.gov/developers` to arrive at the developer hub since it's easy for folks to misremember which it is and get a 404 if they are wrong.  
Since this was [discussed](https://github.com/18F/18f.gsa.gov/issues/115) a year ago, we've updated our practices and [this method of offering redirects is allowable](https://18f.slack.com/archives/g-accessibility/p1432221216000214).  
This pull request should result in `18f.gsa.gov/developers` redirecting to `18f.gsa.gov/developer` instead of 404ing.  
https://18f.gsa.gov/developer/

adding a redirect for /developers

---

_posts/2015-07-15-openfec-api-update.md

This PR turns this:
Into this:

Fix FEC blog post JSON formatting

---

pages/consulting.md

removing default subject line per @CaliforniaKara 
(otherwise, gmail will put them all together when I get the inquiries e-mails)

remove default subject line in consulting page mailto:

---

_posts/2015-05-07-layering-innovation.md

I tried to find this post about devops by going to 18f.gsa.gov/tags/devops and found nothing, so I added the devops tag. Plz merge.

Adds the `devops` tag to Diego's post about cloudfoundry

---

_includes/nav.html
_layouts/bare.html
_layouts/default.html
_layouts/page.html
_layouts/post.html
_layouts/press.html
_layouts/profile.html
_layouts/team.html
assets/_sass/_custom.scss

I don't know what [this idiot](https://github.com/gboone) was thinking when he did the skip links [the first time 'round](https://github.com/18F/18f.gsa.gov/commit/6c79ff9833ce1997528144f154c4e2c74fc2e207#diff-70c103dc160c67e7a579206a58d26b94) but they're way better now.
This PR fixes the skip link target and makes it visible on `:focus`. It also adds a proper `:focus` state to the global nav links and properly anchors the main content section on all layouts. This should be a major improvement for users who navigate the page with a keyboard.

Skip links and happy meals

---

_data/services.yaml

https://18f.gsa.gov/ shows "doing it.." instead of "doing it."

template page already puts a period after cta

---

_posts/2014-03-31-announcing-fbopen-government-opportunities-made-easier.html

I think this is the only post using `products` and not `our projects`. I'd also be open to renaming "our projects" (or adding a new tag) to "our products" but the latter seems less inclusive somehow. Thoughts? @18F/blog

Changes `projects` tag to `our projects`

---

deploy/hookshot.js

The public Hub push in 18F/hub#370 failed due to the webhook exceeding the default 100K limit, just as in 18F/pages#15. This applies the same fix as 18F/pages. Still waiting on coreh/hookshot#12 to get merged upstream, so before this change is deployed, I'll need to install 18F/hookshot#json-options on the server:
```shell
npm install git+ssh://git@github.com/18F/hookshot.git#json-options
```
cc: @gboone

Pass through bodyParser.json() middleware options

---

_includes/scripts.html

This changes our DAP embed code to:
```
<script id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA"></script>
```
This takes advantage of the DAP's new [centrally hosted JavaScript code](https://www.digitalgov.gov/2015/08/14/secure-central-hosting-for-the-digital-analytics-program/), which means 18f.gsa.gov will automatically get security updates, new features, and other bugfixes automatically.

Use new centrally hosted DAP code

---

_data/authors.yml

Apparently we spelled it correctly almost everywhere!

Spell check: Guest author name

---

README.md
deploy/18f-site.conf

I moved the staging site to staging.18f.gov, and removed all references to staging.18f.us from nginx, from the README, and updated this repo's webhook URL.
staging.18f.us is no longer guaranteed to work at all (and doesn't serve an 18f.us cert anymore, expired or not).
I verified that the staging.18f.gov webhook was operating as expected with a couple of trivial HTML comment hotfixes to `staging`.

Move staging site to staging.18f.gov

---

_posts/2015-10-09-cloud-gov-launch.md

The link for the cloud.gov contact form was missing from the blog post. I'm adding it here, not quite sure what to do next so I'm pinging a few people :)
@awfrancisco @mogul

Link for CF contact form

---

_posts/2015-10-08-updated-18f-content-guide.md

It looks like the link was copied from a Google search result, which yields a Google-tracking URL instead of a direct URL.

Replace Google redirect with an actual link

---

_posts/2015-10-09-cloud-gov-launch.md

Saw on Hacker News and elsewhere that people wanted to know where the awesome GIF came from. Not very discoverable, but at least if they click they'll see it.
Note I made this edit via the GitHub web interface, and I'm not sure how Markdown will handle the <img> inside brackets... So please test before merging!

Fixed caps on "PaaS", added link from GIF to source

---

_includes/byline.html

Modifies the byline include so that no comma separates names when only
two authors are on a post.
Fixes #1246, cc: @awfrancisco @18F/blog

Two author byline fix.

---

pages/tags/user research.md

The page at /tags/user-research was redirecting to itself! Infinitely!
What is supposed to happen is the old /tags/user%20research/ redirects to /tags/user-research; that happens now.
cc: @carodew @awfrancisco @18F/blog

Fixes the user-research tag bug

---

assets/_sass/_custom.scss
assets/_sass/base/_typography.scss
assets/_sass/components/_blog.scss
blog/index.html
pages/index.html

Did a few things to clean up the CSS. Was poking around and noticed that some styles were using the same styling across the site so move them in to `_base.scss`. Here's a list of things: 
- moved `p` & `h1` to site wide styling
- created `class=“h4”` for smaller `h1` tag in blog posts vs styling the `h1` tag itself
- move container padding to its own class `container-spaced` and removed `blog entry` and `service-entry` tags 
- increased `p` font size from 12 to 14 to be consistent in base
@gboone the big one I would love your opinion on is increasing the font size. @msecret and I noticed that the site uses 14px except for the blog which is slightly smaller. What are your thoughts on making it consistent throughout the site? Here are the differences: 
12px on the live site: 
14px on the …

More CSS Refactoring 

---

_posts/2014-09-25-design-studio-onrr.md
_posts/2015-03-18-sunshine-week-extractive-industries-transparency-initiative-event.md
_posts/2015-11-02-useiti-what-we-learned-where-were-headed.md

We tagged two posts EITI, another USEITI. Since our work is about both the US initiative and part of the global, we should use both.

Tag movement for USEITI posts

---

_includes/newsletter.html
_layouts/post.html
pages/index.html

The newsletter signup is now an `_include` as it can appear in various layouts or pages.

Create an `_include` for newsletter signup

---

_layouts/tag_index.html

Whoops! In trying to clean up the CSS, I broke the blog titles in the tag list page. This fixes that.

fixes the blog title of tag pages

---

go

The big thing this PR does is makes the `build` command a little more useful by adding two default parameters: `watch` and `config`. Pass `true` to `watch` to enable automatic rebuilding, and a string to `config` to enable multiple config files. Example of the latter can be found in the `production_build` command.

Fixes problems with Travis integration and the go script

---

_data/authors.yml
_posts/2015-06-15-building-a-better-welcome-wagon.md
_posts/2015-08-10-18f-design-methods.md
_posts/2015-09-28-web-design-standards.md
_posts/2015-11-19-how-we-use-a-lean-approach-to-product-design.md

Either `colin`'s name changed in the team api, or we always had it wrong in the author file. Either way, it's fixed now.

colin => colinmacarthur

---

_includes/newsletter.html

We don't need to show that, and it's probably better that we don't anyway.
@adelevie this is a fix for the accessibility issue you reported on #blog this afternoon. It turns out we were not hiding a field that didn't need any user input anyway. This fixes the `input` to make it `type="hidden"` instead of `type="text"`. cc: @nickbristow @18F/blog

Hides the unlabeled field from the DOM, addresses #a11y issues

---

_posts/2015-10-15-best-practices-for-distributed-teams.md

I'm assuming that 4 hours is the correct number, and not 5 hours, because the time range "1 p.m. to 5 p.m. ET." is specified.

Fix inconsistent reference to overlap time

---

_config.yml

This should make for slightly more sensible time strings in the [feed](https://18f.gsa.gov/feed/). right now they're all set to `00:00` unless we pass something else with `date` on a post. That's `00:00+00:00` to be more accurate, or midnight, GMT. That turns out to be sometime between 2 and 7pm for most Americans, unless we set a different time, then it's even later in the day or maybe even the next day depending on what news readers do with the UTC time stamp.

Sets a default timezone

---

_posts/2015-12-09-an-open-source-government-is-a-faster-more-efficient-government.md

The paragraph here about cloud.gov was confusing to me -- I wasn't sure what it meant after I read it. This is a second pass that tries to make it more clear, and cuts the line about what cloud.gov saves for the taxpayer to something more terse.

Rewrites cloud.gov paragraph on open source post

---

_posts/2015-12-23-looking-back-2015-our-own-words.md

This does a few tiny things to the 2015 roundup post:
* Fixes a couple of typos I spotted in the post.
* Adds the word `more` after `14` in the part about preloading domains, to be more precise.
* Changes my `really` to `thoroughly` just for some sheer variety (there are 16 instances of `really enjoyed` in the post).

A few tiny tweaks to the 2015 roundup post

---

_posts/2015-12-23-looking-back-2015-our-own-words.md

Changed caption of image under Federalist.
Was:
> The Social and Behavioral Sciecnes team was the first adopter for Federalist.
To:
> The Social and Behavioral Sciences team was the first adopter for Federalist.

Spelling error for SBST

---

go

Since `git pull` has started stalling during automated deployment, these commands will hopefully solve the problem. Also obviates the need for `git stash`.
Inspired by: http://grimoire.ca/git/stop-using-git-pull-to-deploy
cc: @gboone

git stash, git pull => git fetch, git reset

---

go

Replacing the original `exec_cmd` with this:
```
def exec_cmd(cmd)
if !system(cmd)
puts "#{cmd}: #{$?}"
exit($?.exitstatus)
end
end
```
and refiring the webhook produced this:
```
Fetching from git
git fetch origin staging: pid 26648 SIGPIPE (signal 13)
```
Updating the `go` script on the server with this change and refiring the webhook appears to resolve the issue.
cc: @gboone

Redirect system() stderr to stdout

---

_posts/2014-12-18-a-complete-list-of-gov-domains.md

The data.gov permalink for .gov domains changed. This fixes it.
cc @hkdctol

Fix link to the Data.gov page for .gov domains

---

pages/index.html

This should one-and-hopefully-for-all fix the wierd IP-address-instead-of-hostname error we saw in staging and production. Yes, it was that simple. I have no idea why I never caught this before :frowning: :person_frowning: but apparently when you put a slash between `{{ site.baseurl }}` and `{{ post.url }}` it changes `baseurl` to the IP address. WTF, Jekyll!

removes the extra `/` on index line 96

---

README.md

Hi folks!  We're trying to help update documentation that references the `data-private` repo as that has been deprecated in favor of the `team-api.18f.gov` repo. I've created this PR to account for the changes needed in your documentation.
This changeset updates the reference to `data-private` in the README to be `team-api.18f.gov` due to recent changes in the Team API.  This is in reference to https://github.com/18F/team-api.18f.gov/issues/169
If you have any questions, please reach out to the practices team in the #hub Slack channel!

Update data-private reference in README

---

_plugins/dashboard.rb
pages/dashboard.html

use the permalink URL for dashboard index, and use the original (not downcased) project name in the permalink

dashboard links case fix

---

_plugins/author.rb

Removes the trailing slash on authors with outside URLs for their bios.

Fixes the trailing slash deal

---

go

This PR essentially deprecates the `production` branch. Since we're doing manual deploys to production and eventually moving the whole stack to 18F/federalist, that branch is redundant and only slows down our publication flow. Merging has no *immediate* effect but will allow us to skip the second pull request and just run the deployment script to rebuild production.

updates the production deploy to pull from the `staging` branch

---

_includes/newsletter.html

Changed the newsletter email input field to `type="email"` to improve
usability, particularly on mobile devices where it brings up the email
specific keyboard.
Discussed in issue: [https://github.com/18F/18f.gsa.gov/issues/1608](https://github.com/18F/18f.gsa.gov/issues/1608)

Changed newsletter email input to type='email'

---

pages/index.html

Minor markup update. Added </article> on line 63 within the "services" <section> because the <article> end tag was missing.

Added article end tag

---

_posts/2016-04-08-how-we-get-high-availability-with-elasticsearch-and-ruby-on-rails.md

This updates [the Elasticsearch post](https://18f.gsa.gov/2016/04/08/how-we-get-high-availability-with-elasticsearch-and-ruby-on-rails/) by @pkarman to fix the JSON syntax highlighting.
It changes this:
Into this:

Fix JSON formatting in ES post

---

_posts/2015-10-09-cloud-gov-launch.md
_posts/2015-11-13-answering-common-questions-about-cloud-gov.md

https://chat.18f.gov now supports linking directly to the channel! See https://github.com/18F/chat/pull/5 for more information.

link directly to the #devops-public chat room from the blog posts

---

_plugins/author.rb

A first stab at generating archives for authors who are not 18F team members.
Addresses #1637 by creating pages at /author/ for anybody who doesn't work for 18F but wrote a post on our blog. We're getting to the point where we've had many authors turn into guest authors simply because they left the team. Their names aren't linked and their posts are harder to find. That shouldn't be the case. It's harder for us to learn how many posts are being written by guest authors, and it's also hard for them to have an account of the words they wrote for us either as employees or fellow public servants.
Steps remaining:
1. I'm not happy with the copy on the generated pages. See the federalist preview for more context. Maybe we set up a different layout that puts the lists of posts up front and does …

Author archives

---

_includes/footer.html
assets/_sass/components/_blog.scss
pages/hire.md
pages/index.html

* Widens the breakpoint for where blog meta and post content get stacked instead of floated. 
* Adds a contact link to inquiries18f
* Adjusts the title for the "what we deliver" section

Mobile fixes

---

_includes/nav.html

Apparently the `/` is important. Without it we get a weird redirect to a page that doesn't exist. This should fix it!

Adds a trailing slash to the what-we-deliver link in nav

---

assets/_sass/_custom.scss

This PR addresses https://github.com/18F/18f.gsa.gov/issues/1704
Note: this is a short-term fix -- we need to go back and clean up and trim a lot of this CSS, but for now, this should fix the content fitting issue.
Before:
After:

fix header content bug

---

_posts/2016-05-13-how-18f-handles-information-security-and-third-party-applications.md

This does a few small things to our post on the Slack IG report:
* Updates the editor's note on when the post was last updated to include a link to the post's full revision history in GitHub, for transparency.
* Fixes a formatting typo in the Open Graph metadata, where two Markdown asterisks were accidentally left in.
* After "took further steps", adds "(described below)", so that it's more obvious that we shared those further steps later in the post.

An OG fix and a couple small improvements

---

_posts/2016-05-10-building-a-modern-shared-authentication-platform.md

gsa.gov doesn't support HTTPS yet, so this link is broken.

Fix broken gsa.gov link in identity post

---

_includes/newsletter.html

"Sign up to subscribe to our newsletter" is too long and spills over the button on mobile (320px). I think "Subscribe to our newsletter" adequately conveys the correct information to people, and also makes the button work for mobile. The alternative that I tried was reducing the font-size to 0.9em, but this is a better solution IMO.

Copy change for mobile optimization

---

Gemfile
Gemfile.lock

Not sure why there are three versions of this commit but the result is that Jekyll gets updated to 3.1.6, the latest and greatest Jekyll there is.
We're upgrading from 3.1.2 to 3.1.6, here are the blog posts for the current and intervening versions.
3.1.6: https://jekyllrb.com/news/2016/05/19/jekyll-3-1-6-released/
3.1.5: https://jekyllrb.com/news/2016/05/18/jekyll-3-1-5-released/
3.1.4: https://jekyllrb.com/news/2016/05/18/jekyll-3-1-4-released/
3.1.3: https://jekyllrb.com/news/2016/04/19/jekyll-3-1-3-released/

Jekyll update

---

_posts/2014-12-18-a-complete-list-of-gov-domains.md

This updates [A complete list of .gov domains](https://18f.gsa.gov/2014/12/18/a-complete-list-of-gov-domains/) to link to the new central permalink, created in https://github.com/GSA/data/pull/32 for the 2016-06-30 release. This ensures the blog post won't send people to outdated data.
I also updated the text slightly to not call the data outdated, and to link to the Data.gov page, which I still hope will become canonical.

Update a bunch of links to the .gov domain list to stay current

---

pages/code-of-conduct.md
pages/open-source-policy.md

The code of conduct and OSS policy both live in official GH repos. This change
points to the correct location for both and indicates how to suggest changes or
comment on those policies

Points to the correct location for policies

---

pages/home.html

It was causing some unicode errors on Android and not even separating lines so we got rid of it. Closes #1873

removes U+2028 : LINE SEPARATOR from `/`

---

_includes/newsletter.html

Addresses #1608 
If you're sent or click on 18f.gsa.gov/#newsletter you get taken to the bottom of the page. I don't know that this is our best ever solution for the newsletter sign up. Particularly, I think it'd be easy to misunderstand what you're supposed to do at the bottom of the page depending on the context that sent you there. We'll leave #1608 open until we can test this and/or design a better interaction.

Puts the newsletter link back

---

.eslintignore
.eslintrc.yml
.hound.yml
.rubocop.yml
.scss-lint.yml

For #1878, #1879 
This PR adds HoundCI and the linters that it references. Specifically, it adds:
- [eslint](http://eslint.org/) for JavaScript
- scss-lint for SCSS, using the [frontend guild's standard set of rules](https://pages.18f.gov/frontend/#css-linting). The frontend guild has made slight modifications to Airbnb's [styleguide](https://github.com/airbnb/css)
- rubocop for Ruby, using the [18F development guide](https://github.com/18F/development-guide/tree/master/ruby) as a reference
cc @gboone

Adds HoundCI and associated linters

---

_posts/2016-09-20-mississippi-agile-modular-techniques-child-welfare-system.md

Change to `Mississippi's Department of Child Protection Services`, instead of `Mississippi's Department of Child Protective Services`

Correct name of Mississippi department

---

_includes/head.html

For #1929 
This PR removes the Ethnio activation code. It should no longer pop up when users visit the site!
cc @gboone

Removed ethnio 

---

CONTRIBUTING.md
Gemfile
Gemfile.lock
LICENSE.md
README.md
build

⚠️ WIP
For #1914 
@mugizico I forgot that I had started doing this work. Here it is for reference.

Serve script documentation

---

ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

For #1933 
This PR makes templates for new issues and pull request templates. These templates will populate the content field when an issue or pull request is made. 
The issue for this PR says to add 'associated documentation', but I'm not sure where that would go, as it is fairly self-evident.

Issue and pull request templates

---

Dockerfile
README.md
docker-compose.yml
docker_entrypoint.rb
serve

[WIP] and update to https://github.com/18F/18f.gsa.gov/pull/1688
* Based on this  [Gitlab forum post](https://gitlab.com/gitlab-org/gitlab-ce/issues/14983) added UTF-8 language support in `Dockerfile`  to fix `jekyll 3.3.0 | Error:  invalid byte sequence in US-ASCII`  but it doesn't seem to work. I am thinking that it has to do with bundler version discrepancies. 
cc @gboone @gemfarmer @toolness

Docker support(Update)

---

circle.yml

Per or discussion in retro, this PR will prevent Circle CI from running accessibility scanning.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/disable-pa11y-ci.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/disable-pa11y-ci)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/disable-pa11y-ci/)
- disables the pa11i-ci build on CircleCI

temporarily disable pa11y-ci

---

pages/press.html

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/analytics-link.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/analytics-link)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/analytics-link/)
- Link to list of forks of analytics.usa.gov. It's better to keep the canonical list with the project anyway, so we don't need to update in two places.
/cc @konklone

link to list of forks of analytics.usa.gov

---

_includes/footer/desktop.html
_includes/footer/mobile.html
pages/vulnerability-disclosure-policy.md

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/vulnerability-disclosure-policy.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/vulnerability-disclosure-policy)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/vulnerability-disclosure-policy/)
- Adds 18F's and TTs' [vulnerability disclosure policy](https://github.com/18F/vulnerability-disclosure-policy) to the main 18F site. It's structured similarly to the [open source policy page](https://18f.gsa.gov/open-source-policy), where we copy the document from the repo into the site, and link at the top to the GitHub repository as the official/canonical location.
- Updates the footer links in the mobile and desktop views to add a `Vulnerability disclosure` …

Adds 18F's and TTS' vulnerability disclosure policy

---

_authors/aaron.md
_authors/alison.md
_authors/david.md
_authors/dmayercantu.md
_authors/erica.md
_authors/garren.md
_authors/gramirez.md
_authors/greg.md
_authors/jackie.md
_authors/joe.md
_authors/kara.md
_authors/majma.md
_authors/mbland.md
_authors/melody.md
_authors/michael-walker.md
_authors/ozzy.md
_authors/robert.md
_authors/russ.md
_authors/sarah.md
_authors/sean.md
_authors/shashank.md
_authors/vdavez.md
_layouts/default-profile.html
_plugins/author.rb
_posts/2015-02-18-steve-portigal-pre-event-qa-post.md

Fixes issue(s) #1987 and #1637 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/frontmatter-fixes.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/frontmatter-fixes)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/frontmatter-fixes/)
- Adds `alumni: true` for many 18F alumni
- Adds author yml files for several 18F alumni who were missing them, which makes their archive pages work
- Minor capitalization fix
- Adds Dave's first name
- Changes a `'` to a `’` in `author.rb`
/cc @gboone

Alumni author pages

---

Gemfile
Gemfile.lock

Fixes issue(s) #1947 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/tag-bug-2.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/tag-bug-2)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/tag-bug-2/)
- references changes made on 18F/jekyll-archives
- replaces all dashes in archive tags
/cc @coreycaitlin @awfrancisco

Update Gemfile to use 18f/jekyll-archives

---

Gemfile.lock
_layouts/default-profile.html
_layouts/tag-results.html
_plugins/README.md
_plugins/matching_posts.rb

Fixes issue(s) #1989 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/authors-page.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/authors-page)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/authors-page/)
- updates the `match_posts` filter to allow for multiple kinds of page to post matching
- updates the author page rollup to include new tag-rollup layout
- centers the tag page
/cc @mugizico @coreycaitlin

Update author page rollup

---

pages/vulnerability-disclosure-policy.md

- change capitalization to "vulnerability disclosure policy"
Per @konklone, this policy is not a proper noun and should be lower case in all instances.

Change capitalization

---

_config.yml
pages/quote-example.md

Fixes issue(s) #2007 .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/smart-quotes.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/smart-quotes)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/smart-quotes/quotes)
- adds `quotes` extension to render smart quotes
- adds `/quotes` page for testing(remove when merging)
/cc  @coreycaitlin

add smart extension

---

_includes/head.html
_sass/_components/tag-index.scss

Fixes issue(s) #2032 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/deprecate-description.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/deprecate-description)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/deprecate-description/)
- Change which item we're pulling into the page `head` element: it now uses `excerpt` instead of `description`
/cc @gemfarmer

Use excerpt instead of description in header

---

_posts/2016-02-19-how-and-why-we-built-the-micro-purchase-platform.md

The image will still be used as the share graphic, but not as a banner above the post.
😎 [Preview](https://federalist.18f.gov/preview/18f/18f.gsa.gov/hero-remove/2016/02/19/how-and-why-we-built-the-micropurchase-platform/)
cc @18F/blog

Removes a not-great looking hero image

---

_layouts/project-tag-results.html
_projects/fec-gov.md
_sass/_components/tag-index.scss
pages/home.html

Fixes issue(s) #2052 to match mocks mentioned in #2016 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-pg-tweaks.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-pg-tweaks)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/project-pg-tweaks/)
- Changes spacing around the title element
- Moves `Project:` into the template itself and forces a line break after it
/cc @gemfarmer

Style tweaks to the project page hero

---

_config.yml
_data/navigation.yml

Temporarily remove menu accordion, subnav, so we can push to master. Continue this work on another branch
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/temporarily-hide-hire-subpages.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/temporarily-hide-hire-subpages)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/temporarily-hide-hire-subpages/)

Remove hire menu accorion, subnav

---

_config.yml
pages/hire.md

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/hide-hire-pages.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/hide-hire-pages)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/hide-hire-pages/)
- prevents `/hire/partnership-playbook/` and subpages

Temporarily exclude partnership playbook pages

---

_config.yml

Adds a version to the config file so that we can keep track of what version the code is at. I started at `v1.1.0` thinking that we were probably at `v1.0.0` when the current team started in October. Does this seem like an appropriate version?
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/version.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/version)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/version/)
/cc @gboone

Add version to config (v1.1.1)

---

pages/hire.md

The 'hire' page is missing an image in `dev` and `master`. This updates the layout so that it exists!
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/hire-image.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/hire-image)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/hire-image/)

Reintroduce 'hire' image

---

_config.yml
_plugins/redcarpet.rb
_sass/_core/syntax-highlighting.scss
assets/css/main.scss

Fixes issue(s) #2083 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/codeblocks.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/codeblocks)
[:sunglasses: PREVIEW 1](https://federalist.18f.gov/preview/18F/18f.gsa.gov/codeblocks/2016/10/04/what-is-static-source-analysis/)
[:sunglasses: PREVIEW 2](https://federalist.18f.gov/preview/18F/18f.gsa.gov/codeblocks/2016/06/24/5-lessons-in-object-oriented-design-from-sandi-metz/)
[:sunglasses: PREVIEW 3](https://federalist.18f.gov/preview/18F/18f.gsa.gov/codeblocks/2016/04/08/how-we-get-high-availability-with-elasticsearch-and-ruby-on-rails/)
- continues to extend redcarpet by using rouge's `block_code` block-level syntax highlighting function
- Added a stylesheet, …

Adds support for syntax highlighted code blocks

---

pages/hire.md

Fixes the hire page part of #2067 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/hire-rewrite.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/hire-rewrite)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/hire-rewrite/)
- Edit the content to focus on the essentials, with a more welcoming tone
- Tell people who they're contacting — in this case, @d-kenny 
- Include more default behavior in the `mailto` link, including subject and a template for body text
- Add a button
/cc @gemfarmer @gboone

Revised "Hire 18F" content

---

_projects/hhs-states.md
pages/what-we-deliver.md

Fixes issue(s) #2069 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-intros.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-intros)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/project-intros/)
- Revise the HHS project intro to include the words "acquisition" and "monolithic"
- Change project links on `What we deliver` to go to project pages 🎉 
/cc @gemfarmer

Add project-page links to what we deliver, revise HHS intro

---

circle.yml

- Chain `accesslint-ci` command with `jekyll serve`.
- Fixes blank accesslint results by waiting for jekyll server to finish starting.
cc @gemfarmer 
[Fixes https://github.com/accesslint/accesslint-ci/issues/39]

Fix accesslint scanning by chaining with jekyll server

---

Gemfile
Gemfile.lock
_config-blog.yml
circle.yml
package.json
serve-accesslint

18F version of PR #2133, submitted by @ckundo 👏 
The CircleCI tokens mentioned have been added to the repo settings, so we should receive comments on this PR 🙏 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/serve-accesslint.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/serve-accesslint)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/serve-accesslint/)
/cc @ckundo, @gboone 
<hr />
> - Install accesslint-ci and accesslint-cli.
> - Update _config-blog.yml by running `ruby config_blog.rb`.
> - Define a `serve-accesslint` script.
> - Use config-blog.yml to only serve the 3 most recent posts.
> - Compare errors with the most recent successful build of `dev` branch.
>
> AccessLint will fail unless you set these ENV variables (in your [Circle …

Serve accesslint

---

_sass/_components/layout.scss
_sass/_core/typography.scss

Fixes issue(s) #2084 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/anti-anti-aliasing.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/anti-anti-aliasing)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/anti-anti-aliasing/)
- Removed `antialiased` from body
- Added `antialiased` to `.background-dark` 
/cc @maya @coreycaitlin

Removed anti-aliasing from body

---

_posts/2016-03-29-best-practices-for-building-an-accessible-website-using-the-draft-us-web-design-standards.md
_posts/2016-04-06-take-our-code-18f-projects-you-can-reuse.md
_posts/2016-05-03-delivering-the-next-generation-of-digital-government.md
_posts/2016-05-06-the-day-90-kids-came-to-code-with-18f.md
_posts/2016-05-10-gsa-invests-in-18fs-work-with-new-service.md
_posts/2016-05-23-a-sestina-on-sunsetting-content.md
_posts/2016-07-13-technology-transformation-services-looking-for-new-commissioner.md
_posts/2016-07-14-elaine-kamlley-a-developer-commited-diversity.md

Follow-up to blockquote fixes — this is the result of my spot-checking the last year or so of blog posts for markdown issues.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/blog-fixes.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/blog-fixes)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/blog-fixes/)
/cc @gemfarmer

Blog spot-fixes for markdown

---

.codeclimate.yml
.eslintrc
README.md

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/codeclimate.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/codeclimate)
- adds a badge to the README that tracks the code climate for this repo
- adds a .codeclimate.yml` configuration file so that codeclimate works on this repo
- updates the `eslintrc.yml` file to include current syntax
This doesn't need to be in the README (in my opinion), but to run codeclimate locally, you need to install Docker, Docker Machine, and run the [codeclimate CLI](https://github.com/codeclimate/codeclimate#prerequisites) through a docker image. The `analyze` command is [where the magic happens](https://github.com/codeclimate/codeclimate#usage):
```bash
docker run \ …
```

Adds codeclimate monitor

---

_layouts/project-tag-results.html
_posts/2016-07-06-illinois-fourth-grade-class-uses-every-kid-in-a-park-to-explore.md
_projects/doi-every-kid-in-a-park.md
_projects/ed-college-scorecard.md
_projects/fec-gov.md
_projects/hhs-states.md
_sass/_components/tag-index.scss
_sass/_core/variables.scss
pages/how-we-work.md
pages/what-we-deliver.md
tests/schema/_projects.yml

Fixes issue(s) #2104 and #2105 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/new-project-intros.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/new-project-intros)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/new-project-intros/)
- Add College Scorecard and EKIP project intros as markdown files
- Add `agency` attribute to project intro frontmatter
- Add links from `What we deliver` to College Scorecard — and, bonus!, to the Climate Discovery report
- Simplify and improve hero image style on project intro pages
/cc @awfrancisco @gemfarmer @austinhernandez

New project intros and layout refinements

---

_config.yml

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/removes-version.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/removes-version)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/removes-version/)
- Removes the version number in the `_config.yml` so that we no longer confuse people with the wrong version

Remove version number

---

_includes/navigation/footer-desktop.html
_includes/navigation/footer-mobile.html

Fixes issue(s) #2220 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/github-link.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/github-link)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/github-link/)
- Remove `edit on GitHub` link
- Replace with `File an issue` link that opens a new issue in this repo
/cc @maya @gboone

better GitHub link

---

_includes/card.html

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/card-navigation.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/card-navigation)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/card-navigation/)
- add `site.baseurl` to outer card link

Add baseurl to project cards

---

Gemfile
Gemfile.lock
_includes/card.html
_includes/javascript.html
_plugins/jekyll_asset_pipeline.rb
_sass/_components/sticky.scss
assets/css/main.scss
assets/js/jekyll-pages-api-search.js
assets/js/sticky.js

Fixes issue(s) #324 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/jekyll-asset-pipeline.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/jekyll-asset-pipeline)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/jekyll-asset-pipeline/)
- Adds [`jekyll-asset-pipeline`](https://github.com/matthodan/jekyll-asset-pipeline) to bundle JS
- Adds sticky JS script from [`18F/stickyfill`](https://github.com/18F/stickyfill) to create site stickies
Elements can be made sticky by adding a `class="sticky"` to them 😄 

Adds jekyll asset pipeline, site sticky

---

_includes/tag-results.html

Fixes issue(s) #2192 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/image-focus.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/image-focus)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/image-focus/)
- Reduces the size of the focus box around post preview images
- Removes the link surrounding the image from the tab order. It is redundant (there are already two other links to 'Continue to post') and comes before the title of the post.

Make focus box for post image smaller

---

_layouts/project-tag-results.html
_sass/_components/section-info.scss

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-bugs.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/project-bugs)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/project-bugs/)
- Changed text `Github` to `GitHub`
- Removed unnecessary styles causing a subtle bug in the meta content chunk

Remove a few project pages bugs

---

_posts/2016-06-15-two-agencies-participating-in-the-digital-acquisition-accelerator-pilot.md
_posts/2016-06-21-using-plain-language-to-bridge-the-gap-between-government-and-industry.md
_posts/2016-10-25-three-small-steps-you-can-take-to-reboot-agile-in-your-organization.md
_posts/2017-01-05-building-effective-agile-partnership-between-government-industry.md

- adds the `agency work` tag to a couple posts that should have it
/cc @coreycaitlin @gboone

Add agency work tag

---

_data/navigation.yml
_layouts/project-tag-results.html

Fixes issue(s) #2276 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/active-nav.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/active-nav)
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/18f.gsa.gov/active-nav/project/fec-gov/)
- Ensures that the `what-we-deliver` nav item is active when a user is on any of the project pages
- Changed breadcrumb link from  `how-we-work` to `what-we-deliver`

highlight what-we-deliver nav heading

---

_about/index.md
_includes/banner-cta.html
_layouts/default-intro.html
_layouts/project-tag-results.html
_sass/_components/layout.scss

What I am trying to edit above: 
This adds a generic call to action banner to the site.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/page-footers.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/page-footers)
[:sunglasses: PREVIEW project](https://federalist.18f.gov/preview/18F/18f.gsa.gov/page-footers/project/fec-gov)
[:sunglasses: PREVIEW about](https://federalist.18f.gov/preview/18F/18f.gsa.gov/page-footers/about)
- adds a `$medium` background banner that can be added to `profile-intro` layouts by adding the `banner_cta: true` to the fronmatter
- adds it by default on the project page layout

Adds generic call to action banner

---

_posts/2016-02-12-happy-valentines-day-from-18F.md

Since we dropped the `card` collection and the layout that generated the Twitter cards, all the links now 404. If this is something we want to support again in the future we should make an issue for it.
The way the `card` collection worked was to generate pages that could be read into Twitter effectively creating multiple custom share messages for the same blog post.
cc @18F/blog

Takes out the twitter share links

---

_posts/2015-03-17-does-18f-pass-the-bechdel-test-for-tech.md
_posts/2015-04-01-govtechhack-hacking-for-civic-improvement.md
_posts/2015-07-08-openfec-api.md

Removes an old link to the dashboard, which no longer works. It doesn't seem to affect meaning/sense at all.
/cc @gboone or @awfrancisco

remove broken dashboard links

---

_about/index.md
_authors/jameshupp.md
_data/navigation.yml
_includes/navigation.html
_includes/navigation/subnav.html

Fixes issue(s) #2127 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/in-page-nav.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/in-page-nav)
[:sunglasses: PREVIEW]https://federalist.18f.gov/preview/18F/18f.gsa.gov/in-page-nav/)
- Adds the `nav_items` attribute to the About page frontmatter, as an example of how to add navigation on a localized level

In page nav items

---

_data/navigation.yml
_projects/calc.md
_projects/eregs.md
pages/contact.md
pages/what-we-deliver.md

This has a few edits suggested in review:
- moves the "email us" button to the main content area
- removes "with agencies" from the "what we deliver" intro, because we already said "support agencies" in the prior sentence
- switches up a few placeholder project images for variety
- change nav order so `Contact` is in the upper-right
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/edits-from-slack.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/edits-from-slack)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/edits-from-slack/)
/cc @gboone

minor image and copy edits

---

Gemfile
Gemfile.lock

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/upgrade-jekyll_oembed.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/upgrade-jekyll_oembed)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/upgrade-jekyll_oembed/)
- upgrades `jekyll_oembed` to `0.0.3`
- This is important because previously, private (or otherwise blocked) URLs would fail a build. `0.0.3` fails silently, which is good, in this case.
/cc @gboone

Upgrade jekyll_oembed to v0.0.3

---

404.html
_config-accesslint.yml
_config-blog.yml
_config-fast-builds.yml
_config.yml
circle.yml

Replaces #2321 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/restore-accesslint.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/restore-accesslint)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/restore-accesslint/)
- adds a new page `404.html` that will only be served with the `./serve-accesslint` command
- Before this is merged I need to make sure that when Federalist serves the correct 404 page.
/cc @gboone @ckundo

Restore accesslint

---

Gemfile
Gemfile.lock
_posts/2014-05-19-packaging-up-api-usability-testing-for-agency-re-use.md
_projects/c2.md
tests/schema/_authors.yml
tests/schema/_posts.yml
tests/schema/_projects.yml
tests/schema/_test_collection.yml
tests/schema/rules.yml

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/jekyll_fm_redux.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/jekyll_fm_redux)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/jekyll_fm_redux/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/jekyll_fm_redux/README.md)
- updates the `jekyll_frontmatter_tests` gem to `v0.1.0`
- updates frontmatter formatting
/cc @gboone

Update frontmatter tests

---

README.md

This updates the documentation in the README so that users have an easier time finding the style guide.
**New text:**
> > 18f.gsa.gov extends the [U.S. Web Design Standards](https://standards.usa.gov/) and [18F Brand guidelines](https://pages.18f.gov/brand/) to create a style that is professional, unique, and informative. The style guide, located at [18f.gsa.gov/styleguide/](https://18f.gsa.gov/styleguide/) documents the patterns and components used to create this theme.
> 
> > [View style guide](https://18f.gsa.gov/styleguide/)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/gemfarmer-styleguide-readme/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/gemfarmer-styleguide-readme/README.md)
/cc @gboone

Update Readme to better link to styleguide

---

pages/developer.md

team-api is deprecated :pour-one-out:, link on this page 404s
have not heard of any plans to revive it
Fixes issue(s) #2381.
- Remove entire section referencing Team API.
-
-

remove team-api

---

_includes/open-positions.html
_join/job-listings/product-manager.md
_join/open-positions/position-title.md
_join/open-positions/product-manager.md

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/unlisting.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/unlisting)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/unlisting/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/unlisting/README.md)
- Unlists the product manager job description (because it's closed now)
/cc @hestherchang

Unlists the Product Manager postiion (it's closed)

---

_layouts/styleguide.html
_plugins/README.md
_projects/doi-every-kid-in-a-park.md
_styleguide/index.md
_styleguide/subpages/for-developers.md

Updates to `sg-5`
- rename "using jekyll" to 'for developers". 
- rename "introduction" to 'overview". 
- added some text to overview
cc @elainekamlley

Brian changes to sg-5

---

_includes/open-positions.html
_join/open-positions/acquisition-technical-lead.md

Fixes issue(s) #2431 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-title-links.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-title-links/)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/job-title-links/join/)
- Add `Innovation Specialist — ` to the beginning of the link text
- Add a couple of sentences attempting to explain why people might see multiple postings for "Innovation Specialist" roles
/cc @hestherchang @amandaschonfeld

Clarify job title link

---

_posts/2016-10-04-what-is-static-source-analysis.md

This example doesn't make sense without having all children nested under the top line. I confirmed with @mgwalker that this is a bug. I also standardized the ellipses.
-indent all lines of code
-replace ellipsis character with three periods

Correct an error in faux-code indentation

---

_join/job-listings/acq-gs-15.md
_join/open-positions/acquisition-technical-lead.md

I spent a bit more time with @hestherchang and @amandaschonfeld, working through some minor information architecture tweaks to try to reduce candidate confusion. We used the no-longer-live Acq. Technical Lead as a sample, but I set it back to `published: false` before pushing, so you'd need to pull it down locally and change that to preview the subnav on the job description page.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-listing-tweaks.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-listing-tweaks)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/job-listing-tweaks/)
- Tweak headers and breadcrumbs for job posting
- Add sample subnav for job posting (see GS-15 Technical Lead posting) …

Add subnav to job posting as example, tweak IA

---

_includes/header.html
_includes/navigation/footer-desktop.html

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/capitalize-f.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/capitalize-f/)
- image path correction

Correction: Capitalize F in 18f logo image path

---

CONTRIBUTING.md

Per https://github.com/18F/18f.gsa.gov/pull/2460#issuecomment-311119942
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/clarify-fork.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/clarify-fork)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/clarify-fork/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/clarify-fork/README.md)
- Tell 18F team members not to fork the repo, but instead create a branch.

Tell people not to submit a PR from a fork

---

_join/index.md

Fixes issue(s) #2439 .
- Add information about federal employee salaries being public information.
- Add a link to federalpay.org as an example. 
/cc @elainekamlley @coreycaitlin @commit-dkp

Add info on public nature of fed salaries

---

_join/position-no-longer-available.md

Fixes issue(s) #2425  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/pd-redirects.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/pd-redirects)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/pd-redirects/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/pd-redirects/README.md)
- Created page to notify users a job position is no longer available 
- Added expired job postings to redirect front matter

Redirect page for positions no longer available 

---

_join/open-positions/front-end-design-intern.md
_join/open-positions/service-visual-design-intern.md
_join/position-no-longer-available.md
_styleguide/subpages/for-developers.md

**To be merged COB 8/2** 
Fixes issue(s) #2479  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/expired-pd.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/expired-pd)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/expired-pd/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/expired-pd/README.md)
- removes internship posting
- fixes URL in styleguide 

Removing expired job posting and URL fix

---

_join/open-positions/talent-acquisition-specialist.md
_join/open-positions/talent-engagement-lead.md
_join/open-positions/talent-engagement-specialist.md
_join/position-no-longer-available.md

To me merged at 9:00 PM ET. 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-takedown.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-takedown)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/job-takedown/)
- Removing talent job descriptions 
/cc @rooneywp

Removes Talent positions from join page

---

pages/vulnerability-disclosure-policy.md

Pulled content on https://github.com/18F/vulnerability-disclosure-policy into the 18f.gsa.gov page.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/wslack-update-vul.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/wslack-update-vul)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/wslack-update-vul/)

updating the vul policy with the latest

---

_posts/2015-09-15-federalist-platform-launch.md

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/wslack-add-blurb.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/wslack-add-blurb)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/wslack-add-blurb/2015/09/15/federalist-platform-launch/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/wslack-add-blurb/README.md)
- adds a blurb to an old blog post

add a blurb to old blog post that Federalist is open for business

---

_includes/open-positions.html
_join/open-positions/acquisition-technical-lead-gs14.md
_join/open-positions/acquisition-technical-lead-gs15.md
_join/position-no-longer-available.md

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/acq-jobs-takedown.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/acq-jobs-takedown)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/acq-jobs-takedown/)
- Removes Acq Tech Lead positions
- Added newsletter link when there are no open positions

Removes acq tech lead positions

---

_join/open-positions/opp-feedback-analytics-engineer.md
_join/position-no-longer-available.md

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-takedown.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/job-takedown)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/job-takedown/)
- OPP Feedback analytics engineer position is now closed. Removing post

Remove OPP engineer position

---

_principles/index.md

Emphasize the important role that product owners need to play in our engagements. Remove ambiguities between product management and agile. Removed references to part time commitments.
Two specific changes that may need clarification:
1. I'm taking out the reference to time commitment from the PO and replacing it with what the PO needs to do in order to set the project up for success. 15-20 hours per week does not accurately account for the dedication to [product work that we are finding is necessary in our projects](https://breathepublication.com/product-for-president-59580e3b554c). Instead, I am recommending we talk about what we expect the product owner to be doing. If the partner cannot take on that responsibility, it will be a risk to the project, and they should be aware of this as …

Update to language around product owner

---

Gemfile

Using 2.3.3, I was able to successfully build and run. This allows Ruby v2.3.1 to 2.3.99 to work also.

Allow more than just Ruby 2.3.1

---

_projects/fec-gov.md

Fixes issue(s) #2594  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/beta-fec.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/beta-fec)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/beta-fec/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/beta-fec/README.md)
- Change FEC project page to FEC.gov from beta.fec.gov
- Updates FEC repo to active repo

Remove beta from FEC project page

---

_projects/dod-military-onesource.md
_projects/doi-every-kid-in-a-park.md
_projects/micro-purchase-marketplace.md
_projects/navy-reserve.md
_projects/treasury-new-ten.md
pages/what-we-deliver.md

Fixes issue #2620.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/retire-project-pages.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/retire-project-pages)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/retire-project-pages/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/retire-project-pages/README.md)
**Changes proposed in this pull request:**
Retires project pages for:
- Military One Source
- Every Kid in a Park
- Micro-purchase marketplace
- Ready-2-Serve
- The New Ten
Adds redirects for those pages to /what-we-deliver/

Retire some project pages

---

_layouts/styleguide.html
_posts/2015-04-28-intersection-of-art-and-technology.md
_posts/2015-05-27-dan-brown-conflict-in-design.md
_posts/2016-09-19-vendors-government-strengthen-partnership-technology-industry-day.md
_styleguide/subpages/blog-components.md

Fixes issue(s) #2629 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/ombed-fx.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/ombed-fx)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/ombed-fx/)
- oembed is a unpredictable. Removing the instructions from style guide. Will use `<iframe>` for any videos or tweet moving forward
- removed oembed and replaced it with iframe
- removed unavailable videos

Removed oembed videos and instructions on style guide

---

_posts/2015-02-26-Five-Ways-To-Turn-A-Bad-Idea-Into-A-Great-One.md
_posts/2015-04-03-how-to-welcome-new-coders-to-a-civic-hackathon.md
_posts/2015-07-15-openfec-api-update.md

Fixes issue(s) #2640.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/storify.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/storify)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/storify/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/storify/README.md)
- Remove links to Storify from 3 blog posts
cc @elainekamlley

Remove storify links

---

pages/contact.md

Fixes issue(s) #2623.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/contact-sidebar.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/contact-sidebar)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/contact-sidebar/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/contact-sidebar/README.md)
- Add new paragraph to sidebar of Contact page that links to Join 18F page and the JoinTTS email.

Add sidebar to Contact that links to Join

---

_about/index.md
_data/navigation.yml

Fixes issue(s) #2646 .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/about.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/about)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/about/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/about/README.md)
- removed `18F` in the `nav` and `/about` page

Removing '18F' from 'About 18F'

---

_includes/banner-cta.html

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/contact-b.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/contact-b)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/contact-b/)
- Makes all call to action consistent to say `Contact us`

Changed banner call to action to say Contact us

---

_posts/2018-02-22-new-home-for-the-federal-plain-language-community.md

To help out @nicoleslaw - she tweeted out the link to the blog post's original URL and it's currently a 404. This redirects the outdated URL to the correct one.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/hursey013-patch-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/hursey013-patch-1)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/hursey013-patch-1/)

Add redirect for previous blog post URL

---

_includes/side-cta.html
_layouts/project-page.html
_products_projects/cloud-gov.md
_products_projects/federalist.md
_products_projects/micro-purchase-marketplace.md
_sass/_core/utility.scss
_services_projects/c2.md
_services_projects/calc.md
_services_projects/dol-wage-and-hour.md
_services_projects/ed-college-scorecard.md
_services_projects/fbi-crime-data-explorer.md
_services_projects/fec-gov.md
_services_projects/forest-service.md
_services_projects/nsf-seedfund.md
_services_projects/us-web-design-standards.md
tests/schema/products_projects.yml
tests/schema/services_projects.yml

Fixes issue(s) #2645  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/moar-repos.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/moar-repos)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/moar-repos/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/moar-repos/README.md)
- Now able to add multiple repost
- Github repos links now have to be in markdown
- Added additional margins to call to action 

Reconfigured side bar in project pages to include multiple GitHub repos

---

_includes/card-project.html
pages/what-we-deliver.md

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/p-cards.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/p-cards)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/p-cards/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/p-cards/README.md)
- Updated the project card includes to use title and agency as headers

Makes all project cards consistent to use agency name and title as headers

---

pages/vulnerability-disclosure-policy.md

This syncs the VDP with the latest from its source GitHub repository.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/sync-vdp.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/sync-vdp)
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/sync-vdp/)
/cc @jacobian

Sync with up current vuln disclosure policy

---

_includes/head.html

Fixes issue(s) #2682  .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/favicon.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/favicon)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/favicon)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/favicon/README.md)
- Adds desktop favicon

Favicon fix

---

_layouts/styleguide.html
_styleguide/subpages/images.md
_styleguide/subpages/layout.md
examples/project-template.md

Fixes issue(s) #2660
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/docu-wha.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/docu-wha)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/docu-wha/styleguide/#project-page-template)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/docu-wha/README.md)
- Updated project page template documentation style guide 

Revised project page documentation on style guide

---

_layouts/styleguide.html
_styleguide/subpages/components.md
_styleguide/subpages/layout.md

Fixes issue(s) #2698 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/docu-hww.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/docu-hww)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/docu-hww/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/docu-hww/README.md)
- Adds documentation of testimonials to components section
- Adds a section about `how-we-work` layout under primary layout 

Adds documentation on testimonials and how we work page to the style guide

---

_includes/breadcrumb.html

Fixes issue(s) #2720 
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/breadcrumbs.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/breadcrumbs)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/breadcrumbs/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/breadcrumbs/README.md)
- Changes breadcrumbs to include agency name instead of title of page
From: 
To: 

Updates breadcrumb to include agency name

---

pages/developer.md

Remove link to https://18f.gsa.gov/hub/api/ since this service no longer exists

remove broken link to https://18f.gsa.gov/hub/api/

---

_posts/2014-12-18-a-complete-list-of-gov-domains.md

This fixes a couple of broken links to the CSV of .gov domains (we switched branches from `gh-pages` to `master`), moves some links to `https://` where we can, and it removes an outdated note about the intended landing place of the .gov domain data. (It's now ending up at home.dotgov.gov/data/, not at data.gov.)
/cc @h-m-f-t

In .gov domain post: fixing broken links, using HTTPS, removing interim text

---

assets/js/jekyll-pages-api-search.js

Fixes issue(s) # #2777
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/do_not_display_blank_results_in_search.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/do_not_display_blank_results_in_search)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/do_not_display_blank_results_in_search/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/do_not_display_blank_results_in_search/README.md)
-
-
-
Checklist:

when search results are blank, do not show in results page

---

assets/js/jekyll-pages-api-search.js

Fixes issue(s) #2775
Did not previously merge in correctly
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/hide_loading_bar.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/hide_loading_bar)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/hide_loading_bar/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/hide_loading_bar/README.md)
-
-
-
Checklist:

hide loading bar after search completes

---

_join/index.md

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/addstratandvisroles.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/addstratandvisroles)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/addstratandvisroles/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/addstratandvisroles/README.md)
- roles ready to be merged on Monday.  Can move forward with tweeting about virtual design role.  Should make an announcement about virtual location option

added strategist & visual design roles to Open positions

---

ISSUE_TEMPLATE.md

Just a very small change — I noticed the word "is" was in there twice by accident, so I figured I'd submit a PR to address it. 🙂
- Remove a likely typo/extra word
(I deleted most of the PR template fields here as they look like they're not so relevant for this PR)

Remove extra word

---

_about/index.md

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/add-iaa-link.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/add-iaa-link)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/add-iaa-link/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/add-iaa-link/README.md)
- Remove old IAA page link
- Replace with new link about IAA from Treasury

Replace IAA page link in About page

---

_posts/2018-08-15-shared-infrastructure-as-code.md

Turns out `dig` is not the nicest acronym, and the `host` output is more self-explanatory anyway.

switch `dig` for `host`

---

_posts/2018-08-09-etl-extract-transform-learn.md

- Reading https://18f.gsa.gov/2018/08/09/etl-extract-transform-learn/ I noticed a typo (repeated "the" twice) in the "Transform modestly" section. This PR simply fixes the typo.

fix repeated "the" typo on https://18f.gsa.gov/2018/08/09/etl-extract-transform-learn/

---

_includes/post.html
_layouts/post.html

Fixes issue(s) #2800 .
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/hide_date_in_related_blog_posts_section.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/hide_date_in_related_blog_posts_section)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/hide_date_in_related_blog_posts_section/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/hide_date_in_related_blog_posts_section/README.md)
-
-
-
Checklist:
/cc @Dahianna

hide date from Related blog posts section

---

_posts/2018-10-09-implementing-rules-without-rules-engines.md

Although there may be a good reason to point to tag fixed in time, generally people want to see that latest production work.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/pdb/rules-engine-patch-1.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/pdb/rules-engine-patch-1)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/pdb/rules-engine-patch-1/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/pdb/rules-engine-patch-1/README.md)
- Change url to point to master instead of tree in github
-
-
Checklist:

Point to master branch of data-act-broker-backend

---

_config.yml

Fix the error message when running tests.
`Liquid Exception: Liquid syntax error (line 30): Unknown tag 'jekyll_pages_api_search_load' in /_layouts/default.html`
`Liquid Exception: Liquid syntax error (line 71): Unknown tag 'oembed' in /Users/eddie/Code/18f.gsa.gov/_posts/2014-05-14-hacking-bureaucracy-improving-hiring-and-software.md`
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/include_gems_when_building_test_to_pass_test.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/include_gems_when_building_test_to_pass_test)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/include_gems_when_building_test_to_pass_test/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/include_gems_when_building_test_to_pass_test/R …

added gems to _config so they are detected when we run tests

---

_posts/2016-04-20-a-clear-audience-makes-for-a-good-blog-post.md

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-3.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/awfrancisco-patch-3)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/awfrancisco-patch-3/2016/04/20/a-clear-audience-makes-for-a-good-blog-post/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/awfrancisco-patch-3/README.md)
- Change links from old blogging guide to current handbook pages
@Dahianna

Fix blogging guide links

---

_layouts/tag-results.html

Fixes issue(s) #2899.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/add_color_to_tag_header.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/add_color_to_tag_header)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/add_color_to_tag_header/tags/modular-contracting/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/add_color_to_tag_header/README.md)
- Changed color of header to dark blue in tags page

Use dark header when showing tags page

---

_includes/head.html

Fixes issue(s) https://github.com/18F/18f.gsa.gov/issues/2942
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/add_social_image.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/add_social_image)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/add_social_image/)
- Added default image to Twitter card

Add image to twitter card

---

_join/index.md

Change from 2017 General Schedule (GS) Salary Calculator to 2018.
- Update the Join page's salary calculator link from the [2017 version](https://www.opm.gov/policy-data-oversight/pay-leave/salaries-wages/2017/general-schedule-gs-salary-calculator/) to [the current version](https://www.opm.gov/policy-data-oversight/pay-leave/salaries-wages/2018/general-schedule-gs-salary-calculator/).
/cc @ctro

Update to use current GS salary calculator

---

_posts/2019-03-19-18F-5-Anniversary-achieve.md

* Tying Federalist to cloud.gov makes the amount of impact clearer
* cloud.gov is definitely _not as good_ at helping out with legacy systems; better not to use that word!

Adjust cloud.gov description

---

Gemfile
Gemfile.lock

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/downgrade_gemfile_april_2019.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/downgrade_gemfile_april_2019)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/downgrade_gemfile_april_2019/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/downgrade_gemfile_april_2019/README.md)
- The latest version of Jekyll breaks in the production environment. This version builds okay.
cc: @amirbey

downgrade jekyll to resolve build problems with new version

---

_config.yml
blog/index.html

Fixes issue(s) #1825
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/apburnes/fix-pagination)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/apburnes/fix-pagination/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/apburnes/fix-pagination/README.md)
- Remove slashes from blog's markup pagination links
- Let the Jekyll's paginator handle slashes

Fix blog pagination to not add unnecessary slash to path

---

_plugins/author.rb

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/author-baseurl-check.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/author-baseurl-check)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/author-baseurl-check/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/author-baseurl-check/README.md)
- Trying to fix liquid template exception in Federalist only effected during master branch builds
- Master branch build error `Liquid Exception: undefined method `include?' for nil:NilClass in /_layouts/post.html`
- Federalist garden build [README](https://github.com/18F/federalist-garden-build#environment-variables) states the `BASEURL` is not set on live site …

Check baseurl nil for author set_site_url method

---

package-lock.json

Update `lodash` due to security vulnerability.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/update-lodash.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/update-lodash/)
- Ran `npm audit fix` to update `lodash` used in `package-lock.json` sub-dependencies.

Update lodash for security

---

_posts/2016-12-14-how-to-run-an-efficient-meeting.md

- Change 'call of people' to 'call on people' in [How to run an efficient meeting](https://18f.gsa.gov/2016/12/14/how-to-run-an-efficient-meeting/) blog post

fix typo in meetings blog post

---

_posts/2019-08-20-an-agile-software-development-solicitation-guide.md

The link to a Word file goes to GitHub, instead of to Federalist, so the link doesn't work. I've corrected that. I attempted to fix this in #3052, but in my haste to fix a live blog entry, I missed one of the links.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/word-link.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/word-link)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/word-link/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/word-link/README.md)
- Fix link to Word file
/cc @Dahianna

Fix one more Word file link in Agile software blog entry

---

_includes/head.html

Fixes issue #3040
- Update `siteurl` metadata to use the site url and not the `federalist_url` it was set using
- Enables twitter card to pull image when posting

Update header meta tags for site url

---

_sass/_components/blog-index.scss
_sass/_components/buttons.scss
_sass/_components/post-meta.scss
_sass/_components/search.scss
_sass/_core/variables.scss
assets/css/main.scss

Fixes issue(s) #3046
[`/blog` PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/apburnes-blog-post-adjustment/blog)
- Update related blog classes margin to `!important`
- FYI, The update to USWDS uses class selectors ie `.usa-grid :first-child` which overrides the related blog classes margins
To Review:
- View the layout for the blog and blog posts
- View the [search input](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/apburnes-blog-post-adjustment/search/?q=hello)

Fix blog layout after updating USWDS

---

README.md

Fixes issue(s) #2996 
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/doc-tagging/README.md)
- Add documentation for creating new tags to `README`
- Update repo Wiki too

Add documentation for creating a new tag to README

---

PULL_REQUEST_TEMPLATE.md

- This fixes a broken link in the pull request template. 
+ As you can see in the "Checklist" section below, the link to learn more about how to optimize images is currently being parsed as a relative path within GitHub. 
+ This PR updates the link URL to point to the styleguide hosted within the blog.  
Checklist:

Fix broken link in PULL_REQUEST_TEMPLATE

---

_includes/head.html

this will allow the 18f logo to populate on linkedin and Facebook if a specific page doesn't have an image
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/lg/metatag-image-1)
- update meta og title to work on FB /linkedin if there isn't a page image
Checklist:

add og image to metatags if no page image

---

_posts/2019-08-22-building-product-management-capacity-in-government-part-1.md
_posts/2019-11-19-building-product-management-capacity-in-government-part-2.md

- I was reading these two blog posts today, and I couldn't find the links to go between the two parts. I then figured out they were hiding in the "18F" and "agency perspective" links in the introductory paragraph. I expect a link to "18F" to go to the 18F website, so I didn't think to click it. This change makes the link text more obvious.
/cc @Dahianna

Make "part one" and "part two" links more legible in PM Perspective posts

---

_config.yml
sitemap.xml

Fixes issue(s) https://github.com/18F/18f.gsa.gov/issues/3142
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/bh-sitemap-url/)
- Removes the `federalist_url` config option (it's only being used for sitemap generation)
- Uses `site.url` instead to reflect 18f.gsa.gov in sitemap.xml
/cc @apburnes

Update sitemap.xml URL to 18f.gsa.gov

---

_includes/header.html
_includes/navigation/drawer.html
assets/js/index.js

Fixes #3188
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/3188-a11y-mobile-nav.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/3188-a11y-mobile-nav)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/3188-a11y-mobile-nav/)
[Preview README for this branch](https://github.com/18F/18f.gsa.gov/blob/3188-a11y-mobile-nav/README.md)
- Adds and controls `aria-expanded` to the "Menu" button, toggled in response to mobile menu opening and closing
- Adds label to mobile menu close button
- Sets focus to mobile menu container when opened
- Sets focus to "Menu" button when mobile menu is closed
- Closes mobile menu in response to <kbd>Escape</kbd> key press
- Traps focus to mobile menu container while …

Fix mobile menu accessibility, focus issues

---

_sass/_theme/_uswds-theme-typography.scss

Part of issue(s) https://github.com/18F/18f.gsa.gov/issues/3130 .
[:sunglasses: PREVIEW](https://federalist-d703a102-c627-4805-8934-78f5bf4c97da.app.cloud.gov/preview/igorkorenfeld/18f.gsa.gov/ik-font-update/)
- Change theme typography back to Helvetica to match 18F branding
Checklist:
/cc @Dahianna

Set theme typography to Helvetica

---

admin/config.yml

When a CMS editor goes to add a Service Project, there is a WSIWYG editor for the body of the page
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/apb-projects-markdown-1/)
- Add markdown widget to service projects collection

Add markdown editor to service projects content

---

_sass/_components/nav-subnav.scss
_sass/_theme/_uswds-theme-custom-styles.scss

Fixes issue(s) #3238.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/BRANCH_NAME.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/iamjolly/fix-sidenav-hover-contrast/)
[:sunglasses: PREVIEW the About page with corrected hover link contrast](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/iamjolly/fix-sidenav-hover-contrast/about/)
- Improve contrast of page submenu (`.sidenav a:hover`) when hovered
Screenshot of fix:

custom style for sidenav hover contrast, resolves #3238

---

_sass/_components/header.scss
_sass/_theme/_uswds-theme-custom-styles.scss

Fixes issue(s) #3229.
[:sunglasses: PREVIEW](https://federalist-d703a102-c627-4805-8934-78f5bf4c97da.app.cloud.gov/preview/igorkorenfeld/18f.gsa.gov/ik-nav-align/)
- Remove left padding from the list of navigation links (`navbar`)
/cc @Dahianna and @jstrothman (just FYI since we talked about this)

Remove padding in nav to align items

---

assets/img/guides/derisking.svg
assets/img/guides/user-interviews-love--c.svg
pages/guides.md

Fixes issue(s) #3244 and #3245  simultaneously, to prevent awkward alignment of the UX guide icon and title
👓  &nbsp; [Preview](https://federalist-d703a102-c627-4805-8934-78f5bf4c97da.app.cloud.gov/preview/igorkorenfeld/18f.gsa.gov/ik-add-derisking/guides/)
- Add derisking guide to the guides page, with icon
- Make the UX guide icon slightly larger
Checklist:
/cc @Dahianna

Add derisking guide to guide list, fix size of ux icon

---

_data/navigation.yml
_sass/_components/header.scss

[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/header-nav-guides.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/header-nav-guides)
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/header-nav-guides/)
- Change about to guides link for header nav

Switch about to guides in header nav

---

package-lock.json
package.json

Fixes dependabot vulnerability and upgrades netlify-cms to v2.10.63
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/update-netlify-v2_10_63.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/update-netlify-v2_10_63)
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/18f.gsa.gov/update-netlify-v2_10_63/)
- Update netlify-cms from v2.10.61 to v2.10.63

Update netlify-cms to 2.10.63 and fix fetch vulnerability

---

_sass/_components/blockquotes.scss

Proposed fix for https://github.com/18F/18f.gsa.gov/issues/3181.
- convert `em` units to `rem`
It appears the `em` calculation was getting misapplied in IE11 so the easiest fix I could think of is to do a simple conversion to `rem` units. However the catch is upwards of `1px` is shaved off of the quote character, depending on the screen size, since root is defined as `11px` (summarized below).
| Screen size | Intended Font Size | Proposed Font Size |
| --- | --- | --- |
| Mobile | 60px | 59.95px |
| Tablet | 80px | 79.75px |
| Desktop | 100px | 99px |
I'm not sure what your design tolerance is for changes like this so if you still need to hit the original sizes I can update the PR to do so. I can do the division right in the style declaration itself, …

convert em units to rem

---

_assets/js/external-links.js
_config-accesslint.yml
_config-blog.yml
_config.yml
_includes/javascript.html
_sass/_theme/_uswds-theme-color.scss

Fixes issue(s) #3132 by closing out the final piece of criteria.
[![CircleCI](https://circleci.com/gh/18F/18f.gsa.gov/tree/apb-external-link-js.svg?style=svg)](https://circleci.com/gh/18F/18f.gsa.gov/tree/apb-external-link-js)
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/apb-external-link-js/)
- Adds a snippet of js with `external-links.js` to add the `usa-link--external` for any non .gov or .mil links
- Ignores the `usa-social-link` icons to twitter, linkedin, and github
- Ignores the GSA logo

Add external link js to add icon for non gov and mil sites

---

_sass/_components/blog-index.scss
blog/index.html

Fixes issue(s) #[3258](https://github.com/18F/18f.gsa.gov/issues/3258) - Happy New Year!
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/BRANCH_NAME/)
- Remove blog search bar
- Remove unused style def for search bar 
- Add styling to next component down to maintain the blue border at the top of the sidebar. I used the `Contact` page as a reference but if this is wrong let me know and I will modify it. 
Checklist:
/cc @apburnes @Dahianna

Remove blog search bar

---

_sass/_components/header.scss

This PR adjusts the color of the bar under the current page in the navigation to an 18F brand color.
😎  &nbsp; [Preview](https://federalist-d703a102-c627-4805-8934-78f5bf4c97da.app.cloud.gov/preview/igorkorenfeld/18f.gsa.gov/ik-current-link-color/what-we-deliver/)
The current color is `cyan-70` which is not in our brand color palette
/cc @Dahianna

Ik current link color

---

README.md

This PR updates the readme instructions to include a step to run `npm install` when running locally. I was encountering an issue where the local server wouldn't start up because it was missing a `netlify-cms` js file. Running npm install solved the issue.

Update running local instructions

---

_assets/js/external-links.js
_sass/_components/blog-index.scss
_sass/_components/card.scss
_sass/_components/post-list.scss
blog/index.html

Fixes issue(s) #3258 thanks to @nate-io 
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/nate-io/remove-sidebar-search/blog/)
- Remove blog search bar
- Remove unused style def for search bar
- Add styling to next component down to maintain the blue border at the top of the sidebar. I used the Contact page as a reference but if this is wrong let me know and I will modify it.

Nate io/remove sidebar search

---

_includes/navigation/footer.html

Role `Logo image` is not a valid value for `role` attribute. Use `img` instead.
See:
- https://html.spec.whatwg.org/multipage/infrastructure.html#attr-aria-role
- https://w3c.github.io/aria/#introroles
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles
- https://designsystem.digital.gov/components/identifier/
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/aduth-identifier-img-role/)

Update identifier logo image role to valid role

---

_includes/navigation/footer.html

`javascript:void(0);` is from demo code markup for USWDS identifier component and should be substituted with the URL of the agency website. Currently, clicking the link does nothing.
See:
- https://designsystem.digital.gov/components/identifier/
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/aduth-identifier-logo-link/)

Update identifier logo image link to direct to GSA homepage

---

Gemfile
Gemfile.lock

Fixes issue(s) dependabot alert for nokogiri
[:sunglasses: PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/apb/update-nokogiri/)
- Update nokogiri to `>= 1.11.1`

Update nokogiri to >= 1.11.1

---

_includes/testimonial.html
_sass/_components/blockquotes.scss

This PR changes the layout of the testimonial, moving the attribution below the quote and shifting over the quote to the center. I polled designers on Slack, and they preferred this layout over the current side by side layout. 
👓  [Preview](https://federalist-d703a102-c627-4805-8934-78f5bf4c97da.app.cloud.gov/preview/igorkorenfeld/18f.gsa.gov/testimonial/)

Change layout of testimonials

---

_layouts/project-page.html
_services_projects/doj-crt-portal.md

Fixes the sidebar template issue in #3386 by correcting a tag and adding the `sublist` class to most sidenav items. 
👓 &nbsp;[Federalist Preview](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/project-template-fix/what-we-deliver/doj-crt/)

Project template fix

---

_posts/2016-03-22-helping-california-buy-a-new-child-welfare-system.md
_posts/2016-09-20-mississippi-agile-modular-techniques-child-welfare-system.md
_posts/2016-10-28-california-takes-new-approach-procurement.md
_posts/2016-11-14-modular-procurement-state-local-government.md
_posts/2016-11-17-leadership-innovation-california-child-welfare-services.md
_posts/2017-09-12-how-alaska-is-using-transparency.md
_posts/2018-05-22-using-agile-methods-to-improve-the-rfp-process.md
_posts/2018-07-03-presidential-innovation-fellows-bringing-new-approaches-to-nations-biggest-challenges.md
_posts/2018-10-09-implementing-rules-without-rules-engines.md
_posts/2018-10-16-exploring-a-new-way-to-make-eligibility-rules-easier-to-implement.md
_posts/2018-10-25-modular-contracting-and-working-in-the-open.md
_posts/2020-05-12-rapid-implementation-of-policy-as-code.md
_posts/2020-12-17-18f-and-tts-office-of-acquisition-award-first-assisted-acquisition.md
_posts/2021-03-31-18f-public-benefits-portfolio-reflects-on-the-last-year.md
tests/schema/tags.yml

Signed-off-by: Robert Jolly <robert.jolly@gsa.gov>
Updates requested by the Public Benefits Portfolio team due to name change from Human Services Portfolio. This PR changes the tag "health and human services" to "public benefits" in the tests/schema/tags.yml and 14 posts. Replacing tag was preferred over adding a new tag at this time. 
cc/ @Dahianna for review and approval.

tag change: health and human services to public benefits

---

_posts/2021-04-01-building_a_user-centered_data_strategy.md

This post has a non-breaking space (`&nbsp;`) between words, resulting in two spaces between "understanding" and "their". This patch removes the non-breaking space and replaces it with a single space.

Removes non-breaking space between words

---

admin/config.yml

Allow the netlify CMS to create new services projects pages

All CMS to create new services projects pages

---

.circleci/config.yml
pages/home.html

Signed-off-by: Robert Jolly <robert.jolly@gsa.gov>
Resolves issue described in #3523 -> unfriendly `alt` was being set on otherwise decorative images for agency logos in home page "who we've worked with" section
(Optional) Closes #3523.
Make sure that automated checks are ok

remove alt for decorative image, resolves #3523

---

_sass/_templates/how-we-work.scss
pages/how-we-work.md

This PR adjusts some of the styling issue on the current `How-we-work` page:
1.  It  aligns the text of the service offerings with the introductory text. 
2. Adds more consistent spacing and groupings of sections. Headers and subheaders are placed closer to one another and closer to the text, meanwhile there is more space between different service offerings. This way there are "units" of information, grouped together. 
3. Icons are sized down slightly so they don't run into the text
4. Remove the medium-blue lines from the sidebar for the acquisition section that currently don't have additional details about team size or duration. 
👓 &nbsp;[Preview](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/ik-hww-styling/how-we-work/)

Adjust spacing and sizing on hww page

---

pages/vulnerability-disclosure-policy.md

Allows VDP and bug bounty to apply pre-release when authorized.
Tag @LindsayYoung @JJediny @rpalmer-gsa -- Can this work?

Allow VDP to used for testing pre-release

---

_sass/_components/blockquotes.scss

I noticed blockquote styling is uncomfortably cramped with the left border, and would benefit from padding and typographic styling. 
This pull request:
- adds padding between the blockquote border and the text
- applies italic styling to blockquotes for typographic differentiation
[🔍 PREVIEW](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.app.cloud.gov/preview/18f/18f.gsa.gov/rj-blockquote/2022/07/13/content-design-ada/)

Adds padding and italics to blockquote elements

---

_data/usa_anchor.yml
_includes/footer.html

This changes the links in the footer to match the up-to-date requirements of GSA policy. The links match those currently showing on https://derisking-guide.18f.gov/. Included in this change is the added privacy policy link that will close #3601 .

Modernize footer links and link text

---

_authors/stacy-dion.md
_posts/2022-08-09-senior-executives-pt3.md
_posts/2022-08-11-senior-executives-pt3.md

Creates a new post for the blog entitled Senior executives part 3: use short-term initiatives to build confidence in long-term decisions
@jstrothman date for publication is set for tomorrow, 08/09/2022. If that changes the file name and the meta data will need to be updated.
Make sure that automated checks are ok

New Blog Post: Senior executives part 3

---

_layouts/post.html

Add the `id="main-content"` to the blog post template so that the code in `_includes/skipnav.html` from the `uswds-jekyll` theme will know where to skip on the page in a blog post. 
Closes #3510.

Add id main-content to make skip navigation work

---

README.md
_includes/tag-results.html
examples/blog-post.md

Adds alt text for images on the blogpost feed page. 
(No existing issue for this bug)
Current website:
Note there is no alt text for the image.

Post index image alt

---

_includes/card.html
_sass/_components/card.scss

Closes #3457 
- removes "Read More" link in card footer
- wraps entire card container in a link
- styles card H3 to look like a link
- adjusts card hover effects to denote entire card as a link
With right card hover:

Make whole card clickable (including image) for featured projects

---

_layouts/styleguide.html
_posts/2014-11-17-taking-control-of-our-website-with-jekyll-and-webhooks.md

The pa11y build was failing in CI. To repro the problems, I ran pa11y locally and it surfaced two different issues.
- The styleguide layout was using a `<main>` tag with an id of `main-content` nested inside a `<main>` tag coming from the `uswds-jekyll` template.
- An old blog post was using an embedded IFFT iframe that had an error. 
The fixes:
-  I changed the interior main element in `styleguide.html` into a div. It did not appear to change the layout or style of the element.
- The embedded recipe no longer exists, and if you try clicking on it you get an error. I removed the iframe element and references to it.

Fix pa11y problems

---

_sass/_components/header.scss
pages/home.html

This PR addresses a bug where the "get in touch" button and the logo click areas were extending past the boundaries of the viewable element. To solve this bug I:
- Changed an anchor tag wrapping a button element into an anchor tag with button classes and;
- Added a `display: flex` to the `header-logo` element. USWDS default header assumes a logo image with clickable text next to it; since 18F's logo does not need extra text, the alignment of the clickable element was getting messed up. 
(Optional) Closes #3456 

Update get in touch button html

---

_posts/2015-07-15-openfec-api-update.md

The page https://18f.gsa.gov/2015/07/15/openfec-api-update/ embeds a [tweet](https://twitter.com/mheadd/status/619098677710340096) from an account which is now private. This tweet doesn't end up in the published page, but I noticed this error in a build log when using this site to test something for cloud.gov Pages:
```
INFO [build-jekyll] @branch: main @buildid: 1 @owner: 18F @repository: 18f.gsa.gov @message: OEmbedError: The url, https://twitter.com/mheadd/status/619098677710340096, is not available as an oembed. Consider using an HTML embed instead.
```

Change to legacy content: remove broken oembed of tweet from private account

---

_posts/2022-08-10-18f-tech-sandwich.md

I noticed the format of the tags (with hyphens) in this post is preventing them from behaving like tags
This PR removes the hyphens so `open-source` and `open source` aggregate the same posts.

Hyphens are breaking tags

---

_includes/card.html
_sass/_components/card.scss

This change:
- Moves box-shadow into css rather than via utility classes on the element directly
- Adds the box-shadow on a featured card when you tab to the element
(Optional) Closes #3642

Add featured card box-shadow on focus

---

_includes/post.html
_sass/_components/featured-posts.scss

-  Removes Read More links at the bottom of featured blog posts
- Adds underline to header links when user hovers above them to make it clearer they are links
(Optional) Closes #3627

Remove read more links from featured blog posts

---

_sass/_components/post-details.scss

- changes the post-author and post-tags link colors to #046B99 (["accent-cool" reference](https://github.com/18F/18f.gsa.gov/blob/main/_sass/_theme/_uswds-theme-color.scss#L80))
Closes #3410

Update CSS to use correct colors

---

.github/workflows/on_new_issue.yml

Adds some automation so when an issue is opened in this repo is it added to the delivery assurance shared projects board for tracking,
(Optional) Closes #3650 

Add on_new_issue.yml automation

---

_layouts/post.html

Removes quote typo.
"In a world where punctuation has run amok...."
[:boom: CUT TO EXPLOSIONS :boom:]
"...one stands alone..."
[CUT TO **Asterisk** (villan, surrounded by army of **Tildés**.)]
**ASTERISK**: "Rogue, your time of ending quotations are... OVER!"
[CUT TO VIEW OF REARVIEW MIRROR - CAR FLIPPING IN MID AIR, WITH **Period** SCREAMING]
**ROGUE QUOTE** (looking at rearview): "Consider that statement over. Period!"
"A rebel takes on the forces of the Lint Brigade."
**ROGUE QUOTE**: "Put me in, Dr A. Anywhere. I don't care. I will go unnoticed.... like a ninja shadow."  
**DR AMPERSAND**: "That's what I'm afraid of. It could be years!"
**ROGUE QUOTE**: "Even better."
[ CUT TO A HELICOPTER EXPLODING 🚁 💥 , BUILDING EXPLODING 🏨 :boom: , A SANDWICH EXPLODING. 🥪 💥 ] 
[ Music and SFX cuts …

Delete extra quote

---

_includes/side-cta.html
_layouts/project-page.html
_sass/_components/cta.scss
_sass/_components/lists.scss
_sass/_uswds-theme-custom-styles.scss

This PR addresses the a11y issues noted in the [a11y audit doc](https://docs.google.com/document/d/1ijBREMLbH6a0NoWaS0BM94vc81z3mfcuJ2yNMOn4Pi0/view)
- Updates the `H5` headings in the sidebar to `H3`s while maintaining the same visual style
- Replaces the CTA mixed button and link element with button
- Moves the `blockquote` in the sidebar inside an `li` so that the `blockquote` is not a direct descendent of a `ul`
In addition the the items noted in the audit doc, this PR updates the above elements so that:
- The hover state in the CTA button contrasts more against the background
- Updates the styling of the `blockquote` so that is not so narrow in the sidebar and more closely matches the style of the quotes on the home page
Closes TLC #[217](https://github.com/18F/TLC-crew/issues/217)
👓 …

Fix what we deliver project page a11y issues

---

_sass/_templates/home.scss
_sass/_uswds-theme-custom-styles.scss

Fixes #3709 by removing all CSS order properties manually set in the home template.

Tlc footer order

---

blog/index.html

Removed "most popular" blog post widget. These aren't the most popular posts overall. The most popular posts are usually going to be very old. The top 10 posts since 2014 are from 2014-2016.
[View preview](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/rm-not-most-popular-blog-posts/blog/)

Remove "most popular" blog post widget

---

_includes/footer.html
_includes/navigation/sidenavnew.html
_includes/navigation/subnav.html

This PR completes TLC Ticket [#212 Remediate 18f website global a11y issues](https://github.com/18F/TLC-crew/issues/212)
Resolved last issue on ticket, the removal of unneeded ARIA `role` attributes. 
The `navigation` role was removed from the `nav` elements. The `contentinfo` role was removed from the `footer` element.

Removed unneeded ARIA role attributes from nav and footer elements

---

blog/index.html

Updated blog index page sidebar links. Made them consistent with the links on the contact page. This fixes the weird external link behavior.
[Review this change](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/blog-sidebar-links/blog/)

Updating blog sidebar links to match contact page

---

_includes/featured-posts.html

This PR removes an extra forward slash from featured posts links which was breaking the post links. 
👓 [Preview](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/ik/fix-blog-links/)

Fix url for featured posts

---

pages/work-with-us.md

This PR corrects the links to the two de-risking guides, which were linking to the wrong guides.
👓 [Preview](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/ik/fix-dersiking-links)

Fix de-risking guide links on work with us page

---

_about/index.md

This PR updates the link on the about page from the Office of Products and Programs to TTS Solutions. 
👓 [Preview](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/ik/fix-about-link/about/)

Fix reference and link for TTS solutions

---

.circleci/config.yml
.pa11yci

- Adds a chromium headless browser config to get pa11y scanning urls in CircleCI job post ruby 3 upgrade
- Also bust dependency caches for ruby and node from the ruby 3 upgrade
Closes #3773

Fix: get pa11y running in CircleCI again

---

_data/guides.yml
_posts/2018-03-13-win-big-by-going-small.md
_posts/2018-07-26-what-we-learned-from-building-a-pool-of-agile-vendors.md
_posts/2019-02-28-prerequisites-for-modular-contracting.md
_posts/2020-03-10-ask-18f-po-vs-cor.md
_posts/2020-03-31-building-a-collaborative-culture.md
pages/work-with-us.md

This PR updates the various links to the Agile guide to use the new URL/address (ie, from `agile.18f.gov` to `guides.18f.gov/agile`)

Update Agile guide links

---

_data/guides.yml

Updates dynamic URL's for the Content, Derisking, and UX Guides. 
This means the guides landing page will use the updated URL's. 
This is part of TLC Crew's work to [finish migrating the guides](https://github.com/18F/guides/issues/156) to 11ty. 

Update dynamic urls for content, derisking, ux guide

---

Gemfile

We shouldn't lock specific ruby versions ([3.2.3 was released earlier this month](https://www.ruby-lang.org/en/news/2024/01/18/ruby-3-2-3-released/)) so I added an `~>` operator which will only upgrade to patch semver, e.g., `3.2.x` versions. We probably can be more permissive here with ruby versions but this will do for now.

Update ruby dependency with approximately greater than operator

---

_sass/_components/button.scss

Accessibility contrast bug on "our work" page with Chrome

---

pages/home.html

Changes the third "Work with us" link on the homepage to have the correct href name, matching the rest

Change the third work with us link to be correct

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md

This PR creates a CODEOWNERS file to automatically tag the TLC crew when opening new pull requests, and includes an update to the pull request template to request a review from @quarterback (who will coordinate with Outreach as appropriate) if the change is in content. 

Add CODEOWNERS and clarify how to loop in Outreach. 

---

_posts/2023-02-13-looking-back-and-forward.md
_posts/2023-04-20-hi-from-the-18F-design-chapter.md

Adds a hyphen in "user-centered design" in the tag that pulls blog posts on the website together. Currently two blog post have the tags listed without hyphens, which prevents all posts from being shown.

Add hyphen to user-centered design tag

---

_authors/amanda-kennedy.md
_posts/2024-03-05-customer-experience-beyond-surveys.md

- Adds @amandarkennedy as an author
- Adds blog post "Customer experience: beyond surveys"

Add blog post and new author

---

_authors/matt-cloyd.md
_authors/qituwra-anderson
_authors/qituwra-anderson.md

There were two conflicting files for qituwra-anderson. The most recent (plaintext) had published=true, the older one (Markdown) had published=false.
Every time the site gets built, there's a little warning in the logs about this conflict.
This PR deletes the plaintext file and sets the markdown file to published=true (the most recent value).

Fix author alert message

---

package-lock.json
package.json

Previously, the Node version specified in package.json was too low for the lockfileVersion. This caused problems like the styles not rendering in development.
This specifies a higher version of Node, as well as a higher version of NPM, to ensure lockfile compatibility.
Closes #3818

Upgrade node version

---

Gemfile.lock
_includes/card-with-image-guides.html
_sass/_components/card-with-image-guides.scss

Closes  https://github.com/18F/TLC-crew/issues/724 for fixing heading order on the [Guides home page](https://18f.gsa.gov/guides/). 
- Changed card `h3`s to `h2`s to keep proper heading order.
- Copied font styles from `h3` and applied to card `h2`s only.
- Makes no visible change and still matches the design file.

Fix the Guides home page's heading order

---

_sass/_components/blog.scss

Add some style rules to differentiate code blocks from regular text and to wrap text so it doesn't overflow.
#3824 
#3823

add code block styling on 18f blog 

---

.circleci/config.yml
.github/workflows/pull-request.yml

Fixing check failures as we go along.
- [Cloud.gov pages for 18f.gsa.gov](https://pages.cloud.gov/sites/3/builds) now builds properly, allowing us to have previews
- Github workflows are [temporarily disabled](https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow) so we aren't indundated with emails 
- Removed CircleCI checks that have to do with ruby/bundler
- Disabled pa11y checks until we are in a place to get it to work again with @caleywoods' newer work
- Added build, lint, html validation, and link testing to the build steps so that checks are immediately useful and reflective of build quality in the PR

Replatform: fix checks

---

.github/workflows/repository_dispatch_create_issue.yml

This PR adds a new GitHub action that kicks off when a [`repository_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch) webhook event is received. This webhook is currently only called from CircleCI if there are failure(s) encountered during the scheduled nightly pa11y scan.
I'm separating this workflow file/action out into a new branch/PR because the action needs to exist on the default branch (`main`) in order for me to test my webhook call.

Add GH action for creating issues when a nightly pa11y scan fails

---

.github/workflows/repository_dispatch_create_issue.yml

Updates the GitHub action that responds to the `repository_dispatch` event (currently sent by CircleCI) and wraps the body in backticks to try and keep it from rendering the HTML that is returned in the event payload which ends up being the body of the PR.

Update GitHub action repository_dispatch template

---

_posts/2024-06-18-back-to-basics-in-the-age-of-ai.md

This PR updates the heading levels on the recent AI blog post. The post currently uses several `h1`s but it is best practice to use just one `h1` on a page, which for the 18F blog is the title of the post. This PR adjusts all the headings down one level (`h1` to `h2`, `h2` to `h3`, etc...) so only the post title remains the `h1`

Shift heading levels on AI blog post

---

Procfile
README.md

Something is wrong with the `./serve` command — that `&` detaches a process, and I'm often running into port conflicts that have to be shut down with `killport`.
There's a better way.
This commit:
- Adds a Foreman-based local dev server:
- Adds a Procfile for building assets and running the server
- Adds instructions to the README for using this
- Corrects references to localhost in the README
You can still use the `./serve` commands if they work for you.
Closes #3819

Better local dev server

---

content/pages/author.liquid
content/pages/home.html
content/pages/our-work.html
content/pages/work-with-us.html
content/posts/2019-10-29-culture-climate-survey.md
content/posts/2022-01-21-what-have-you-learned-from-other-18F-designers.md
content/posts/2023-04-25-18f-checks-in-with-the-dawson-project-at-the-us-tax-court.md
content/posts/2023-09-07-catching-up-with-the-tanf-data-portal-project.md
content/posts/2024-02-01-gathering-feedback-with-customer-panels.md
content/posts/2024-04-03-18f-practices-in-action.md
content/posts/posts.json
content/posts/posts.liquid

- Fix blockquote formatting. All the blockquotes that were rendered with HTML are now rendered with Markdown. Jekyll would render HTML with a `markdown=1` or `markdown="1"` attribute, but 11ty does not. Changing the HTML blockquotes to Markdown now renders with the correct styles.
- Reformat paginators so they all use regular liquid/YAML syntax
- Add or edit layout attributes. Previously, `/our-work` had no layout (so had no styling), and `/work-with-us` used `default` when it should use `primary`.
- Render only featured agencies on the homepage. Previously, the liquid syntax wasn't working as expected, so we needed to add an extra `assign` clause.

Clean up styles

---

content/posts/posts.json
content/posts/posts.liquid

Revert to using posts.json
It's a bit of a mystery to me why posts.liquid and posts.json differ when using the same syntax, but it appears the site doesn't build most posts when it's posts.liquid, but it works fine when it's posts.json. Maybe it's something to do with how the data pipeline works.
So, we'll leave it as JSON.

Revert to using posts.json

---

_posts/2024-07-17-working-with-oracle-databases-in-open-source-projects.md
_sass/typography.scss

This PR shifts the headings in the databases blog post down one level, so that there is only a single `h1` headings on the page. Our blog uses the post title as an `h1`, so I've shifted every other heading by 1 (`h1`-> `h2`, `h2`->`h3`, etc...). The exception to this this was the last two headings for the Conclusion and Special Thanks, which seemed like they were not part of the "Tutorial Part 2" section, but if that's incorrect happy to adjust.

Update heading levels for oracle blog post

---

content/pages/feed/feed.md

Added ATOM feed. Switched from the Jekyll generated feed.
The feed.xml file validates and matches the previous/current Jekyll generated feed.
Not in scope:
- Remove Eleventy RSS plugin and references to it.
Closes #3962 .
- NOT NEEDED
- NOT NEEDED
- NOT NEEDED

Added ATOM feed

---

_data/agencies.yml
_data/navigation.yml
_includes/footer.html

Standardizes footer: some links were hardcoded, some were from data — now they're all from data.
Also, added a missing Forest Service agency/logo

Footer & Forest Service

---

_sass/_components/blog.scss

Closes #4022
Turns out the code wasn't vertically aligned to top, so any time the code block had the overflow-x scrollbar, something about the text block alignment would shift.
This aligns things to top, and fixes the padding/margins at the top so they always align, horizontal scrollbar or not.

Fix code block alignment, mostly by aligning text to top

---

_data/anchor.yml
_includes/meta.html
config/collections/tags.js
config/markdown/headingLinks.js
config/shortcodes/imageWithClass.js
content/pages/work-with-us.html

- Sort posts on tag pages by date descending
- Fix broken No FEAR act URL (unrelated to last fixes but important)
- Revert tab title segments despite being sad about it
- Fix undefined alts by setting default alt (and class) to empty string
- Change page layout for work-with-us so the `lead` shows up
Closes #4037, #4039, #4040, and #4042

Start fixing last issues

---

data/social_media.yml
templates/social-media.html

Solution options here were:
1. spend a long time figuring out why the Markdown renderer that's supposed to handle links isn't seeing the "18F on {platform}" links in the social media sidebar, or
2. manually mark them external
I opted for 2 just to get the migration done for now.
I've listed a task in #3864 to handle this more systematically — our renderers not in good condition to be maintainable in the long run, so this is pennies on top of an already hefty technical debt.
Fixes #4053

Manually correct social media external links

---

.circleci/config.yml

I noticed [in the CircleCI dashboard](https://app.circleci.com/pipelines/github/18F/18f.gsa.gov/3485) that the `.circleci/config.yml` file on `main` had syntax issues. I looked at the config file locally and the CircleCI config validator that is part of their CLI toolkit reported the same issues.
I used the CircleCI config editor on their site to help understand what needed to change since both the CLI validator and the error in the CircleCI dashboard are hard to understand. The changes are simple, just moving the lint, build, and verify steps into `run` blocks, their previous syntax looked like maybe it was meant to use commands `lint`, `build`, and `verify` but they weren't being defined in a [commands block](https://circleci.com/docs/configuration-reference/#commands) prior to being …

CircleCI config syntax fixes

---

templates/footer.html

Inside `templates/footer.html` the max width class being applied to the social media logos had an extra `m` in the class name.

Fix social media link class typo

---

package-lock.json
package.json

Updates the `markdown-it` markdown rendering library to v13.x.x to address [SNYK-JS-MARKDOWNIT-6483324](https://security.snyk.io/vuln/SNYK-JS-MARKDOWNIT-6483324). 
This partially addresses #4068 but the build on that PR fails I think because of the `glob` update. There will be a separate future PR to update `glob`.

Update markdown-it to fix SNYK-JS-MARKDOWNIT-6483324

---

.allstar/admin.yaml

Allows 3 admin teams to be assigned to this repo, instead of the default 2. This commit updates the security config to override the base AllStar configuration.
We appear to need 3 teams, 2 are TTS tech managers, the third is the TLC Crew leads who own the management of the site.
Closes #4128

Update security config to allow 3 admin teams

---

content/posts/2023-03-23-A-check-up-for-agile-teams.md
content/posts/2023-04-20-hi-from-the-18F-design-chapter.md
content/posts/2023-05-08-andrew-hyder-award.md
content/posts/2023-06-13-The-four-operating-levels-of-18F-projects.md
content/posts/2023-08-22-7-tips-on-facilitating-unplanned-topics-in-meetings.md
content/posts/2023-09-05-first-do-no-harm.md
content/posts/2023-09-07-catching-up-with-the-tanf-data-portal-project.md
content/posts/2023-09-21-18f-website-refresh.md
content/posts/2023-12-05-Sharing-artifacts-and-outputs-from-research.md
content/posts/2024-01-12-andrew-hyder-award.md
content/posts/2024-02-01-gathering-feedback-with-customer-panels.md
content/posts/2024-03-05-customer-experience-beyond-surveys.md
content/posts/2024-03-19-18f-at-ten.md
content/posts/2024-08-20-andrew-hyder-award.md
content/posts/2024-09-12-derisking-guide-update.md
content/posts/2024-10-08-18f-year-of-launches.md

I noticed that the "year of launches" post has no tags — they're all commented out, even though they look quite relevant.
The tags that were commented out are written using dashes, which is the wrong tag format — they need to be space-separated. So, my guess is that they were commented out because they were causing build errors.
This commit:
- Adds back commented-out tags
- Cleans up title and excerpt formats from posts from the last year or so

Cleaning up front matter from the last year or so

---

content/posts/2024-10-21-18f-folks.md
content/posts/2024-12-5-18f-project-defaults.md
templates/adjacent_page_links.html
templates/featured-posts.html

- Make blog navigation sentence case
- Add tags to recent blog posts that didn't have them
[Preview URL](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/mr/blog-tidying/blog/)

Make "Previous post / Next post" sentence case and add tags to selected posts
